/**
 * SOP — Google Ads (13 tâches)
 * Rôle incarné : Senior Google Ads Specialist — 30+ ans, Google Premier Partner.
 * Concentre l'expertise réelle : Keyword Planner, tCPA/tROAS, Performance Max,
 * Quality Score, GTM/GA4, Consent Mode v2, offline conversions.
 */
import type { SopBlock } from '@/hooks/useSops'
import {
  introExpert, etape, finalCheck, qaCheck, promptCards,
  conseilsSenior, validationFinale, escalade, projectContext, h2, tip,
} from './sopHelpers'

const norm = (s: string) => (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim()

const ROLE = 'Senior Google Ads Specialist — 30+ ans, Google Premier Partner, 8-figure budgets'
const CANAL = 'Blocage / question stratégie → Projet → Discussion (canal SEA)'

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_AUDIT: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Photographier l\'état d\'un compte Google Ads existant en 45 min pour identifier gaspillage + opportunités',
    resultat: 'Rapport d\'audit 1-pager listant : top 5 gaspillages (par CPA), top 5 opportunités, score global /100.',
    delai: '45 min compte petit (< 5k€/mois) · 2 h compte moyen · 4 h compte gros (> 50k€/mois)',
    canal: CANAL,
    regle: 'JAMAIS toucher aux enchères pendant l\'audit. Photographier d\'abord, agir ensuite.',
    prerequis: ['Accès lecteur Google Ads (via demande d\'accès MCC → ID client)', 'Accès GA4 en lecture', 'Fiche projet à jour'],
  }),
  ...projectContext(['client.name', 'client.company', 'project.budget', 'domain']),
  h2('Étapes'),
  ...etape('1. STRUCTURE ET SANTÉ COMPTE', {
    objectif: 'Cartographier tous les points où le compte perd de l\'argent',
    temps: '15 min',
    ou: 'Google Ads → Vue d\'ensemble + Colonne « Optimisation » + Historique modifications',
    actions: [
      'Google Ads → Vue d\'ensemble → screenshot 90 derniers jours (CPA, ROAS, taux de conv)',
      'Campagnes → colonne « Statut » → repère « Limité par le budget », « Learning Limited », « Below First Page Bid »',
      'Colonne « Optimisation Score » → note < 80% = signal fort',
      'Outils → Historique des modifications → dernières 30 jours → repère qui a touché quoi',
      'Note dans Projet → Documentation → tableau : 1 ligne par campagne = statut / budget / CPA / conversions',
    ],
    resultat: 'Tableau complet compte + score global chiffré.',
    verification: ['Score d\'optimisation noté', 'Chaque campagne classée « saine / à surveiller / à couper »', 'Historique changements récents relevé'],
    erreurs: [
      ['« Limited by budget » ignoré', 'C\'est le premier lever à activer — souvent 20% de conversions gratuites en levant le budget de 20%.'],
      ['Optimisation Score pris à la lettre', 'Google pousse ses features (PMax, Broad Match). Filtre : ne suis que les recos qui améliorent CPA/ROAS observé.'],
    ],
    conseil: 'Le compte le plus rentable est rarement le plus complexe. Souvent 2-3 campagnes claires > 30 campagnes fragmentées.',
  }),
  ...etape('2. QUALITY SCORE ET RECHERCHE GASPILLAGE', {
    objectif: 'Trouver les mots-clés qui brûlent le budget sans convertir',
    temps: '15 min',
    ou: 'Rapports → Rapports personnalisés + Onglet Mots-clés',
    actions: [
      'Mots-clés → filtre : coût > 100 MAD ET conversions = 0 sur 30 jours',
      'Screenshot du tableau → colle dans Projet → Documentation',
      'Colonne Quality Score → repère les mots-clés < 5/10 → sous-optimisation landing ou pertinence',
      'Termes de recherche → filtre : impressions > 100 ET « Ajouté / Exclu » = vide → mots-clés négatifs manquants',
      'Rapport recommandations Search Terms → export CSV',
    ],
    resultat: 'Liste des 10 pires mots-clés à supprimer + 20 mots-clés négatifs à ajouter.',
    verification: ['Top gaspillage identifié en MAD', 'Liste négatifs prête à importer via Ads Editor'],
    erreurs: [
      ['Supprimer un mot-clé sans check impressions', 'Peut couper 30% du trafic. Vérifie toujours part d\'impressions perdue.'],
      ['Quality Score = 3 traité comme urgence', 'QS n\'est pas linéaire avec CPA. Regarde d\'abord CPA/ROAS, QS ensuite.'],
    ],
    conseil: 'Les termes de recherche révèlent 80% des angles morts. Regarde-les avant même les mots-clés.',
  }),
  ...etape('3. TRACKING ET LIVRAISON', {
    objectif: 'Confirmer que ce qu\'on voit dans Ads = ce qu\'on voit dans GA4 (± 5%)',
    temps: '15 min',
    ou: 'Google Ads → Objectifs · GA4 → Attribution · GTM',
    actions: [
      'Google Ads → Outils → Conversions → repère « Statut : Aucune conversion récente » → tracking cassé',
      'Vérifie que Enhanced Conversions est ON (User-provided data ou tag)',
      'GA4 → Acquisition → Trafic → filtre source=google/cpc → compare conversions vs Ads (±5% OK)',
      'GTM → Preview → simule un achat/lead → confirme tag Google Ads Conversion fire une seule fois',
      'Consent Mode v2 : vérifie que les paramètres ad_storage + ad_user_data + ad_personalization sont bien envoyés',
    ],
    resultat: 'Rapport tracking : ✅ conversions cohérentes ou ⚠️ écart identifié.',
    verification: ['Écart Ads vs GA4 mesuré', 'Enhanced Conversions actives', 'Consent Mode v2 vérifié'],
    erreurs: [
      ['Duplication conversions (tag dans GTM + gtag direct)', 'Divise le nombre de conv par 2. Supprime l\'un des deux.'],
      ['Consent Mode v2 non déployé (depuis mars 2024)', 'Perte de 15-40% de conv observables en Europe. À corriger en 1er.'],
    ],
    conseil: 'Un compte propre en tracking > un compte optimisé en enchères. Fixe le tracking avant tout.',
  }),
  ...finalCheck([
    'Rapport 1-pager archivé dans Projet → Documentation',
    'Top 5 gaspillages chiffrés en MAD',
    'Top 5 opportunités priorisées (impact/effort)',
    'Statut tracking : ✅ / ⚠️ / 🚨',
    'Score global /100 attribué',
    'Prochaine action recommandée définie',
  ]),
  ...qaCheck([
    'Le rapport est-il compréhensible par un client non-technique ?',
    'Les gaspillages sont-ils chiffrés en MAD, pas en % ?',
    'Chaque recommandation a-t-elle un effort estimé (1-3-5 jours) ?',
    'Le tracking a-t-il été vérifié bout-en-bout ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Synthétise un audit Google Ads en 1-pager client',
      prompt: 'Tu es Senior SEA Consultant. Voici les métriques 90j de mon compte Google Ads (CSV collé) : [CSV]. Rédige un audit 1-pager en français destiné au client : (1) Score global /100 (moyenne pondérée QS + optimisation score + tracking + ratio CPA/AOV), (2) Top 5 gaspillages chiffrés en MAD/mois, (3) Top 5 opportunités priorisées matrice impact/effort. Zéro jargon. Ton direct.' },
    { agent: 'Claude Code', title: 'Debug tag Google Ads Conversion via GTM Preview',
      prompt: 'Voici les datalayer events de mon site (colle JSON). J\'utilise GTM avec un tag « Google Ads Conversion Tracking » qui fire sur trigger custom event=purchase. Le tag ne se déclenche pas. Analyse : (1) Quel trigger devrait fire ? (2) Quelle variable extraire pour transaction_id + value + currency ? (3) Y a-t-il duplication avec gtag direct dans le head ? Réponds étape par étape avec correctifs GTM.' },
  ]),
  ...conseilsSenior([
    'Un audit qui liste 30 problèmes ne sert à rien. Sélectionne les 5 à impact 80/20.',
    'Toujours faire l\'audit AVANT d\'accepter le mandat. Ça montre le sérieux et cadre les attentes.',
    'Photo initiale du compte = capture d\'écran de toutes les métriques 90j — indispensable pour prouver l\'amélioration ensuite.',
    'Ne juge jamais un compte sur 30 jours. Minimum 90 jours pour absorber saisonnalité + weekends.',
  ]),
  ...validationFinale('Le client a vu et validé le rapport. Le plan d\'action prioritaire est acté par écrit.', 'Fichier « Audit_[Client]_[YYYY-MM-DD].md » archivé dans Projet → Documentation'),
  ...escalade('Compte suspendu ou policy strike en cours', 'Chef de projet + Google Ads Support via Projet → Discussion (Alerte)'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_KEYWORDS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Sélectionner 20-50 mots-clés à forte intention transactionnelle, budget-cohérents, qui rentabiliseront un ROAS cible',
    resultat: 'Fichier keywords structuré par thème + match type + landing page assignée + volume + CPC estimé.',
    delai: '2-3 h pour un secteur, 1 journée pour un e-commerce large',
    canal: CANAL,
    regle: 'JAMAIS lancer une campagne avec des mots-clés Broad Match par défaut. Toujours Phrase ou Exact au démarrage.',
    prerequis: ['Fiche projet à jour (secteur, zone géo, budget)', 'Accès Keyword Planner (compte Ads actif)'],
  }),
  ...projectContext(['client.name', 'domain', 'project.budget']),
  h2('Étapes'),
  ...etape('1. BRAINSTORM SEED + INTENTION', {
    objectif: 'Lister 30-50 mots-clés seed classés par intention (transactionnelle / informative / navigation)',
    temps: '30 min',
    ou: 'Projet → Documentation + Keyword Planner',
    actions: [
      'Ouvre la fiche projet → note les 3 catégories produits/services principaux',
      'Pour chaque catégorie, écris 5 formulations client (« acheter X », « prix X », « X à [ville] »)',
      'Ajoute variations naturelles : synonymes, misspellings courants, formes verbales',
      'Marque chaque mot-clé : 🔥 transactionnel · 💡 informatif · 🧭 navigation',
      'Ne garde que le 🔥 pour la campagne Search initiale',
    ],
    resultat: 'Liste 30-50 mots-clés seed catégorisés par intention.',
    verification: ['≥ 20 mots-clés transactionnels', 'Zone géo incluse dans au moins 5 mots-clés locaux', 'Pas de mots-clés > 3 termes (à ce stade)'],
    erreurs: [
      ['Inclure des mots-clés informatifs en Search', 'Coûteux + peu convertit. Réserve-les au Display ou blog SEO.'],
      ['Copier-coller la liste concurrents', 'Tu paies l\'apprentissage de Google au lieu de le tester chez toi.'],
    ],
    conseil: 'Les mots-clés qui commencent par « prix », « tarif », « acheter » ou incluent « près de moi » convertissent 3-5× mieux que le reste.',
  }),
  ...etape('2. KEYWORD PLANNER + VOLUME/CPC', {
    objectif: 'Enrichir la seed list avec Keyword Planner : volume, CPC low/high, concurrence',
    temps: '45 min',
    ou: 'Google Ads → Outils → Keyword Planner → Trouver de nouveaux mots-clés',
    actions: [
      'Colle ta seed list dans « Découvrez de nouveaux mots-clés » → langue française + zone géo projet',
      'Exporte le CSV complet (Télécharger les idées de mots-clés → CSV)',
      'Ouvre le CSV → colonnes clés : Terme, Volume mensuel, Concurrence, Enchère haute/basse',
      'Filtre : volume ≥ 100/mois ET CPC max < (budget_mois / 300 clics_minimum)',
      'Garde les mots-clés qui passent → ~50 restants',
    ],
    resultat: 'CSV filtré ~50 mots-clés viables budget-cohérents.',
    verification: ['Chaque mot-clé a volume + CPC visible', 'Filtre budget appliqué', 'Zone géo correcte'],
    erreurs: [
      ['Ignorer les mots-clés faible volume < 100', 'Souvent les plus rentables (longue traîne, faible concurrence).'],
      ['CPC pris pour argent comptant', 'Enchère haute est un plafond, pas le vrai CPC payé. Comptez × 0.7 en moyenne.'],
    ],
    conseil: 'Le volume mensuel Google Ads est arrondi (10, 100, 1k, 10k). Un « 100 » peut être 50 comme 400. Croise avec Semrush si possible.',
  }),
  ...etape('3. MAPPING MOTS-CLÉS ↔ LANDING ↔ MATCH TYPE', {
    objectif: 'Décider où chaque mot-clé mène + comment il matche → fondation des Ad Groups',
    temps: '45 min',
    ou: 'Tableur (feuille dans Projet → Documentation)',
    actions: [
      'Colonnes : Mot-clé | Volume | CPC | Landing URL | Match Type | Ad Group',
      'Landing URL : URL exacte de la page qui répond au mot-clé (pas la home !)',
      'Match Type : Exact [keyword] pour top-perf + Phrase "keyword" pour discovery. Éviter Broad au démarrage.',
      'Regroupe par intention proche → 1 Ad Group = 5-15 mots-clés SIMILAIRES',
      'Nomme les Ad Groups par intention : « [Produit A] - Transactionnel », « [Produit A] - Comparatif »',
    ],
    resultat: 'Mapping complet prêt à importer dans Ads Editor.',
    verification: ['Chaque mot-clé a une landing URL spécifique', 'Aucun Ad Group > 20 mots-clés', 'Aucun match type Broad'],
    erreurs: [
      ['Une seule landing pour tout', 'Quality Score effondré. Landing doit contenir le mot-clé dans title + H1.'],
      ['Ad Group géant (30+ keywords)', 'Impossible d\'optimiser annonces. Splitter par intention.'],
    ],
    conseil: 'Règle STAG (Single Theme Ad Group) : chaque Ad Group = 1 thème sémantique clair. 5-10 mots-clés, jamais plus.',
  }),
  ...finalCheck([
    'Fichier mapping complet dans Projet → Documentation',
    'Chaque mot-clé a landing URL + match type + Ad Group',
    'Aucun match type Broad',
    'Budget vs CPC vérifié (min 300 clics/mois par campagne)',
    'Volume total ≥ 500 recherches/mois (sinon élargir seed)',
  ]),
  ...qaCheck([
    'Les mots-clés informatifs sont-ils exclus de la campagne Search ?',
    'Chaque Ad Group est-il un thème unique (STAG) ?',
    'Les landing pages contiennent-elles le mot-clé dans title + H1 ?',
    'Le mapping est-il exportable directement dans Ads Editor ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Filtre keywords par intention transactionnelle',
      prompt: 'Voici un CSV Keyword Planner de 200 mots-clés (colle). Le client vend [PRODUIT/SERVICE] avec un budget [MAD]/mois. Filtre uniquement les mots-clés qui remplissent LES 4 conditions : (1) intention transactionnelle (verbe d\'achat, prix, tarif, near me), (2) CPC < BUDGET/300, (3) volume ≥ 100, (4) concurrence faible/moyenne. Sortie : tableau Markdown | Mot-clé | Volume | CPC | Match Type recommandé (Exact/Phrase) | Raison |, trié par (Volume × pertinence / CPC).' },
    { agent: 'Claude Code', title: 'Génère import Ads Editor CSV',
      prompt: 'Voici mon mapping mots-clés (colle CSV). Produis le fichier CSV au format exact Google Ads Editor pour import : colonnes obligatoires « Campaign | Ad Group | Keyword | Match Type | Max CPC | Final URL ». Applique règles : Max CPC = 0.7 × Enchère haute du Planner, Match Type = Exact si volume > 500 sinon Phrase, Final URL = celle donnée dans mon mapping. Format CSV strict séparateur virgule.' },
  ]),
  ...conseilsSenior([
    'STAG > SKAG : un Ad Group thématique bat 1 mot-clé par Ad Group (obsolète depuis close variants Broad).',
    'Ne mets JAMAIS un mot-clé avec CPC > 2% du budget mensuel — un seul clic peut griller la campagne.',
    'La longue traîne (4+ mots) convertit 5-10× mieux mais volume divisé par 20. Priorité tête de traîne pour volume, longue traîne pour rentabilité.',
    'Réutilise les termes de recherche des 90 derniers jours du client (ou concurrents via Semrush) — trésor caché.',
  ]),
  ...validationFinale('Mapping validé par le client (mots-clés + landings). Import Ads Editor prêt.', 'Fichier CSV « Keywords_[Client].csv » dans Projet → Documentation'),
  ...escalade('Aucun mot-clé viable trouvé (budget trop faible)', 'Chef de projet — revoir stratégie Display/Social plutôt que Search'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_BUDGET: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Cadrer un budget mensuel réaliste + choisir la stratégie d\'enchère qui correspond au niveau de conversions',
    resultat: 'Feuille de calcul : budget/jour × campagne + stratégie d\'enchère justifiée + CPA cible chiffré.',
    delai: '1 h de réflexion + 30 min avec le client pour validation',
    canal: CANAL,
    regle: 'JAMAIS activer tCPA ou tROAS avant 30 conversions/mois. Reste en Manual CPC ou Max Conversions.',
    prerequis: ['Historique GA4 3+ mois (ou benchmark secteur)', 'CPA/AOV/marge du client connus'],
  }),
  ...projectContext(['client.name', 'project.budget', 'client.company']),
  h2('Étapes'),
  ...etape('1. MODÉLISATION BUDGET SELON CPA CIBLE', {
    objectif: 'Calculer le budget minimum viable à partir du CPA cible et du volume attendu',
    temps: '30 min',
    ou: 'Tableur dans Projet → Documentation',
    actions: [
      'Demande au client : AOV (panier moyen), marge nette %, CPA acceptable',
      'Si CPA acceptable non connu → CPA max = AOV × marge% × 0.5 (règle mi-marge)',
      'Estime volume clics nécessaires : leads_visés × (1 / taux_conversion) — si tx conv inconnu, prendre 2%',
      'Budget minimum = clics × CPC moyen (issu du mapping keywords)',
      'Applique règle : budget < 300 clics/mois = pas assez de données pour optimiser',
    ],
    resultat: 'Budget mensuel chiffré + justification.',
    verification: ['CPA max calculé', 'Volume clics estimé', 'Budget minimum satisfait (≥ 300 clics)'],
    erreurs: [
      ['Budget accepté « bas prix »', 'En dessous de 300 clics/mois, impossible d\'optimiser statistiquement. Refuse ou passe en Google Business + SEO.'],
      ['CPA cible fixé au CPA actuel', 'Google Ads démarre plus cher (learning). Prends CPA × 1.5 pendant 30 jours puis on optimise.'],
    ],
    conseil: 'Vise pas la rentabilité au mois 1. Vise l\'apprentissage. La rentabilité arrive au mois 3.',
  }),
  ...etape('2. SPLIT PAR CAMPAGNE ET PLAFOND JOURNALIER', {
    objectif: 'Ventiler le budget par campagne selon priorité + éviter le crash journalier',
    temps: '20 min',
    ou: 'Tableur',
    actions: [
      'Priorité 1 : Search branded (mots-clés marque) — 10-15% du budget',
      'Priorité 2 : Search transactionnel top produits — 50-60%',
      'Priorité 3 : Search longue traîne / discovery — 15-20%',
      'Priorité 4 : Remarketing Display ou Video — 10-15%',
      'Budget journalier = budget_mensuel / 30.4 (jamais /30 arrondi)',
    ],
    resultat: 'Split validé + budget journalier par campagne.',
    verification: ['Somme des splits = 100%', 'Budget journalier > CPC max × 5 (marge sécurité)', 'Branded présent'],
    erreurs: [
      ['Oublier le Branded', 'Concurrents surenchèrent sur ta marque. 100 MAD/mois économise des CAC ×10.'],
      ['Budget journalier = budget/30', 'Sur un mois de 31 jours, dépasse le budget mensuel. Utilise /30.4.'],
    ],
    conseil: 'Google peut dépenser jusqu\'à 2× le daily budget certains jours (compensé sur le mois). Réserve une marge dans le compte.',
  }),
  ...etape('3. CHOIX STRATÉGIE D\'ENCHÈRE', {
    objectif: 'Choisir la stratégie qui correspond au volume de conversions historique',
    temps: '15 min',
    ou: 'Google Ads → Nouvelle campagne → Enchères',
    actions: [
      '< 15 conv/mois → Manual CPC ou Max Clicks (récolter données)',
      '15-30 conv/mois → Maximize Conversions (sans tCPA)',
      '30-100 conv/mois → tCPA (Target CPA) avec CPA = CPA_moyen_actuel',
      '> 100 conv/mois + tracking valeur → tROAS avec ROAS = marge / AOV',
      'Note le choix + justification dans Projet → Documentation',
    ],
    resultat: 'Stratégie d\'enchère sélectionnée + rationale documenté.',
    verification: ['Volume conv vérifié 30 derniers jours', 'tCPA justifié par historique OU passé', 'ROAS matche marge cible'],
    erreurs: [
      ['tROAS activé sans 30 conv/mois', 'Google n\'a pas de données → délivrance chaotique. Reste sur Maximize Conv.'],
      ['tCPA = objectif rêvé (trop bas)', 'Google coupe la diffusion. tCPA doit être au CPA actuel × 0.9, pas -50%.'],
    ],
    conseil: 'Les stratégies auto ont besoin de 30 conv MINIMUM sur 30 jours pour sortir du learning. Sinon, tu paies pour Google apprendre.',
  }),
  ...finalCheck([
    'Budget mensuel chiffré et justifié',
    'CPA max défini et documenté',
    'Split budget par campagne (branded / transactionnel / longue traîne / remarketing)',
    'Budget journalier calculé avec /30.4',
    'Stratégie d\'enchère cohérente avec volume conv',
    'Client a signé la proposition budgétaire',
  ]),
  ...qaCheck([
    'Le budget minimum viable (300 clics/mois) est-il respecté ?',
    'La stratégie d\'enchère correspond-elle à l\'historique conv ?',
    'Le Branded est-il séparé du reste ?',
    'Le CPA cible est-il × 1.5 pour absorber le learning ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Calcule budget Google Ads à partir du secteur',
      prompt: 'Tu es Senior SEA. Le client vend [PRODUIT] à un AOV [MAD] avec marge [%]. Il veut [NB] leads/mois. Estime : (1) CPA max viable (mi-marge), (2) taux de conv secteur, (3) CPC moyen secteur au Maroc si tu connais, sinon indique benchmark international × 0.5, (4) Budget minimum viable, (5) Budget optimal 3× minimum. Sortie : bloc chiffres avec justif de chaque calcul.' },
  ]),
  ...conseilsSenior([
    'Vends au client une phase de « ramp-up » de 30 jours à budget × 1.3 → apprentissage.',
    'Ne parle jamais de « ROI Google Ads » mais de « CPA / ROAS ». Le ROI dépend de la LTV que tu ne contrôles pas.',
    'Ajoute toujours 15% de marge sur le budget accepté par le client — Google dépasse parfois, tu en as besoin.',
    'Branded protège toujours ta marque. Même à 200 MAD/mois, ça vaut le coup.',
  ]),
  ...validationFinale('Le client a signé le brief budgétaire + KPIs cibles. Le split par campagne est validé.', 'Fichier « Budget_[Client]_[YYYY-MM-DD].md » dans Projet → Documentation'),
  ...escalade('Client refuse budget minimum viable', 'Chef de projet → basculer sur SEO local + Google Business'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_ACCESS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Obtenir les accès Google Ads du client (MCC ou compte direct) sans compromettre la sécurité',
    resultat: 'Compte Google Ads lié au MCC agence + accès admin conservé pour le client + trace écrite.',
    delai: '15-30 min',
    canal: CANAL,
    regle: 'JAMAIS demander le mot de passe Google du client. Toujours via demande d\'accès MCC.',
    prerequis: ['MCC agence configuré', 'Email admin du client sur son compte Google Ads'],
  }),
  ...projectContext(['client.name', 'client.email']),
  h2('Étapes'),
  ...etape('1. IDENTIFIER LE COMPTE EXISTANT (OU EN CRÉER UN)', {
    objectif: 'Savoir si le client a déjà un compte Ads ou s\'il faut en créer un neuf',
    temps: '10 min',
    ou: 'Demande au client dans Projet → Discussion',
    actions: [
      'Demande au client : « as-tu déjà un compte Google Ads ? Si oui, envoie-moi l\'ID (10 chiffres, format XXX-XXX-XXXX) »',
      'Note l\'ID dans Projet → Infos & Accès → « Google Ads Customer ID »',
      'Si non → il faudra créer le compte via ads.google.com avec l\'email de contact business du client',
      'Si oui mais suspendu → NE PAS activer un nouveau compte, résoudre la suspension d\'abord',
    ],
    resultat: 'ID compte connu + statut (actif / suspendu / à créer).',
    verification: ['Customer ID au format correct', 'Statut du compte vérifié'],
    erreurs: [
      ['Créer un 2e compte à côté du 1er', 'Google détecte doublon → suspend les deux. Toujours résoudre le premier.'],
      ['Utiliser email perso du client', 'Si le client part, tu perds le compte. Toujours email business type ads@[client].ma.'],
    ],
    conseil: 'Fais créer par le client sa propre agence sur son compte — tu es prestataire, pas propriétaire.',
  }),
  ...etape('2. ENVOYER DEMANDE D\'ACCÈS MCC', {
    objectif: 'Lier le compte client au MCC agence en mode Admin (pas Standard)',
    temps: '5 min',
    ou: 'MCC agence → Accounts → + Add Account → Link existing account',
    actions: [
      'Ouvre le MCC agence → Comptes → + Ajouter un compte → Lier un compte existant',
      'Colle le Customer ID du client (XXX-XXX-XXXX)',
      'Niveau d\'accès : Admin (pour gérer factures + campaigns + billing)',
      'Envoie la demande — un email arrive au propriétaire du compte client',
      'Message dans Projet → Discussion au client : « Reçu un email de Google Ads Manager ? Clique “Accepter” »',
    ],
    resultat: 'Demande envoyée, client informé.',
    verification: ['MCC → Comptes → nouveau compte affiché « Pending »', 'Client a reçu email Google'],
    erreurs: [
      ['Client ne reçoit pas l\'email', 'Vérifie l\'adresse propriétaire du compte, pas juste l\'admin. Souvent ancienne adresse gmail perso.'],
      ['Accès Standard au lieu d\'Admin', 'Tu ne pourras pas modifier billing. Redemande niveau Admin.'],
    ],
    conseil: 'Rassure le client sur le sens : accepter ne donne PAS accès à ses données Gmail/Drive — uniquement à Ads.',
  }),
  ...etape('3. VÉRIFICATION ET DOCUMENTATION', {
    objectif: 'Confirmer que l\'accès fonctionne + tracer dans Infos & Accès',
    temps: '5 min',
    ou: 'MCC agence + Projet → Infos & Accès',
    actions: [
      'MCC → clique sur le compte client → doit ouvrir son interface Ads',
      'Vérifie que tu vois les campagnes, factures, historique',
      'Note dans Projet → Infos & Accès : ID Ads + email propriétaire + date de liaison + niveau accès',
      'Enregistre dans Projet → Documentation le screenshot du MCC avec le compte lié',
    ],
    resultat: 'Accès fonctionnel + tracé.',
    verification: ['Ouverture compte OK', 'Traces dans Infos & Accès + Documentation'],
    conseil: 'Si le compte est neuf, active dès maintenant Consent Mode v2 dans les paramètres avant même la 1re campagne.',
  }),
  ...finalCheck([
    'Customer ID enregistré dans Projet → Infos & Accès',
    'Compte lié au MCC en niveau Admin',
    'Client a accepté la demande',
    'Test d\'ouverture du compte réussi',
    'Screenshot MCC dans Projet → Documentation',
  ]),
  ...qaCheck([
    'Le niveau d\'accès est-il Admin (pas Standard) ?',
    'Le propriétaire du compte est-il le business client (pas ton agence) ?',
    'Les infos sont-elles dans Projet → Infos & Accès ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige email demande accès pour client',
      prompt: 'Rédige un email court (max 8 lignes) au client [NOM] pour lui demander l\'ID de son compte Google Ads. Explique en 2 phrases pourquoi (setup MCC agence), rassure sur la sécurité (aucun accès Gmail/Drive), et donne le chemin exact pour trouver l\'ID (ads.google.com → coin haut droit). Ton : professionnel et rassurant.' },
  ]),
  ...conseilsSenior([
    'Ne jamais accepter que ton agence soit propriétaire du compte client. Tu es prestataire, pas propriétaire.',
    'Documenter chaque accès dans Infos & Accès = quand tu perds un compte, tu retrouves.',
    'Toujours niveau Admin. Standard te bloque sur billing et user management.',
    'Fais lier au moins 2 emails admin côté client (le sien + un autre du bureau) — sinon départ = accès perdu.',
  ]),
  ...validationFinale('Compte Ads du client lié au MCC agence en Admin. Accès testé. Trace dans Infos & Accès.', 'Ligne « Google Ads » dans Projet → Infos & Accès'),
  ...escalade('Client refuse d\'accepter la demande MCC', 'Chef de projet — souvent malentendu sur sécurité, à ré-expliquer'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_TRACKING: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Installer un tracking de conversions Google Ads fiable et attribué correctement à chaque campagne',
    resultat: 'Conversions actives dans Google Ads, cohérentes avec GA4 (± 5%), Enhanced Conversions + Consent Mode v2 déployés.',
    delai: '2-3 h pour un site simple, 1 journée pour e-commerce',
    canal: CANAL,
    regle: 'JAMAIS lancer une campagne sans conversion tracking validée. Sans conversion = sans optimisation.',
    prerequis: ['GTM installé sur le site', 'Accès admin GA4', 'Accès Google Ads Admin'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. DÉFINIR LES CONVERSIONS À TRACER', {
    objectif: 'Lister les 3-5 conversions principales + leur valeur monétaire',
    temps: '30 min',
    ou: 'Projet → Documentation → « Objectifs conversion »',
    actions: [
      'Réunion 15 min avec client : quel événement client final = « success » ?',
      'Liste primaires (1-3) : Achat, Lead form envoyé, Demande devis, Réservation',
      'Liste secondaires (2-4) : Contact WhatsApp, Appel téléphonique, Newsletter, Ajout panier',
      'Attribue valeur monétaire à chaque : Achat = valeur commande, Lead = AOV × taux_conv_lead_to_sale',
      'Note dans Projet → Documentation : nom_conv | primary/secondary | valeur | trigger (URL merci / event GTM)',
    ],
    resultat: 'Liste complète conversions + valeur + trigger identifiés.',
    verification: ['≥ 1 conversion primaire', 'Valeur monétaire attribuée', 'Trigger technique identifié'],
    erreurs: [
      ['Trop de conversions primaires', 'Google optimise sur toutes → dilution. Max 3 primaires.'],
      ['Pas de valeur monétaire', 'Impossible d\'utiliser tROAS. Toujours estimer une valeur, même approximative.'],
    ],
    conseil: 'Un « appel WhatsApp » est une conversion primaire au Maroc, pas secondaire. 60% des leads B2C passent par là.',
  }),
  ...etape('2. CRÉER LES CONVERSIONS DANS GOOGLE ADS', {
    objectif: 'Enregistrer chaque conversion + son mode d\'attribution',
    temps: '30 min',
    ou: 'Google Ads → Outils → Conversions → + Nouvelle',
    actions: [
      'Google Ads → Outils → Conversions → + Nouvelle conversion',
      'Source : Site web (majorité) OU Import (offline conversions Salesforce/HubSpot)',
      'Catégorie : correspond au type (Achat / Lead / Contact)',
      'Valeur : Utiliser des valeurs différentes par conversion → colle valeur estimée',
      'Comptage : « Une seule » (Lead / Contact) ou « Toutes » (Achat/Vente)',
      'Fenêtre de conversion : 30 jours clic + 1 jour vue (défaut ok)',
      'Attribution : Data-driven (défaut recommandé)',
      'Enhanced Conversions : Activer (via balise gtag OU manuel)',
    ],
    resultat: 'Conversions créées + configurées.',
    verification: ['Chaque conversion listée statut « Aucune conversion récente » (normal avant tag)', 'Enhanced Conversions ON', 'Data-driven attribution ON'],
    erreurs: [
      ['Attribution Last Click', 'Perd 20-40% de crédit sur Search + PMax. Data-driven quasi obligatoire depuis 2023.'],
      ['Comptage « Toutes » sur un Lead form', 'Compte plusieurs soumissions du même user. Utilise « Une seule ».'],
    ],
    conseil: 'Enhanced Conversions donne +5-15% de conversions observables (récupère les données bloquées par iOS 14+ / cookies).',
  }),
  ...etape('3. DÉPLOYER TAGS GTM + TESTER', {
    objectif: 'Poser le tag Google Ads Conversion Tracking sur les bons triggers + valider en preview',
    temps: '1-2 h selon nb tags',
    ou: 'Google Tag Manager → Balises',
    actions: [
      'GTM → Balises → + Nouvelle → Google Ads Conversion Tracking',
      'Renseigne Conversion ID + Conversion Label (récupérés dans Google Ads → Conversion → Balise)',
      'Ajoute paramètres value + transaction_id + currency (obligatoires pour e-com)',
      'Trigger : événement custom « purchase », OU URL merci contains /thank-you',
      'GTM → Preview → simule un achat/lead sur le site → vérifie que le tag fire (green) 1 seule fois',
      'GTM → Publish → note version dans commentaire',
      'Test réel : effectue 1 conversion depuis un clic Google Ads → vérifie dans Google Ads → Conversions dans les 3h',
    ],
    resultat: 'Tags actifs, conversion test remontée.',
    verification: ['Tag fire une fois seulement en preview', 'Google Ads affiche « conversions récentes »', 'Cohérence GA4'],
    erreurs: [
      ['Tag fire 2x (duplication)', 'Conversion label posée aussi dans gtag direct + GTM. Supprimer l\'un.'],
      ['Transaction ID identique pour tous', 'Google dédoublonne → conversions perdues. Utiliser dataLayer.transaction_id unique.'],
    ],
    conseil: 'Toujours tester en réel après GTM Publish. Preview ≠ prod, il y a parfois divergences (cookie sync, referrer).',
  }),
  ...etape('4. CONSENT MODE V2 + ENHANCED CONVERSIONS', {
    objectif: 'Rendre le tracking conforme RGPD tout en préservant la performance',
    temps: '45 min',
    ou: 'CMP (Axeptio/Didomi/Cookiebot) + GTM',
    actions: [
      'Installe un CMP (Consent Management Platform) : Axeptio ou Cookiebot',
      'Configure Consent Mode v2 : ad_storage, ad_user_data, ad_personalization',
      'GTM → paramètre « Consent Overview » → chaque tag reçoit les signaux',
      'Google Ads → Outils → Enhanced Conversions → Configure via balise ou API',
      'Vérifie dans Ads → Diagnostic conversions que les 2 sont « OK »',
    ],
    resultat: 'Compliance RGPD + tracking optimisé.',
    verification: ['Consent Mode v2 status vert', 'Enhanced Conversions status vert', 'CMP visible sur homepage'],
    erreurs: [
      ['Enhanced Conversions off (défaut)', 'Perte 5-15% observabilité. Toujours activer.'],
      ['Consent Mode v1 (obsolète)', 'Non-compliant depuis mars 2024. Migrer v2 immédiatement.'],
    ],
    conseil: 'Cookiebot > Axeptio pour la conformité juridique fine, Axeptio > Cookiebot pour l\'UX. Choisis selon contexte.',
  }),
  ...finalCheck([
    'Toutes conversions créées et configurées',
    'Tags GTM déployés et publiés',
    'Test réel : conversion tracée dans Google Ads',
    'Data-driven attribution activée',
    'Enhanced Conversions ON',
    'Consent Mode v2 déployé',
    'Écart Ads vs GA4 < 5%',
  ]),
  ...qaCheck([
    'Y a-t-il duplication de tags entre gtag et GTM ?',
    'Chaque transaction_id est-il unique ?',
    'La valeur monétaire est-elle bien envoyée ?',
    'Le CMP est-il présent sur toutes les pages ?',
  ]),
  ...promptCards([
    { agent: 'Claude Code', title: 'Debug tag Google Ads dans GTM',
      prompt: 'Voici mon container GTM (export JSON) : [COLLE]. Le tag « GAds - Purchase » configuré pour trigger « custom event = purchase » ne fire pas. Analyse : (1) le trigger match-t-il l\'event émis par le dataLayer ? (2) les variables value / currency / transaction_id sont-elles présentes ? (3) Consent Mode v2 bloque-t-il ? Réponds pas-à-pas avec correctifs.' },
    { agent: 'ChatGPT', title: 'Calcule valeur conversion pour un Lead',
      prompt: 'Le client est [SECTEUR]. Son AOV moyen est [MAD]. Son taux de conversion Lead → Vente est [%]. Estime la valeur monétaire à attribuer à un Lead pour Google Ads Value-based bidding. Sortie : formule + résultat en MAD + explication en 2 phrases.' },
  ]),
  ...conseilsSenior([
    'La règle absolue : tracking d\'abord, ads ensuite. Une campagne sans conv = 0 optimisation.',
    'Data-driven attribution nécessite historique conv 300+/mois. Sinon fallback last-click auto.',
    'Enhanced Conversions dérisque le futur cookieless — active-le même si tu ne comprends pas tout de suite.',
    'Vérifie l\'écart Ads/GA4 chaque mois. Si > 15%, c\'est un signal fort (déduplication, attribution, consent).',
  ]),
  ...validationFinale('Toutes les conversions traquées, testées, cohérentes GA4. Enhanced Conv + Consent v2 déployés.', 'Section « Tracking » dans Projet → Documentation avec screenshots Ads Diagnostic'),
  ...escalade('Écart Ads vs GA4 > 20% persistant après debug', 'Chef de projet + support GTM/GA4 via Projet → Discussion (Alerte)'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_AUDIENCES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer les segments d\'audiences qui alimentent le remarketing, Similar Audiences, exclusions',
    resultat: 'Bibliothèque d\'audiences propres, taille cohérente, utilisées dans les campagnes Search/PMax/Display.',
    delai: '1-2 h pour setup initial',
    canal: CANAL,
    regle: 'Ne JAMAIS créer une audience < 1000 utilisateurs — trop petite pour être utilisable Google Ads.',
    prerequis: ['GA4 lié à Google Ads', 'Balise Google Ads sur le site', 'Historique 30j+ de visites'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. AUDIENCES REMARKETING FONDAMENTALES', {
    objectif: 'Créer les 5 audiences remarketing de base',
    temps: '30 min',
    ou: 'Google Ads → Outils → Bibliothèque partagée → Gestionnaire d\'audience',
    actions: [
      'Visiteurs 30 jours (toutes URLs) → base retargeting large',
      'Visiteurs pages produit sans achat (URL contains /product ET NOT /thank-you) → chaud',
      'Visiteurs qui ont ajouté au panier sans acheter → très chaud',
      'Anciens acheteurs 90-180j → cross-sell / upsell',
      'Visiteurs bounce (session < 10s) → à exclure des enchères',
    ],
    resultat: '5 audiences remarketing créées.',
    verification: ['Chaque audience > 1000 users ou marquée « too small »', 'Fenêtres cohérentes (30j chaud, 90j moyen, 180j froid)', 'Audience bounce disponible pour exclusion'],
    erreurs: [
      ['Toutes audiences 540 jours par défaut', 'Trop large → dilution. Segmenter par 30j/90j/180j.'],
      ['Créer 20 audiences niches', 'Impossible à gérer. Focus sur 5-8 max.'],
    ],
    conseil: 'L\'audience « visiteur du panier sans achat » a un ROAS 3-5× supérieur au broad remarketing. Priorité absolue.',
  }),
  ...etape('2. LOOKALIKE / SIMILAR AUDIENCES', {
    objectif: 'Étendre l\'audience via ressemblance aux meilleurs clients',
    temps: '20 min',
    ou: 'Google Ads → Audiences → + Nouveau segment personnalisé',
    actions: [
      'Note : Similar Audiences officiellement supprimées mai 2023 → utiliser Optimized Targeting + Audience Signals dans PMax',
      'Créer segments d\'audience personnalisée basés sur : intentions (Custom Intent) OU affinités (Custom Affinity)',
      'Custom Intent : liste mots-clés que ta cible tape + URLs concurrents visités',
      'Utiliser ces audiences comme Audience Signals dans PMax (pas de ciblage strict, juste signal)',
      'Importer les audiences clients depuis GA4 (Advertising Audiences) → sync vers Ads (activer sync explicite)',
    ],
    resultat: 'Audiences personnalisées prêtes + GA4 audiences importées.',
    verification: ['GA4 → Ads link → audiences synced OK', 'Custom Intent créé avec 10-20 seed keywords'],
    erreurs: [
      ['Chercher « Similar Audience » dans l\'UI', 'N\'existe plus. Migrer vers Optimized Targeting + Signals PMax.'],
      ['GA4 audiences pas syncées vers Ads', 'Bouton « Ads » à activer dans GA4 Audience settings. Sinon invisibles.'],
    ],
    conseil: 'Depuis la fin des Similar Audiences, Custom Intent + Signals PMax deviennent LA façon d\'alimenter l\'IA Google.',
  }),
  ...etape('3. LISTES DE CLIENTS + EXCLUSIONS', {
    objectif: 'Charger le CRM du client + créer les exclusions négatives',
    temps: '30 min',
    ou: 'Customer Match Uploader + Bibliothèque audience',
    actions: [
      'Récupère CSV clients depuis CRM (email + téléphone hashés SHA-256)',
      'Google Ads → Outils → Audience Manager → Segments → + Customer List',
      'Upload CSV → attends 24-72h match',
      'Crée une audience « Clients existants » → utilise pour EXCLUSION campagnes acquisition',
      'Crée exclusions : visiteurs employés (IP filter GA4), bounce, non-target',
    ],
    resultat: 'CRM chargé + exclusions actives.',
    verification: ['Match rate Customer List > 40% (sinon problème format)', 'Exclusions appliquées aux campagnes acquisition'],
    erreurs: [
      ['Upload sans hash SHA-256', 'Google rejette pour non-conformité RGPD. Toujours hasher client-side.'],
      ['Ne pas exclure clients existants des campagnes acquisition', 'Tu paies pour convertir des clients déjà acquis. Toujours exclure.'],
    ],
    conseil: 'Customer Match Rate < 30% = données CRM sales/dirty. C\'est le moment de faire le ménage.',
  }),
  ...finalCheck([
    '5 audiences remarketing créées',
    'Audience bounce disponible pour exclusion',
    'Custom Intent créés (min 2)',
    'GA4 audiences syncées vers Ads',
    'Customer List uploadée (match > 40%)',
    'Exclusions clients existants appliquées aux campagnes acquisition',
  ]),
  ...qaCheck([
    'Toutes les audiences ont-elles une taille > 1000 ?',
    'Le remarketing panier est-il isolé (RM très chaud) ?',
    'Les clients existants sont-ils exclus des campagnes prospection ?',
    'Enhanced Conversions active-t-il l\'usage des Customer List ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 20 seed keywords pour Custom Intent',
      prompt: 'Le client vend [PRODUIT] à une cible [PROFIL]. Génère 20 requêtes Google que cette cible tape juste avant d\'acheter (intent commercial). Format : liste numérotée. Puis 5 URLs de concurrents à ajouter comme signaux pour Custom Intent. Justif rapide pour chaque.' },
  ]),
  ...conseilsSenior([
    'Le remarketing panier est l\'audience la plus rentable de Google Ads. Toujours créer + budget dédié.',
    'Une exclusion vaut souvent plus qu\'une audience. Exclure les acheteurs des campagnes acquisition = +30% ROAS.',
    'Customer Match rate < 30% = problème de qualité CRM. Fix ça avant de scaler.',
    'Depuis fin des Similar Audiences, tout passe par Custom Intent + Signals PMax. Apprends-les à fond.',
  ]),
  ...validationFinale('Bibliothèque audiences complète, remarketing + exclusions actives.', 'Section « Audiences » dans Projet → Documentation'),
  ...escalade('Customer Match rate < 20%', 'Chef de projet — audit qualité CRM à programmer'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_EXTENSIONS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Activer toutes les extensions d\'annonces pertinentes pour maximiser CTR + Ad Rank',
    resultat: 'Sitelinks, Callouts, Structured Snippets, Call, Location, Price, Promotion, Image extensions actives.',
    delai: '45 min pour setup complet',
    canal: CANAL,
    regle: 'JAMAIS lancer une campagne Search sans au moins 4 extensions actives — Ad Rank chute × 2.',
    prerequis: ['Campaigns Search créées', 'Coordonnées client complètes (téléphone, adresse, promo)'],
  }),
  ...projectContext(['client.name', 'client.phone', 'client.company', 'domain']),
  h2('Étapes'),
  ...etape('1. SITELINKS (4 minimum, 6 idéal)', {
    objectif: 'Ajouter 4-6 sitelinks avec CTAs orientés conversion',
    temps: '15 min',
    ou: 'Google Ads → Annonces et extensions → Extensions → + → Sitelink',
    actions: [
      'Note en amont 6 pages à mettre en avant : Contact, Nos services, Tarifs, Avis clients, À propos, Blog',
      '+ Sitelink → titre 25 char max + description 1 (35 char) + description 2 (35 char) + URL',
      'Utilise des verbes d\'action : « Voir tarifs », « Prendre RDV », « Nos avis »',
      'Ajoute des chiffres si possible : « 500+ clients », « 15 ans d\'expérience »',
      'Ajoute au niveau Campagne (pas Ad Group) sauf sitelinks très spécifiques',
    ],
    resultat: '4-6 sitelinks actifs.',
    verification: ['≥ 4 sitelinks', 'Chaque sitelink a description 1 + 2 (non obligatoire mais boost CTR)', 'URLs cliquent bien'],
    erreurs: [
      ['Sitelinks sans description', 'Rate 30% du CTR bonus. Descriptions toujours remplies.'],
      ['Sitelinks tous ⇒ homepage', 'Perd le sens. Chaque sitelink = page dédiée.'],
    ],
    conseil: 'Sitelinks + descriptions augmentent l\'espace visuel Ad × 2 sur mobile → CTR +15-30%.',
  }),
  ...etape('2. CALLOUTS + STRUCTURED SNIPPETS', {
    objectif: 'Ajouter les callouts (bénéfices) et structured snippets (catégories)',
    temps: '15 min',
    ou: 'Google Ads → Extensions → + → Callout / Structured Snippet',
    actions: [
      'Callouts : 8-10 phrases courtes (25 char max) sans CTA — bénéfices/USPs',
      'Ex : « Livraison 24h », « Devis gratuit », « Garantie 2 ans », « SAV Maroc »',
      'Structured Snippets : header (ex « Services », « Types ») + valeurs (max 10)',
      'Ex : Header « Services » + valeurs « Dev web, Design, SEO, Ads »',
      'Ajouter au niveau compte pour couverture large',
    ],
    resultat: '8+ callouts + 1-2 structured snippets.',
    verification: ['Callouts ≥ 8', 'Structured snippets header + values non redondants avec callouts'],
    erreurs: [
      ['Callouts génériques (« Qualité premium »)', 'Google filtre les callouts génériques. Sois spécifique et chiffré.'],
      ['Duplication callouts / snippets', 'Google en affichera qu\'un. Distingue clairement.'],
    ],
    conseil: 'Callouts = pourquoi choisir, Snippets = quoi tu offres. Pense « pourquoi vs quoi ».',
  }),
  ...etape('3. CALL, LOCATION, PRICE, PROMO', {
    objectif: 'Activer les extensions à fort impact conversion',
    temps: '15 min',
    ou: 'Google Ads → Extensions → + → Call / Location / Price / Promotion',
    actions: [
      'Call extension : ajoute téléphone client (auto-lié conversion Appel si tracking configuré)',
      'Location extension : lie le compte Google Business Profile (essential pour local)',
      'Price extension : min 3 prix (« Consultation 500 MAD », « Setup 3000 MAD »)',
      'Promotion extension : uniquement si promo réelle (dates début/fin, code, réduction %)',
      'Vérifie que chaque extension a horaires si applicable (Call uniquement heures ouvrées)',
    ],
    resultat: 'Extensions high-impact actives.',
    verification: ['Call fonctionne (test appel)', 'Location liée à GBP', 'Price extensions ≥ 3 items', 'Promo dans les dates'],
    erreurs: [
      ['Call extension 24/7 alors qu\'employés 9h-18h', 'Appels perdus la nuit → impression -. Configure horaires.'],
      ['Promo expirée toujours active', 'Google désapprouve après 30 jours. Nettoyer régulièrement.'],
    ],
    conseil: 'Location extension augmente les appels de 20-40% pour un business local. Toujours activer si physique.',
  }),
  ...etape('4. IMAGE EXTENSIONS + LEAD FORM', {
    objectif: 'Ajouter visuel + capture de leads directe',
    temps: '15 min',
    ou: 'Google Ads → Extensions → + → Image / Lead Form',
    actions: [
      'Image extensions : uploader 3-5 images 1200x1200 (produits, équipe, boutique)',
      'Google auto-crop, préfère fonds neutres',
      'Lead Form extension : formulaire natif Ads (nom, email, tel) → capture sans redirection',
      'Configure webhook pour recevoir les leads directement (Zapier / API)',
      'Lead Form Extension utile si taux de conv landing < 2%',
    ],
    resultat: 'Extensions visuelles + capture directes.',
    verification: ['3+ images uploadées', 'Lead Form testé (soumission → réception mail)'],
    conseil: 'Lead Form Extension convertit 2-3× mieux que landing mobile pour les leads simples (rappel, devis).',
  }),
  ...finalCheck([
    '≥ 4 sitelinks avec descriptions',
    '≥ 8 callouts',
    '1-2 structured snippets',
    'Call extension avec horaires',
    'Location liée GBP (si local)',
    'Price extensions si applicable',
    '3+ image extensions',
  ]),
  ...qaCheck([
    'Toutes extensions ont-elles statut « Approuvée » ?',
    'Les URLs sitelinks cliquent-elles bien ?',
    'Call horaires cohérents avec activité ?',
    'Promo dans les dates valides ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 10 callouts pour un secteur',
      prompt: 'Génère 10 callouts Google Ads pour un business [SECTEUR] au Maroc. Contraintes : 25 chars max chacun, sans CTA (pas « Appelez »), bénéfice concret et chiffré si possible (années, garantie, délai). Sortie : liste numérotée + longueur en chars entre parenthèses.' },
  ]),
  ...conseilsSenior([
    'Sans extensions, ton annonce prend 1/3 de l\'espace des concurrents mobiles → CTR effondré.',
    'Location + Call sont les 2 extensions qui bougent le plus le business local. Toujours en priorité.',
    'Lead Form Extension = win pour les métiers où le prospect ne veut pas de landing longue (rappel devis).',
    'Refresh les callouts tous les 3 mois pour éviter fatigue Ad Strength.',
  ]),
  ...validationFinale('Compte a Ad Strength « Excellent » ou « Good » sur toutes campagnes grâce aux extensions.', 'Screenshot Extensions dans Projet → Documentation'),
  ...escalade('Extensions désapprouvées répétées', 'Chef de projet — check policy et re-formuler'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_AD_GROUPS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Structurer les Ad Groups en thèmes uniques (STAG) alignés avec landings',
    resultat: '1 campagne = 3-8 Ad Groups thématiques, chacun avec 5-15 keywords + 3 RSA + landings dédiées.',
    delai: '1-2 h pour structurer + créer',
    canal: CANAL,
    regle: 'JAMAIS mixer keywords de thèmes différents dans un Ad Group. Quality Score s\'effondre.',
    prerequis: ['Mapping keywords fait (SOP précédent)', 'Landings dédiées existantes'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. GROUPER LES KEYWORDS PAR THÈME (STAG)', {
    objectif: 'Regrouper 5-15 keywords sémantiquement proches par Ad Group',
    temps: '30 min',
    ou: 'Tableur mapping',
    actions: [
      'Reprends le mapping keywords → colonne « Ad Group »',
      'Règle STAG : chaque Ad Group = 1 thème unique (ex « Devis Toiture », « Réparation Toiture »)',
      '5 keywords minimum (moins = pas assez de volume), 15 max (plus = perte pertinence)',
      'Chaque Ad Group aura sa propre landing + ses propres RSAs (annonces)',
      'Nommer clairement : « [Produit] - [Intention] - [Match Type] »',
    ],
    resultat: 'Ad Groups définis 5-15 keywords chacun.',
    verification: ['Chaque Ad Group ≥ 5 keywords', 'Aucun mélange thématique', 'Nommage cohérent'],
    erreurs: [
      ['1 keyword par Ad Group (SKAG)', 'Obsolète depuis Broad Match variants. STAG est la norme.'],
      ['20+ keywords par Ad Group', 'Impossible d\'écrire RSAs pertinents pour tous.'],
    ],
    conseil: 'STAG bien fait = Quality Score 8-10/10 → CPC divisé par 2-3.',
  }),
  ...etape('2. CRÉER LES AD GROUPS DANS ADS EDITOR', {
    objectif: 'Importer tout en batch via Google Ads Editor (10× plus rapide que UI)',
    temps: '30 min',
    ou: 'Google Ads Editor (desktop app)',
    actions: [
      'Télécharge Google Ads Editor si pas installé',
      'Editor → Get recent changes → sync ton compte',
      'Onglet Campagnes → + Nouvelle campagne (ou modifier existante)',
      'Onglet Ad Groups → clic droit → Import from spreadsheet → colle ton mapping',
      'Editor valide le CSV → si erreurs (URL invalide, char trop long), corrige',
      'Post → attente sync (1-3 min)',
    ],
    resultat: 'Ad Groups créés en batch.',
    verification: ['Editor sync sans erreur', 'Nb Ad Groups créés = attendu', 'Statut = « En attente d\'annonces »'],
    erreurs: [
      ['Créer à la main dans UI', 'Perte 3-5× de temps. Toujours Editor pour > 3 Ad Groups.'],
      ['Ne pas POST après Import', 'Rien envoyé à Google. Toujours vérifier statut « Posted ».'],
    ],
    conseil: 'Ads Editor a un mode « Undo » puissant. Fais un « Backup XML » avant chaque gros changement.',
  }),
  ...etape('3. AJOUTER 3 RSA PAR AD GROUP', {
    objectif: 'Chaque Ad Group doit avoir 3 Responsive Search Ads pour tester',
    temps: '30 min',
    ou: 'Ads Editor → Ads → + Nouvelle RSA',
    actions: [
      'Pour chaque Ad Group : minimum 15 headlines (30 char max), 4 descriptions (90 char max)',
      'Épingler intelligemment : Headline 1 = marque ou keyword principal, Headline 2 = USP unique',
      '3 variantes par Ad Group avec angles différents : autorité / urgence / social proof',
      'Chaque RSA doit avoir Ad Strength ≥ « Good » (idéal « Excellent »)',
      'Final URL = landing dédiée du Ad Group (pas homepage !)',
    ],
    resultat: '3 RSA par Ad Group + Ad Strength Good/Excellent.',
    verification: ['3 RSA par Ad Group', 'Ad Strength ≥ Good', 'Final URLs pointent vers landings dédiées'],
    erreurs: [
      ['1 seule RSA par Ad Group', 'Pas de A/B testing possible. Toujours 3 minimum.'],
      ['Épingler toutes les headlines', 'Bloque le ML de Google. Épingle max 2 (H1 + H2), laisse les autres libres.'],
    ],
    conseil: 'Ad Strength « Excellent » = +9% conversions vs « Poor » (data Google). Investis 30 min à l\'atteindre.',
  }),
  ...finalCheck([
    'Tous les Ad Groups créés avec STAG (5-15 keywords)',
    '3 RSAs par Ad Group',
    'Ad Strength ≥ Good partout',
    'Final URLs = landings dédiées',
    'Backup Editor XML fait',
  ]),
  ...qaCheck([
    'Aucun Ad Group ne mélange des thèmes ?',
    'Les RSAs varient-elles vraiment (3 angles différents) ?',
    'Chaque Ad Group a-t-il un « responsible » assigné pour A/B ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 3 RSAs par angle pour un Ad Group',
      prompt: 'Tu es Senior Google Ads copywriter. Pour l\'Ad Group « [NOM] » (mots-clés : [LISTE], landing URL : [URL], USP : [USP]), génère 3 RSAs. Contraintes : 15 headlines de 30 chars max, 4 descriptions de 90 chars max chacune. 3 angles distincts : (1) Autorité (années/experts), (2) Urgence (offre limitée), (3) Social proof (avis/clients). Pinning : H1 = brand, H2 = keyword. Format YAML par variante.' },
  ]),
  ...conseilsSenior([
    'STAG rigoureux + RSAs A/B = 90% de la perf Search. Le reste est du fine-tuning.',
    'Ne re-crée jamais un Ad Group qui perd — pause-le mais garde l\'historique (Google Ads apprend).',
    'Google Ads Editor sauve littéralement des heures. Fais-le devenir ta 2e nature.',
    'La landing doit contenir le mot-clé principal dans Title + H1. Sinon Quality Score bloqué à 3-5.',
  ]),
  ...validationFinale('Ad Groups structurés, RSAs prêtes, campagne prête à lancer.', 'Structure exportée depuis Editor dans Projet → Documentation'),
  ...escalade('Ad Strength « Poor » persistant malgré 3 variantes', 'Chef de projet — auditer la landing (souvent non-alignée avec keyword)'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_RSAS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger 3 RSAs (Responsive Search Ad) par Ad Group avec 3 angles psychologiques différents',
    resultat: 'Ad Strength ≥ Good, 15 headlines + 4 descriptions par RSA, 3 angles distincts.',
    delai: '30-45 min par Ad Group',
    canal: CANAL,
    regle: 'JAMAIS écrire une seule RSA. Toujours 3 minimum pour permettre à Google de tester.',
    prerequis: ['Ad Groups structurés STAG', 'Landings dédiées avec keyword dans title'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. BRIEF PSYCHOLOGIQUE : 3 ANGLES', {
    objectif: 'Définir 3 angles psychologiques distincts pour tes 3 RSAs',
    temps: '15 min',
    ou: 'Projet → Documentation → « Angles RSA »',
    actions: [
      'Angle 1 - Autorité : ancienneté, expertise, certifications, chiffres',
      'Angle 2 - Urgence : offre limitée, dernières places, promo fin de mois',
      'Angle 3 - Social Proof : nombre clients, notes, avis, cas',
      'Pour chaque angle, note 3 phrases fortes qui l\'incarnent',
      'Ces 3 phrases seront tes headlines épinglées ou top-performers',
    ],
    resultat: 'Brief 3 angles + 9 phrases fortes.',
    verification: ['3 angles psychologiquement distincts', '3 phrases par angle', 'Phrases mesurables ou concrètes'],
    conseil: 'Le duo Autorité + Social Proof convertit toujours en B2B. Urgence marche mieux en B2C.',
  }),
  ...etape('2. RÉDIGER 15 HEADLINES × 3 RSAs', {
    objectif: 'Chaque RSA doit avoir 15 headlines (30 chars max) couvrant : keyword + benefit + CTA + brand',
    temps: '30 min',
    ou: 'Ads Editor → Onglet Ads',
    actions: [
      'Headline 1 (épinglée pos 1) : Brand ou Keyword principal',
      'Headline 2 (épinglée pos 2) : USP unique',
      'Headlines 3-15 (libres) : benefits, garanties, CTAs, chiffres, callouts intégrés',
      'Utilise Dynamic Keyword Insertion sur 1-2 headlines : {KeyWord:default}',
      'Zéro majuscules abusives (« GRATUIT » = désapprobation policy)',
    ],
    resultat: '3 RSAs × 15 headlines = 45 headlines uniques.',
    verification: ['15 headlines par RSA', 'H1 et H2 épinglées', 'Ad Strength ≥ Good'],
    erreurs: [
      ['5 headlines par RSA', 'Ad Strength Poor. Google ne peut pas tester. Toujours 15.'],
      ['Toutes majuscules', 'Désapprobation policy. Une majuscule par mot max.'],
    ],
    conseil: 'Le DKI (Dynamic Keyword Insertion) booste CTR de 15-30% en Search. Utilise sur 1-2 headlines.',
  }),
  ...etape('3. RÉDIGER 4 DESCRIPTIONS + FINAL URL', {
    objectif: '4 descriptions (90 char max) qui prolongent les headlines + landing dédiée',
    temps: '15 min',
    ou: 'Ads Editor',
    actions: [
      'Description 1 : bénéfice + preuve + CTA',
      'Description 2 : USP + différenciation vs concurrents',
      'Description 3 : réassurance (garantie, retour, SAV)',
      'Description 4 : call to action final + urgence si applicable',
      'Final URL = landing dédiée à l\'Ad Group (contient le keyword)',
      'Display URL Path : /keyword ou /produit (utilise le path pour renforcer le keyword)',
    ],
    resultat: '3 RSAs complètes prêtes à publier.',
    verification: ['4 descriptions par RSA', 'Final URL landing dédiée', 'Display URL path renforce keyword'],
    conseil: 'Description 1 est LA plus vue. Investis 80% de ton effort dessus.',
  }),
  ...finalCheck([
    '3 RSAs par Ad Group',
    'Ad Strength ≥ Good pour chaque',
    '15 headlines par RSA',
    '4 descriptions par RSA',
    'H1 + H2 épinglées, autres libres',
    'Final URL = landing dédiée avec keyword dans title + H1',
    'Display URL Path renforce keyword',
  ]),
  ...qaCheck([
    'Les 3 angles psychologiques sont-ils vraiment distincts ?',
    'Aucune majuscule abusive ?',
    'DKI utilisé sur au moins 1 headline ?',
    'Landings testées (chargent, mobile-friendly, keyword présent) ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 3 RSAs par angle psychologique',
      prompt: 'Tu es Senior Google Ads copywriter. Ad Group : [NOM]. Keyword principal : [KEYWORD]. USP : [USP]. Landing : [URL]. Génère 3 RSAs distinctes, chacune avec 15 headlines (30 chars) + 4 descriptions (90 chars). Angles : (1) Autorité chiffrée, (2) Urgence contrôlée, (3) Social proof concret. Épingle H1=brand, H2=keyword. Utilise DKI {KeyWord:default} sur 1 headline par RSA. Format YAML.' },
    { agent: 'Claude Code', title: 'Vérifie Ad Strength anticipé',
      prompt: 'Voici mes 3 RSAs (YAML). Anticipe l\'Ad Strength selon les critères Google : (1) variété headlines (aucun doublon sémantique), (2) inclusion keyword dans ≥ 3 headlines, (3) présence CTA distincts, (4) longueur descriptions variée. Note chaque RSA /100 + explique les 3 changements les plus impactants pour passer de Good à Excellent.' },
  ]),
  ...conseilsSenior([
    'Pin trop = tue le ML. Pin trop peu = message dilué. La ligne juste : 2 headlines épinglées max.',
    'Ad Strength « Excellent » = +9% conv. Ne jamais accepter « Poor ».',
    'A/B tests RSAs = min 2 semaines par variante pour statistique fiable (30+ conv chacune).',
    'Chaque headline doit être un mini-slogan qui vend seul. Pas de phrases coupées.',
  ]),
  ...validationFinale('3 RSAs par Ad Group publiées, Ad Strength Good/Excellent, landings alignées.', 'Section « RSAs » dans Projet → Documentation'),
  ...escalade('Ad Strength « Poor » sur toutes variantes', 'Chef de projet — souvent problème d\'alignement landing/keyword'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_NEGATIVES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer et maintenir la liste des mots-clés négatifs partagée pour éviter les impressions gaspillage',
    resultat: 'Liste négatifs partagée compte 100+ termes + révisée chaque semaine.',
    delai: '30 min setup + 15 min hebdo',
    canal: CANAL,
    regle: 'Un compte sans négatifs = 20-40% de budget gaspillé. Négatifs = priorité 1 dès jour 1.',
    prerequis: ['Search Terms Report disponible (≥ 7 jours de données)'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. NÉGATIFS INITIAUX AVANT LANCEMENT', {
    objectif: 'Poser une liste négatifs de base pour éviter les catégories parasites',
    temps: '30 min',
    ou: 'Google Ads → Bibliothèque partagée → Listes de mots-clés négatifs',
    actions: [
      'Crée une liste « [Client] - Négatifs compte »',
      'Ajoute négatifs génériques : gratuit, free, tuto, cours, formation, exemple, DIY',
      'Ajoute négatifs sectoriels selon métier (ex métier B2B → « stage », « emploi », « salaire »)',
      'Ajoute négatifs concurrents nommés (leur marque en négatif exact)',
      'Applique la liste à toutes les campagnes',
    ],
    resultat: '80-100 négatifs de base actifs.',
    verification: ['Liste appliquée à toutes campagnes', 'Match type mixte : phrase + exact selon terme'],
    erreurs: [
      ['Négatif Broad Match (« emploi »)', 'Bloque « emploi de temps » aussi. Toujours Phrase ou Exact.'],
      ['Négatif = mot-clé actif d\'un Ad Group', 'Conflit. Vérifie les intersections avec Ads Editor.'],
    ],
    conseil: 'Depuis Broad Match élargi, les négatifs sont VITAL — sinon Google élargit à des synonymes non pertinents.',
  }),
  ...etape('2. AJOUT HEBDO SEARCH TERMS REPORT', {
    objectif: 'Chaque semaine, extraire les termes de recherche non pertinents pour les ajouter en négatifs',
    temps: '15 min',
    ou: 'Google Ads → Recherches → Termes de recherche',
    actions: [
      'Ads → Termes de recherche → filtre 7 derniers jours',
      'Trie par « Coût descendant »',
      'Repère les termes SANS conversion sur > 100 MAD dépensés',
      'Coche → clique « Ajouter comme négatif » → ajoute à la liste partagée',
      'Note dans Projet → Documentation le montant sauvé chaque semaine',
    ],
    resultat: 'Nouveaux négatifs ajoutés chaque semaine.',
    verification: ['≥ 5 nouveaux négatifs/semaine première mois', 'Économies chiffrées trackées'],
    erreurs: [
      ['Bloquer trop tôt (< 100 MAD)', 'Statistiquement peu fiable. Attendre seuil.'],
      ['Ne pas noter les économies', 'Client ne voit pas ta valeur. Toujours quantifier.'],
    ],
    conseil: 'Bloque en Phrase Match. Un phrase match « location voiture » bloque « location de voiture », « location voiture pas cher ». Économie massive.',
  }),
  ...etape('3. NÉGATIFS PAR AD GROUP (avancé)', {
    objectif: 'Ajouter des négatifs au niveau Ad Group pour affiner (ex séparation Devis vs Réparation)',
    temps: '20 min si applicable',
    ou: 'Ad Group → Négatifs',
    actions: [
      'Si 2 Ad Groups thématiquement proches (« Devis Toiture » et « Réparation Toiture »), ils se cannibalisent',
      'Sur Ad Group « Devis Toiture », ajoute négatif « réparation » (exact)',
      'Sur Ad Group « Réparation Toiture », ajoute négatif « devis » (exact)',
      'Chaque terme de recherche va au bon Ad Group avec le bon Quality Score',
    ],
    resultat: 'Cannibalisation résolue.',
    verification: ['Termes de recherche mieux distribués', 'Ad Group Quality Score en hausse'],
    conseil: 'La cannibalisation entre Ad Groups thématiquement proches est le tueur silencieux de Quality Score. Toujours vérifier.',
  }),
  ...finalCheck([
    'Liste partagée « Négatifs compte » créée + appliquée',
    '80-100 négatifs initiaux',
    'Match type Phrase ou Exact (jamais Broad)',
    'Revue hebdo Search Terms programmée',
    'Négatifs Ad Group ajoutés si cannibalisation',
  ]),
  ...qaCheck([
    'Aucun négatif Broad Match sur des mots courants ?',
    'Aucun négatif ne bloque un keyword actif d\'un Ad Group ?',
    'La revue hebdo est-elle documentée avec économies chiffrées ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 80 négatifs initiaux pour un secteur',
      prompt: 'Le client est [SECTEUR B2C ou B2B]. Génère 80 mots-clés négatifs à appliquer dès jour 1 pour éviter le gaspillage : (1) 20 génériques (gratuit, formation, exemple, etc.), (2) 30 sectoriels (concurrents connus, catégories parasites), (3) 30 métier (mots-clés spécifiques au marché Maroc). Format : liste plate séparée par virgules pour import direct Google Ads. Précise en note quel match type utiliser pour chaque groupe.' },
  ]),
  ...conseilsSenior([
    'Un compte propre en négatifs bat un compte optimisé en enchères.',
    'Toujours Phrase Match par défaut pour négatifs — Broad casse trop, Exact rate trop.',
    'Documentation hebdo des économies = client heureux, contrat renouvelé.',
    'Automatise via script : Google Ads Script « Search Query Negative » automatisé après 30j.',
  ]),
  ...validationFinale('Liste partagée > 100 négatifs, revue hebdo active, économies documentées.', 'Section « Négatifs » dans Projet → Documentation avec journal des ajouts'),
  ...escalade('Search Terms Report vide (tracking cassé)', 'Chef de projet — audit tracking Consent Mode v2'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_OPTIMISATION: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Optimiser les enchères + campagnes chaque semaine pour améliorer CPA/ROAS sans casser le learning',
    resultat: 'Actions hebdo tracées : enchères ajustées, budgets rebalancés, tests A/B avancés, apprentissage préservé.',
    delai: '2 h par semaine pour un compte moyen',
    canal: CANAL,
    regle: 'JAMAIS changer > 20% d\'un budget/enchère par semaine. Google entre en re-learning.',
    prerequis: ['Compte 30+ jours d\'historique', 'Tracking fiable', 'KPIs cibles clairs'],
  }),
  ...projectContext(['client.name', 'project.budget']),
  h2('Étapes'),
  ...etape('1. AUDIT PERFORMANCE 7 DERNIERS JOURS', {
    objectif: 'Photographier la perf hebdo + identifier les 3 leviers principaux',
    temps: '30 min',
    ou: 'Google Ads → Vue d\'ensemble + Rapports personnalisés',
    actions: [
      'Compare 7 derniers jours vs 7 précédents : CPA, ROAS, taux de conv, CTR',
      'Note dans Projet → Documentation : chiffres + delta %',
      'Identifie les 3 campagnes ou Ad Groups qui ont bougé le plus (positive ou négative)',
      'Vérifie que le tracking fonctionne toujours (test conversion réelle)',
      'Regarde « Statuts » : Learning, Learning Limited, Limited by Budget',
    ],
    resultat: 'Photo hebdo + 3 leviers d\'action identifiés.',
    verification: ['Comparaison 7j vs 7j faite', 'Tracking OK', 'Statuts campagnes notés'],
    erreurs: [
      ['Optimiser sur 24h de données', 'Statistiquement invalide. Minimum 7 jours.'],
      ['Ignorer « Learning »', 'Modifier une campagne en learning = reset. Attends fin learning (7-14j).'],
    ],
    conseil: 'La perf tombe le week-end pour B2B, monte pour B2C. Compare toujours L vs L, pas 7j full.',
  }),
  ...etape('2. AJUSTEMENTS ENCHÈRES ET BUDGETS', {
    objectif: 'Faire les ajustements chirurgicaux qui améliorent sans re-learning',
    temps: '45 min',
    ou: 'Google Ads → Campagnes / Ad Groups',
    actions: [
      'Ad Group avec CPA > cible × 1.5 : baisse enchère de -15% (ou baisse tCPA)',
      'Ad Group avec CPA < cible × 0.7 + Limité par budget : augmente budget +15% max',
      'Campagne avec taux d\'impressions perdues (rank) > 30% : augmente enchères Ad Groups top-perf',
      'Ne jamais > 20% de changement par semaine — Google entre en re-learning',
      'Note chaque changement dans Projet → Documentation avec avant/après',
    ],
    resultat: 'Ajustements < 20% enregistrés.',
    verification: ['Toutes les modifications < 20%', 'Chaque changement tracé', 'Ad Groups en learning NON touchés'],
    conseil: 'Petits changements réguliers (2 fois par mois × 10%) > gros changements ponctuels (1 fois × 40%). Google déteste les shocks.',
  }),
  ...etape('3. ANALYSE ET DÉCISION SEARCH TERMS', {
    objectif: 'Extraire de nouveaux mots-clés positifs + négatifs à partir du Search Terms Report',
    temps: '30 min',
    ou: 'Google Ads → Termes de recherche',
    actions: [
      'Filtre 7 derniers jours + conversions > 0',
      'Termes avec conversions mais match Phrase/Broad → ajoute en Exact dans un Ad Group dédié (control granulaire)',
      'Termes avec dépense > 100 MAD + 0 conv → ajoute négatifs (voir SOP négatifs)',
      'Note top 5 termes convertisseurs dans Projet → Documentation → « Insights »',
      'Cette liste devient la base d\'un rapport « Insights client » mensuel',
    ],
    resultat: 'Nouveaux Exacts + négatifs ajoutés.',
    verification: ['Top 5 termes convertisseurs documentés', 'Négatifs ajoutés à liste partagée'],
    conseil: 'Les mots-clés qui convertissent le plus ne sont JAMAIS ceux qu\'on avait imaginés. Écoute les termes de recherche religieusement.',
  }),
  ...etape('4. TESTS A/B + PROCHAINE ITÉRATION', {
    objectif: 'Lancer 1 A/B test par semaine (RSA, landing, offre) pour progresser',
    temps: '15 min',
    ou: 'Ads Editor + note dans Projet → Documentation',
    actions: [
      'Choisis 1 hypothèse à tester : nouveau angle RSA, nouveau CTA, nouvelle image',
      'Duplique une RSA existante → modifie 1 seul élément → publie',
      'Note dans Projet → Documentation : hypothèse + KPI mesuré + durée test (min 2 semaines)',
      'Programme la revue du test dans 2 semaines (task récurrente ERP)',
    ],
    resultat: '1 A/B test lancé.',
    verification: ['Hypothèse claire', 'KPI mesuré défini', 'Revue programmée'],
    conseil: 'Test 1 variable à la fois. Sinon impossible de savoir ce qui a marché.',
  }),
  ...finalCheck([
    'Audit 7j vs 7j fait',
    'Ajustements enchères < 20%',
    'Search Terms exploités (positifs + négatifs)',
    '1 A/B test lancé cette semaine',
    'Rapport hebdo au client rédigé',
  ]),
  ...qaCheck([
    'Aucun Ad Group en Learning n\'a été touché ?',
    'Chaque changement est-il tracé avec avant/après ?',
    'Le rapport client montre-t-il l\'impact chiffré ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Synthétise la revue hebdo pour le client',
      prompt: 'Voici les données 7j Google Ads : [COLLE CSV]. Rédige un rapport hebdo client en français : (1) 3 chiffres clés (CPA, conv, dépenses) vs semaine précédente, (2) 2-3 actions faites cette semaine + impact anticipé, (3) 1 alerte ou opportunité pour la semaine suivante. Zéro jargon. Max 200 mots.' },
  ]),
  ...conseilsSenior([
    'Discipline > improvisation. Même 2h par semaine, mais chaque semaine.',
    'Ne touche jamais un Ad Group en « Learning ». Attends la sortie.',
    'La règle 20% : + de 20% de changement = re-learning. Sacrifice si nécessaire, mais consciemment.',
    'Documente chaque décision — dans 6 mois tu voudras savoir POURQUOI tu as fait ça.',
  ]),
  ...validationFinale('Revue hebdo effectuée, tracée, communiquée au client.', 'Note hebdo dans Projet → Documentation'),
  ...escalade('CPA × 3 vs cible malgré 30j d\'optimisation', 'Chef de projet — remise en cause structurelle (audit stratégie)'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_AB_TESTING: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Structurer des A/B tests statistiquement valides sur RSAs, extensions, landings',
    resultat: 'Chaque test documenté (hypothèse, variable, KPI, résultat), gains cumulés > 15%/an.',
    delai: '15 min setup par test + 2 semaines observation minimum',
    canal: CANAL,
    regle: 'JAMAIS déclarer un gagnant sur < 30 conversions par variante. Statistiquement invalide.',
    prerequis: ['Volume conversions ≥ 60/mois (30 par variante en 2 semaines)'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. FORMULATION HYPOTHÈSE + KPI', {
    objectif: 'Une hypothèse claire, un seul changement, un KPI mesurable',
    temps: '15 min',
    ou: 'Projet → Documentation → « A/B Tests »',
    actions: [
      'Format hypothèse : « Si je [CHANGEMENT], alors [MÉTRIQUE] va [BOUGER] parce que [POURQUOI] »',
      'Exemple : « Si j\'ajoute “Devis gratuit” en headline 3, alors CTR va augmenter parce que la friction perçue baisse »',
      'Choisis 1 seule variable (jamais 2 en même temps)',
      'KPI mesurable : CTR, taux de conv, CPA (jamais « ça marche mieux »)',
      'Durée min = 2 semaines OU 30 conv/variante, le plus long',
    ],
    resultat: 'Hypothèse écrite, KPI clair, durée définie.',
    verification: ['1 seule variable', 'KPI chiffrable', 'Durée minimum respectée'],
    erreurs: [
      ['Tester 3 changements en même temps', 'Impossible d\'attribuer le gain. Toujours 1 variable.'],
      ['Regarder au bout de 3 jours', 'Bruit statistique. Attends 2 semaines minimum.'],
    ],
    conseil: 'La formulation « Si… alors… parce que… » force la clarté. Utilise TOUJOURS ce format.',
  }),
  ...etape('2. CRÉATION DES VARIANTES', {
    objectif: 'Créer variante B en dupliquant variante A puis modifiant UN seul élément',
    temps: '15 min',
    ou: 'Ads Editor',
    actions: [
      'Editor → duplique la RSA/campagne existante',
      'Renomme : « [Original] - Control » et « [Original] - Variant B »',
      'Modifie UNIQUEMENT l\'élément testé',
      'Publie les 2 en même temps dans le même Ad Group',
      'Google distribuera les impressions ~50/50 automatiquement (Optimize for = « Rotation » si tu veux forcer)',
    ],
    resultat: 'Control + Variant B en ligne.',
    verification: ['Un seul élément différent', 'Rotation équilibrée', 'Naming cohérent'],
    conseil: 'Google Ads Experiments (Drafts & Experiments) permet des tests 50/50 rigoureux au niveau campagne. Utilise-le pour des tests structurels.',
  }),
  ...etape('3. ANALYSE + DÉCISION', {
    objectif: 'Après 2 semaines, décider objectivement gagnant/perdant',
    temps: '20 min',
    ou: 'Google Ads → Rapports personnalisés',
    actions: [
      'Rapport comparant Control vs Variant B sur le KPI cible',
      'Vérifie : ≥ 30 conv par variante ? Sinon prolonge test',
      'Calcule confiance statistique : différence significative si > 15% écart',
      'Note dans Projet → Documentation : hypothèse validée / invalidée / non concluant',
      'Si gagnant : archive le control, garde le variant. Si perdant : reverse. Si non-conclusif : nouveau test.',
    ],
    resultat: 'Décision documentée + apprentissage capitalisé.',
    verification: ['30+ conv par variante', 'Écart > 15% pour déclarer gagnant', 'Décision tracée'],
    conseil: 'Un test qui « ne conclut pas » est un test réussi. Tu as appris que ce changement n\'a pas d\'impact.',
  }),
  ...finalCheck([
    'Hypothèse « Si… alors… parce que… » écrite',
    '1 seule variable testée',
    '2 semaines minimum d\'observation',
    '30+ conv par variante',
    'Décision tracée + capitalisée',
    '1 nouveau test planifié',
  ]),
  ...qaCheck([
    'Y avait-il vraiment UNE seule variable ?',
    'A-t-on attendu 30+ conv par variante ?',
    'L\'écart est-il > 15% pour appeler « gagnant » ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Propose 10 hypothèses A/B pertinentes',
      prompt: 'Voici mes RSAs et perfs actuelles [COLLE]. Propose 10 hypothèses A/B à tester dans les 3 prochains mois, priorisées par impact estimé × facilité. Format : « Si je [CHANGEMENT], alors [KPI] va [DELTA] parce que [POURQUOI] ». Chaque hypothèse mesurable en 2 semaines. Priorité : angles psychologiques, CTAs, extensions, DKI.' },
  ]),
  ...conseilsSenior([
    'Un test raté est aussi précieux qu\'un test réussi. Documente les deux.',
    'Programme les tests à l\'année : 26 tests × 2 semaines = 52 semaines. Discipline > génie.',
    'Ne teste jamais 2 changements = tu ne sauras rien. Patience.',
    'La confiance statistique est mathématique — 15% écart minimum avec 30 conv/variante, sinon reste sceptique.',
  ]),
  ...validationFinale('Test conclu, résultat tracé, prochain test programmé.', 'Journal A/B dans Projet → Documentation'),
  ...escalade('Volume trop faible pour A/B (< 30 conv/variante en 2 semaines)', 'Chef de projet — accepter tests plus longs OU tester au niveau campagne (Experiments)'),
]

/* ═══════════════════════════════════════════════════════════════════════ */
const SOP_RAPPORT: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger un rapport mensuel client clair, chiffré, orienté action',
    resultat: 'Rapport 3 pages max : KPIs / gains du mois / plan mois suivant. Signé par le client.',
    delai: '1 h par mois par client',
    canal: CANAL,
    regle: 'JAMAIS de rapport rempli de screenshots bruts. Toujours 1 phrase = 1 chiffre = 1 action.',
    prerequis: ['Data 30j complètes', 'Objectifs mensuels connus'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. EXTRACTION KPIS MENSUELS', {
    objectif: 'Extraire les 5 KPIs essentiels du mois avec comparaison',
    temps: '20 min',
    ou: 'Google Ads → Rapports personnalisés + GA4',
    actions: [
      'KPIs à extraire : Dépenses / Impressions / Clics / Conversions / CPA / ROAS',
      'Compare M vs M-1 ET vs même mois année précédente',
      'Ajoute % delta pour chaque',
      'Note les 3 chiffres qui ont le plus bougé (positifs ET négatifs)',
      'Vérifie cohérence GA4 (écart < 5%)',
    ],
    resultat: 'Tableau KPIs prêt.',
    verification: ['Comparaisons multiples', '3 mouvements majeurs identifiés', 'Cohérence GA4 vérifiée'],
    conseil: 'Un rapport sans comparaison ne dit rien. Toujours M vs M-1 et Y vs Y-1.',
  }),
  ...etape('2. ACTIONS DU MOIS + IMPACT', {
    objectif: 'Lister les 3-5 actions majeures + leur impact chiffré',
    temps: '20 min',
    ou: 'Projet → Documentation (journal d\'actions du mois)',
    actions: [
      'Liste toutes les actions faites (négatifs ajoutés, RSAs, budgets, tests)',
      'Sélectionne les 3-5 avec impact chiffrable',
      'Format : « [Action] → [Impact chiffré en MAD ou %] »',
      'Ex : « 45 négatifs ajoutés → 800 MAD/mois économisés »',
      'Attache screenshot preuve pour chaque',
    ],
    resultat: '3-5 actions × impact chiffré.',
    verification: ['Chaque action a un impact chiffré', 'Preuves attachées'],
    conseil: 'Chiffrer chaque action = client comprend ta valeur = renouvelle. Ne rate jamais cette étape.',
  }),
  ...etape('3. PLAN DU MOIS SUIVANT + RÉUNION', {
    objectif: 'Définir 3 priorités du mois suivant + valider avec client',
    temps: '20 min',
    ou: 'Projet → Documentation + réunion visio',
    actions: [
      'Rédige 3 priorités du mois suivant (max 3, sinon tu diluees)',
      'Chaque priorité : objectif chiffré + hypothèse + risque',
      'Rédige rapport final (3 pages max) avec structure : KPIs / Actions / Plan',
      'Envoie rapport dans Projet → Discussion + programme 30 min visio',
      'Réunion : présente en 15 min + 15 min questions/décisions',
    ],
    resultat: 'Rapport envoyé + réunion tenue + signature.',
    verification: ['Rapport ≤ 3 pages', '3 priorités clairs', 'Client a validé par écrit'],
    erreurs: [
      ['Envoyer sans présenter', 'Client ne lit pas / oublie. Toujours faire une visio courte.'],
      ['Rapport 15 pages', 'Personne ne lit. 3 pages maximum.'],
    ],
    conseil: 'Le client paie autant pour ton reporting que pour ton exécution. Ne le néglige jamais.',
  }),
  ...finalCheck([
    'KPIs comparés M vs M-1 et Y vs Y-1',
    '3-5 actions × impact chiffré',
    '3 priorités mois suivant claires',
    'Rapport ≤ 3 pages',
    'Réunion tenue + validation écrite',
  ]),
  ...qaCheck([
    'Chaque chiffre est-il correct et sourcé ?',
    'Le rapport tient-il vraiment en 3 pages ?',
    'Un client non-technique comprend-il tout ?',
    'La validation écrite est-elle archivée ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige rapport mensuel Google Ads client',
      prompt: 'Rédige un rapport mensuel Google Ads en français pour le client [NOM]. Données : dépenses [MAD], conv [NB], CPA [MAD], ROAS [X] vs mois précédent [DELTAS]. Actions du mois : [LISTE]. Structure attendue : (1) KPIs en tableau, (2) 3 gains chiffrés du mois, (3) 3 priorités mois suivant. Zéro jargon technique. Ton : direct, orienté business. Max 400 mots.' },
  ]),
  ...conseilsSenior([
    'Le rapport est ton meilleur outil de rétention client. Investis 1 h de qualité.',
    'Toujours quantifier ta valeur ajoutée en MAD, pas en %.',
    'Réunion mensuelle 30 min = obligatoire. Sinon le client oublie ta valeur.',
    'Toujours signer par écrit dans Projet → Discussion (« ok pour le plan »).',
  ]),
  ...validationFinale('Rapport présenté, plan validé par le client par écrit.', 'Fichier « Rapport_[Client]_[YYYY-MM].pdf » dans Projet → Documentation'),
  ...escalade('Client refuse la réunion mensuelle', 'Chef de projet — signal fort de désengagement'),
]

/* ═══════════════════════════════════════════════════════════════════════ */

export const SOP_INDEX_GOOGLE_ADS: Record<string, SopBlock[]> = {
  [norm('Audit compte Google Ads')]:      SOP_AUDIT,
  [norm('Étude mots-clés')]:              SOP_KEYWORDS,
  [norm('Budget + enchères')]:            SOP_BUDGET,
  [norm('Création compte / accès')]:      SOP_ACCESS,
  [norm('Conversions + tracking')]:       SOP_TRACKING,
  [norm('Audiences personnalisées')]:     SOP_AUDIENCES,
  [norm('Extensions d\'annonces')]:       SOP_EXTENSIONS,
  [norm('Groupes d\'annonces')]:          SOP_AD_GROUPS,
  [norm('Rédaction annonces (3 versions)')]: SOP_RSAS,
  [norm('Mots-clés négatifs')]:           SOP_NEGATIVES,
  [norm('Optimisation enchères')]:        SOP_OPTIMISATION,
  [norm('A/B testing annonces')]:         SOP_AB_TESTING,
  [norm('Rapport mensuel')]:              SOP_RAPPORT,
}
