/**
 * SOP — Identité visuelle / Logo (15 tâches)
 * Rôle : Directeur Artistique Senior — 30+ ans, marques internationales.
 */
import type { SopBlock } from '@/hooks/useSops'
import {
  introExpert, etape, finalCheck, qaCheck, promptCards,
  conseilsSenior, validationFinale, escalade, projectContext, h2, tip, beforeAfter,
} from './sopHelpers'

const norm = (s: string) => (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim()
const ROLE = 'Directeur Artistique Senior — 30+ ans, marques internationales, 500+ identités créées'
const CANAL = 'Blocage / clarification → Projet → Discussion (canal Créa)'

/* ─── BRIEF ───────────────────────────────────────────────────────────── */
const SOP_BRIEF: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Extraire la substance de la marque en 60 min pour orienter tous les visuels à venir',
    resultat: 'Document brief 1-page validé par le client, exploitable pour créer 3 pistes de logo',
    delai: '60 min entretien + 30 min synthèse',
    canal: CANAL,
    regle: 'Ne JAMAIS commencer à dessiner sans brief signé.',
    prerequis: ['Fiche client complète (secteur, cible, valeurs)', 'Accès Projet → Documentation'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. QUESTIONNAIRE (12 questions max)', {
    objectif: 'Préparer un entretien structuré',
    temps: '15 min',
    ou: 'Projet → Documentation → « Brief créatif »',
    actions: [
      '5 blocs de questions : Marque · Cible · Concurrence · Personnalité · Contraintes',
      'Question obligatoire : « Qu\'est-ce que le logo NE DOIT PAS évoquer ? »',
      'Question puissante : « Quelle marque admires-tu et pourquoi ? »',
      'Prépare moodboard sommaire de 6 images pour amorcer',
    ],
    resultat: 'Questionnaire prêt.',
    verification: ['12 questions max', 'Zone « couleurs interdites »', 'Zone « références aimées/détestées »'],
    conseil: 'La question « ce qu\'il NE DOIT PAS évoquer » évite 80% des allers-retours.',
  }),
  ...etape('2. ENTRETIEN + SYNTHÈSE', {
    objectif: 'Extraire matière brute + livrer brief 1 page signé',
    temps: '60+30 min',
    ou: 'Visio (lien archivé dans Projet → Documentation)',
    actions: [
      'Enregistre l\'entretien (accord client)',
      'Prends notes en direct dans le brief',
      'Reformule chaque réponse importante : « donc si je comprends bien… »',
      'Termine par « donne-moi 3 mots que le nouveau logo doit évoquer »',
      'Synthèse : 1 page A4 max, 3 mots-clés en gros en haut',
      'Envoie via Projet → Discussion + signature écrite',
    ],
    resultat: 'Brief signé.',
    verification: ['3 mots-clés obtenus', 'Contraintes noires listées', 'Signature écrite dans Projet → Discussion'],
    erreurs: [['Brief validé oralement uniquement', 'Sans écrit = pas de base pour reprises. Toujours signature.']],
    conseil: 'Les silences font parler. Pose la question, attends 5 secondes.',
  }),
  ...finalCheck(['Brief 1 page A4', '3 mots-clés obtenus', 'Couleurs interdites listées', 'Références aimées/détestées', 'Signature écrite']),
  ...qaCheck(['Le brief est-il signé ?', 'Les 3 mots-clés sont-ils actionnables en visuel ?', 'Enregistrement archivé ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: '12 questions de brief à partir d\'un secteur',
      prompt: 'Tu es Directeur Artistique senior. Client secteur [SECTEUR], cible [CIBLE]. Rédige 12 questions ouvertes pour brief créatif 45 min en 5 blocs (Marque, Cible, Concurrence, Personnalité, Contraintes). Inclure obligatoirement « ce que le logo NE DOIT PAS évoquer ». Markdown H3 par bloc.' },
    { agent: 'Claude Code', title: 'Convertit brief oral en 1-pager',
      prompt: 'Transcription brute entretien 45 min : [COLLE]. Extrait 1-pager Markdown : (1) Marque + baseline, (2) 3 mots-clés, (3) Cible en 1 phrase, (4) 5 différenciateurs, (5) Références aimées/détestées, (6) Contraintes absolues. Tient sur 1 page A4.' },
  ]),
  ...conseilsSenior([
    'La règle des 3 : jamais moins, jamais plus de 3 pistes.',
    'Un brief validé oralement n\'existe pas. Seul l\'écrit fait foi.',
    'La couleur préférée du client = pire donnée. Demande « quelle couleur = professionnel ? ».',
    'Enregistre TOUJOURS. Tu réécouteras à la 8e itération.',
  ]),
  ...validationFinale('Brief signé + tient sur 1 page + contraintes noires listées.', 'Fichier « Brief_[Client].md » dans Projet → Documentation'),
  ...escalade('Client refuse la signature du brief', 'Chef de projet'),
]

/* ─── RECHERCHE CONCURRENCE ───────────────────────────────────────────── */
const SOP_CONCURRENCE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Cartographier les logos concurrents pour éviter la ressemblance + identifier l\'espace libre',
    resultat: 'Board 8-12 logos concurrents analysés (couleurs, formes, style) + « white space » identifié',
    delai: '2 h',
    canal: CANAL,
    regle: 'JAMAIS reproduire un style sectoriel dominant. Cherche l\'espace libre.',
    prerequis: ['Brief signé', 'Liste concurrents identifiée'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. SÉLECTION 10-12 CONCURRENTS', {
    objectif: 'Identifier les concurrents directs + latéraux',
    temps: '30 min',
    ou: 'Google Search + Behance + Dribbble',
    actions: [
      'Liste 6 concurrents directs (même métier, même zone)',
      '4 concurrents latéraux (même cible, autre métier)',
      '2 « best in class » internationaux du secteur',
      'Screenshots des logos sur fond neutre',
      'Archive dans Projet → Ressources / Benchmarks',
    ],
    resultat: '10-12 logos collectés.',
    verification: ['Screenshots HD sur fond neutre', 'Mix direct/latéral/international'],
    conseil: 'Les « best in class » internationaux montrent où le marché local peut monter.',
  }),
  ...etape('2. ANALYSE COULEURS / FORMES / STYLES', {
    objectif: 'Extraire les patterns dominants pour identifier ce qui est « déjà pris »',
    temps: '1 h',
    ou: 'Projet → Documentation',
    actions: [
      'Tableau : Marque | Couleur dominante (HEX) | Forme (rond/carré/wordmark) | Style (moderne/classique/luxe)',
      'Note fréquence des couleurs : ex « 60% bleu » → bleu saturé',
      'Note formes dominantes : ex « 80% wordmark simple » → tenter un pictogramme',
      'Identifie 1-2 espaces libres (couleur × forme non-utilisés)',
    ],
    resultat: 'Analyse patterns + white space identifié.',
    verification: ['Fréquences couleurs mesurées', '1-2 espaces libres identifiés'],
    conseil: 'Si 60% du secteur est bleu, ne va pas au bleu. Différencie-toi visuellement.',
  }),
  ...finalCheck(['10-12 logos collectés', 'Analyse couleurs/formes/styles', 'White space identifié', 'Board archivé Projet → Ressources']),
  ...qaCheck(['L\'analyse évite-t-elle la ressemblance ?', 'Le white space est-il documenté ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Extrait white space concurrentiel',
      prompt: 'Voici 10 logos concurrents (descriptions) : [COLLE]. Identifie : (1) couleur dominante (fréquence %), (2) forme dominante (% pictogramme vs wordmark), (3) style dominant (moderne/classique/luxe). Puis propose 2 « white spaces » (combinaisons non utilisées) actionnables pour un nouveau logo.' },
  ]),
  ...conseilsSenior([
    'Le meilleur logo se différencie visuellement en 1 seconde de scroll.',
    'Ne copie jamais le leader — deviens un challenger visuel.',
    'Best in class internationaux montrent la maturité vers laquelle tendre.',
  ]),
  ...validationFinale('Board analysé + white space actionnable.', 'Fichier « Benchmark_[Client].pdf » dans Projet → Ressources'),
  ...escalade('Secteur saturé sans white space clair', 'Chef de projet — orienter vers différenciation par style/type plutôt que couleur'),
]

/* ─── MOODBOARD ───────────────────────────────────────────────────────── */
const SOP_MOODBOARD: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer moodboard 12-15 images incarnant les 3 mots-clés du brief',
    resultat: 'Board visuel présenté au client → validation avant croquis',
    delai: '2-3 h',
    canal: CANAL,
    regle: 'Ne dessine JAMAIS un logo avant moodboard validé.',
    prerequis: ['Brief signé', '3 mots-clés définis', 'White space concurrentiel identifié'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. COLLECTE 30-40 RÉFÉRENCES', {
    objectif: 'Chercher large avant de filtrer',
    temps: '1 h',
    ou: 'Pinterest / Behance / Unsplash',
    actions: [
      'Pinterest : recherche par mot-clé × style (ex « artisanal élégant »)',
      'Behance : cherche cas Directeurs Artistiques renommés',
      '10-12 par mot-clé (pour 3 mots = 30-40 refs)',
      'Sauvegarde en HD dans Projet → Ressources / Moodboard-brut',
    ],
    resultat: '30-40 refs collectées.',
    verification: ['10+ par mot-clé', 'HD > 1000px'],
    conseil: 'Va large en collecte. Le filtrage vient après. Ne t\'auto-censure pas.',
  }),
  ...etape('2. FILTRAGE + BOARD FINAL 12-15 IMAGES', {
    objectif: 'Réduire à 12-15 images qui incarnent VRAIMENT les 3 mots-clés',
    temps: '1 h',
    ou: 'Figma / Canva / Photoshop',
    actions: [
      'Grille 4×3 ou 5×3 pour 12-15 images',
      'Groupe par mot-clé : 4-5 images par mot-clé',
      'Chaque image = incarnation forte du mot-clé, pas illustration littérale',
      'Ajoute une palette couleur (5-6 HEX) en bas du board',
      'Ajoute 2-3 typographies suggérées (nom + preview)',
    ],
    resultat: 'Moodboard final structuré.',
    verification: ['12-15 images', 'Palette couleur présente', 'Typos suggérées'],
    erreurs: [['Trop d\'images (25+)', 'Client perdu. Reste 12-15.']],
    conseil: 'Le moodboard n\'est pas une expo — c\'est une direction. Filtre sévèrement.',
  }),
  ...etape('3. PRÉSENTATION CLIENT + VALIDATION', {
    objectif: 'Faire signer le moodboard avant croquis',
    temps: '30 min',
    ou: 'Visio (lien dans Projet → Documentation)',
    actions: [
      'Présente en 15 min : explique choix par mot-clé',
      'Demande retour : « quelle image est la plus juste ? Laquelle rate ? »',
      'Ajuste si besoin (2 itérations max)',
      'Signature écrite dans Projet → Discussion',
    ],
    resultat: 'Moodboard signé.',
    verification: ['Signature écrite', 'Retours clients intégrés'],
    conseil: 'Le client qui signe le moodboard peut moins revenir sur les croquis. Étape stratégique.',
  }),
  ...finalCheck(['30-40 refs collectées', '12-15 images filtrées', 'Palette + typos', 'Signature écrite']),
  ...qaCheck(['Chaque image incarne-t-elle un mot-clé ?', 'La palette est-elle en HEX ?', 'Signé par écrit ?']),
  ...promptCards([
    { agent: 'Gemini', title: '6 pistes moodboard à partir des 3 mots-clés',
      prompt: 'Les 3 mots-clés du brief : [MOT1, MOT2, MOT3]. Propose 6 pistes visuelles de moodboard qui incarnent ces mots. Par piste : (a) intitulé 3 mots, (b) description visuelle 2 lignes, (c) 2 marques existantes qui illustrent, (d) 4-5 codes couleurs HEX.' },
  ]),
  ...conseilsSenior([
    'Un moodboard signé = 60% de la validation logo assurée.',
    'Filtre à mort. 12-15 images focales > 30 images floues.',
    'Palette + typos dans le board = direction complète, pas juste inspiration.',
  ]),
  ...validationFinale('Moodboard 12-15 images signé + palette + typos suggérées.', 'Fichier « Moodboard_[Client].pdf » dans Projet → Ressources'),
  ...escalade('Client rejette les 2 itérations moodboard', 'Chef de projet — souvent brief à retravailler'),
]

/* ─── CROQUIS 3 PROPOSITIONS ──────────────────────────────────────────── */
const SOP_CROQUIS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Concevoir 3 pistes de logo distinctes couvrant 3 directions du moodboard',
    resultat: '3 logos digitaux HD, chacun sur fond blanc + fond noir, présentés en contexte',
    delai: '1-2 jours de créa',
    canal: CANAL,
    regle: 'Jamais moins, jamais plus de 3 pistes. Ni 2 (choix impossible), ni 4-5 (dilution).',
    prerequis: ['Moodboard signé', 'Brief signé'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. IDÉATION PAPIER (rapide, pas digitale)', {
    objectif: '20-30 croquis papier avant de sortir Illustrator',
    temps: '3-4 h',
    ou: 'Papier + crayon (photographie et archive)',
    actions: [
      '20-30 esquisses rapides (2 min chacune)',
      'Bannis la perfection — cherche variété',
      'Range par direction : minimaliste / illustratif / typographique',
      'Sélectionne 3 directions distinctes',
      'Photographie et archive dans Projet → Ressources / Croquis',
    ],
    resultat: '3 directions retenues.',
    verification: ['20+ esquisses réalisées', '3 directions distinctes'],
    conseil: 'Le papier libère la main. Illustrator bride. Toujours commencer papier.',
  }),
  ...etape('2. DIGITALISATION 3 PISTES (Illustrator/Figma)', {
    objectif: 'Sortir 3 logos vectoriels finaux',
    temps: '1 jour',
    ou: 'Illustrator ou Figma',
    actions: [
      'Chaque piste : version couleur + version noir/blanc',
      'Traits parfaitement vectorisés (pas de courbes bâclées)',
      'Alignement sur grille (12-16 pt)',
      'Test à petite taille (16 px) : logo doit rester lisible',
      'Export : SVG + PNG @2x sur fond blanc + fond noir',
    ],
    resultat: '3 logos vectorisés propres.',
    verification: ['Chaque logo lisible à 16 px', 'Vecteurs propres', 'Version couleur + N/B'],
    erreurs: [['Illisible à 16 px', 'Fatal pour favicon/mobile. Retravaille.']],
    conseil: 'Le logo doit fonctionner à 16 px. Sinon il est mort en 2024 (mobile, favicon, GBP).',
  }),
  ...etape('3. MISE EN CONTEXTE (mockups)', {
    objectif: 'Montrer les logos dans des contextes réels pour aider le client à visualiser',
    temps: '3-4 h',
    ou: 'Mockup files (Freepik / Envato / Cover Actions Pro)',
    actions: [
      'Mockup 1 : carte de visite',
      'Mockup 2 : t-shirt / uniforme',
      'Mockup 3 : réseaux sociaux (avatar Facebook)',
      'Mockup 4 : signalétique / vitrine (si applicable)',
      'Archive dans Projet → Ressources / Mockups',
    ],
    resultat: '3-4 mockups par piste (12 total).',
    verification: ['Chaque piste en 3-4 contextes', 'Mockups HD'],
    conseil: 'Les mockups font signer 30% plus vite. Client visualise → décide.',
  }),
  ...finalCheck(['20+ esquisses papier', '3 pistes vectorisées', 'Lisibilité 16 px OK', 'Version couleur + N/B', '3-4 mockups par piste']),
  ...qaCheck(['3 pistes vraiment distinctes ?', 'Test 16 px OK ?', 'Vecteurs propres ?', 'Mockups HD ?']),
  ...promptCards([
    { agent: 'Gemini', title: 'Suggère 3 directions logo depuis moodboard',
      prompt: 'Voici mon moodboard signé (descriptions) : [COLLE]. Propose 3 directions de logo distinctes qui pourraient incarner ces références : (1) Direction Minimaliste, (2) Direction Illustrative, (3) Direction Typographique. Pour chaque : concept 3 mots, forme dominante, palette 3 HEX, typographie suggérée. Pense mobile-first (16 px).' },
  ]),
  ...conseilsSenior([
    '20 esquisses papier > 3 logos digitaux directs.',
    'Le test 16 px est fatal. Pas négociable en 2024.',
    'Mockups font signer. Ne les rate jamais.',
    'Vecteurs propres = revente future possible. Pas de bricolage.',
  ]),
  ...validationFinale('3 pistes finales HD + mockups prêts pour présentation client.', 'Fichier « Pistes_[Client].pdf » dans Projet → Documentation'),
  ...escalade('3 pistes semblent trop similaires', 'Chef de projet — retour idéation papier obligatoire'),
]

/* ─── PRÉSENTATION CLIENT ─────────────────────────────────────────────── */
const SOP_PRESENTATION: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Présenter les 3 pistes de manière à orienter (pas laisser choisir sans guide)',
    resultat: 'Client choisit 1 piste + notes claires d\'itération',
    delai: '45-60 min visio',
    canal: CANAL,
    regle: 'JAMAIS présenter les 3 pistes de manière neutre. Toujours ta reco + rationale.',
    prerequis: ['3 pistes prêtes', 'Mockups', 'Client dispo'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. STRUCTURE DE PRÉSENTATION', {
    objectif: 'Structurer 45 min visio pour éviter chaos',
    temps: '15 min préparation',
    ou: 'Deck Figma / Keynote',
    actions: [
      'Slide 1 : rappel brief (3 mots-clés, cible, contraintes)',
      'Slide 2 : moodboard signé',
      'Slide 3-5 : 1 slide par piste avec logo + mockup + rationale',
      'Slide 6 : ta recommandation + pourquoi',
      'Slide 7 : Next steps',
    ],
    resultat: 'Deck prêt.',
    verification: ['Rappel brief présent', 'Reco explicite', 'Next steps'],
    conseil: 'Ta reco est la valeur ajoutée. Sans reco, le client se sent seul devant un choix.',
  }),
  ...etape('2. VISIO + CAPTURE RETOURS', {
    objectif: 'Présenter en 20 min + 25 min Q/A structuré',
    temps: '45-60 min',
    ou: 'Visio (lien dans Projet → Documentation)',
    actions: [
      'Enregistre la visio (accord client)',
      'Ne demande PAS « laquelle tu préfères » — demande « laquelle correspond aux 3 mots-clés »',
      'Note chaque retour dans doc partagé en direct',
      'Termine par : décision + itérations demandées (max 3)',
    ],
    resultat: 'Retours structurés notés.',
    verification: ['Décision claire', '≤ 3 itérations demandées', 'Enregistrement archivé'],
    erreurs: [['Client hésite entre 2 pistes', 'Force le choix : « si tu devais choisir demain, lequel ? ».']],
    conseil: 'Ne jamais laisser une réunion sans décision. Force la clarification.',
  }),
  ...etape('3. FORMALISATION + SIGNATURE', {
    objectif: 'Traduire retours oraux en écrit signé',
    temps: '30 min',
    ou: 'Projet → Documentation + Discussion',
    actions: [
      'Résumé écrit : piste choisie + 3 itérations demandées + timeline',
      'Envoie via Projet → Discussion + demande accusé « ok pour la suite »',
      'Sans signature écrite → pas de démarrage itération',
    ],
    resultat: 'Décision signée.',
    verification: ['Résumé complet', 'Signature écrite Projet → Discussion'],
    conseil: 'La signature écrite protège des « je n\'ai jamais dit ça » 2 semaines plus tard.',
  }),
  ...finalCheck(['Deck préparé', 'Visio tenue + enregistrée', '1 piste choisie', '≤ 3 itérations demandées', 'Signature écrite']),
  ...qaCheck(['Ta reco est-elle explicite ?', 'La décision est-elle par écrit ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Structure présentation logo client 45 min',
      prompt: 'Rédige structure présentation client 45 min pour 3 pistes logo. Contraintes : (1) rappel brief, (2) rationale par piste, (3) ta reco explicite, (4) tips pour orienter sans imposer. Sortie : plan de slides + phrases clés par slide.' },
  ]),
  ...conseilsSenior([
    'Ta reco EST la valeur ajoutée. Client paie pour ton avis, pas pour choisir seul.',
    'Enregistre TOUT. Tu réécouteras à la 3e itération.',
    'Signature écrite non négociable. « Ok pour la suite » suffit.',
  ]),
  ...validationFinale('1 piste choisie + itérations écrites + signature.', 'Résumé dans Projet → Discussion + Documentation'),
  ...escalade('Client refuse de choisir même sous pression', 'Chef de projet — brief probablement à revoir'),
]

/* ─── ITÉRATIONS ──────────────────────────────────────────────────────── */
const SOP_ITERATIONS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Livrer 2-3 itérations propres du logo choisi selon retours écrits',
    resultat: 'Logo final proche perfection, itérations bornées (jamais > 3)',
    delai: '2-3 jours',
    canal: CANAL,
    regle: 'Max 3 itérations. Au-delà → nouveau devis (spirale infinie).',
    prerequis: ['Piste choisie + itérations écrites'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. ITÉRATION 1 - AJUSTEMENTS STRUCTURELS', {
    objectif: 'Appliquer les retours majeurs (formes, couleurs)',
    temps: '1 jour',
    ou: 'Illustrator / Figma',
    actions: [
      'Lis retour écrit avant de toucher au fichier',
      'Applique changements majeurs (forme, couleur, proportions)',
      'Ne touche PAS aux détails encore',
      'Test à 16 px après chaque changement',
      'Compare A/B avant/après dans un doc',
    ],
    resultat: 'Version V2 prête.',
    verification: ['Retours écrits respectés', 'Test 16 px', 'A/B doc'],
    conseil: 'Applique les gros changements d\'abord. Les détails viennent en itération 2.',
  }),
  ...etape('2. ITÉRATION 2 - RAFFINEMENT', {
    objectif: 'Ajuster détails (spacing, typo, épaisseur trait)',
    temps: '1 jour',
    ou: 'Illustrator',
    actions: [
      'Ajustements typographiques (letter-spacing, weight)',
      'Alignements pixel-perfect',
      'Épaisseurs trait cohérentes partout',
      'Vérifie 3 tailles (16 px, 64 px, 512 px)',
    ],
    resultat: 'V3 raffinée.',
    verification: ['Alignement grid', 'Épaisseurs cohérentes', 'Test multi-tailles'],
    conseil: 'Un logo raffiné = 10 minuscules détails corrigés. Investis les 2 dernières heures.',
  }),
  ...etape('3. ITÉRATION 3 - FINITIONS + SIGNATURE', {
    objectif: 'Dernière passe et validation finale',
    temps: '2 h',
    ou: 'Visio + Projet → Discussion',
    actions: [
      'Envoie V3 en HD + fond blanc + fond noir',
      'Demande validation écrite « ok final »',
      'Si nouveau retour → prévenir : « on entre au-delà de la 3e itération, nouveau devis »',
    ],
    resultat: 'Validation finale signée.',
    verification: ['Signature écrite « ok final »', 'Fichiers HD envoyés'],
    conseil: 'Signature explicite = protection contre les 6 mois de « en fait je préférais V1 ».',
  }),
  ...finalCheck(['≤ 3 itérations respectées', 'V finale HD + fond blanc + noir', 'Signature écrite finale', 'Test 3 tailles']),
  ...qaCheck(['Retours strictement écrits appliqués ?', 'Test 16 px OK ?', 'Signature « ok final » ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Résume 20 retours clients écrits en 5 changements actionnables',
      prompt: 'Voici 20 retours clients écrits sur mon logo : [COLLE]. Résume en 5 changements actionnables classés par impact (structural → détail). Ignore les retours contradictoires. Format : « [Retour X] → [Action précise] ».' },
  ]),
  ...conseilsSenior([
    'Max 3 itérations. Au-delà = nouveau devis. Non négociable.',
    'Gros changements en itération 1. Détails en 2. Finitions en 3.',
    'Signature explicite finale = protection future.',
  ]),
  ...validationFinale('Logo final signé, prêt pour déclinaisons.', 'Version finale HD dans Projet → Ressources'),
  ...escalade('Client demande 4e itération', 'Chef de projet — nouveau devis à formaliser'),
]

/* ─── VALIDATION FINALE ───────────────────────────────────────────────── */
const SOP_VALIDATION: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Obtenir validation finale écrite du logo pour passer aux déclinaisons',
    resultat: 'Signature écrite « ok final » dans Projet → Discussion. Aucune ambiguïté.',
    delai: '15-30 min',
    canal: CANAL,
    regle: 'Sans signature écrite explicite, ne JAMAIS démarrer déclinaisons.',
    prerequis: ['V3 livrée', 'Client informé du process'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. ENVOI V FINALE + DEMANDE VALIDATION', {
    objectif: 'Faire signer noir sur blanc',
    temps: '15 min',
    ou: 'Projet → Discussion',
    actions: [
      'Envoie fichier final HD + version noir/blanc',
      'Message type : « Voici la V finale. Merci de confirmer par écrit “ok final” pour passer aux déclinaisons »',
      'Attend réponse écrite explicite',
      'Si silence 48h → relance',
    ],
    resultat: 'Signature « ok final ».',
    verification: ['Réponse écrite explicite', 'Aucune ambiguïté'],
    conseil: 'La formule exacte « ok final » évite les malentendus.',
  }),
  ...etape('2. ARCHIVAGE FICHIERS SOURCES', {
    objectif: 'Sauvegarder tous les fichiers de travail avant de fermer',
    temps: '15 min',
    ou: 'Projet → Ressources',
    actions: [
      'Archive AI/SVG source dans Projet → Ressources / Logo-final',
      'Archive PNG HD (2000px + 500px)',
      'Archive version couleur + version N/B',
      'Note version + date dans nom de fichier',
    ],
    resultat: 'Archive complète.',
    verification: ['Fichiers sources + PNG', 'Versions couleur + N/B', 'Nommage clair'],
    conseil: 'Un fichier perdu = drame. Archive dès la signature.',
  }),
  ...finalCheck(['Signature « ok final » écrite', 'AI/SVG archivés', 'PNG HD archivés', 'Versions couleur + N/B', 'Nommage clair']),
  ...qaCheck(['La signature est-elle sans ambiguïté ?', 'Tous les fichiers sont-ils archivés ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige message validation finale non ambigu',
      prompt: 'Rédige message court (max 5 lignes) au client pour demander validation écrite du logo final. Inclure : (1) merci pour les retours, (2) V finale attachée, (3) demande de réponse écrite « ok final ». Ton : professionnel et direct.' },
  ]),
  ...conseilsSenior([
    'Signature écrite explicite = protection future.',
    'Archive TOUT dès signature — ne fais pas ça 3 mois après.',
    'La formule « ok final » évite les malentendus culturels.',
  ]),
  ...validationFinale('Signature « ok final » écrite + archives complètes.', 'Message dans Projet → Discussion + fichiers dans Projet → Ressources'),
  ...escalade('Client ne valide jamais par écrit', 'Chef de projet — bloquer déclinaisons jusqu\'à écrit'),
]

/* ─── DÉCLINAISONS COULEUR / N&B ──────────────────────────────────────── */
const SOP_DECLINAISONS_COULEUR: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer versions couleur / noir / blanc du logo pour tous usages',
    resultat: '3 versions vectorielles (couleur / 100% noir / 100% blanc) + export PNG',
    delai: '1-2 h',
    canal: CANAL,
    regle: 'Un logo qui ne fonctionne pas en noir & blanc N\'EST PAS un logo.',
    prerequis: ['Logo final signé'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. CRÉER LES 3 VERSIONS', {
    objectif: 'Version couleur, version 100% noir, version 100% blanc',
    temps: '45 min',
    ou: 'Illustrator',
    actions: [
      'Version couleur : palette officielle (RGB + CMYK + Pantone)',
      'Version 100% noir : tout ce qui est coloré devient noir uni',
      'Version 100% blanc : inverse — pour fond sombre',
      'Vérifie lisibilité chaque version',
      'Aucun dégradé qui empêche le noir/blanc simple',
    ],
    resultat: '3 versions prêtes.',
    verification: ['Test lisibilité chaque version', 'Aucun dégradé bloquant'],
    erreurs: [['Dégradés impossibles à convertir en N&B', 'Refaire simplement le logo, dégradé = piège à long terme.']],
    conseil: 'Le test noir/blanc révèle les faiblesses. Si le logo perd son identité en N/B, retour case départ.',
  }),
  ...etape('2. EXPORTS VECTORIELS + PNG', {
    objectif: 'Export SVG + AI + PNG HD des 3 versions',
    temps: '30 min',
    ou: 'Illustrator export',
    actions: [
      'AI : version éditable (garde les couleurs officielles nommées)',
      'SVG : optimisé, sans classes CSS inutiles',
      'PNG @2000px + @500px + @200px pour chaque version',
      'Convention nommage : [client]_logo_[version]_[taille].[ext]',
      'Ex : brinova_logo_noir_2000.png, brinova_logo_couleur_500.svg',
    ],
    resultat: 'Exports complets nommés.',
    verification: ['3 versions × 3 tailles PNG', 'AI + SVG', 'Nommage cohérent'],
    conseil: 'Nommage rigoureux = jamais de client qui perd un fichier.',
  }),
  ...finalCheck(['Version couleur créée', 'Version 100% noir', 'Version 100% blanc', 'AI + SVG + PNG HD', 'Nommage cohérent']),
  ...qaCheck(['Logo lisible en N&B ?', 'Nommage clair ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère convention nommage fichiers',
      prompt: 'Propose convention nommage pour livrables logo : versions (couleur/noir/blanc) × formats (SVG/AI/PNG) × tailles (2000/500/200). Contraintes : lowercase, séparé par underscore, court mais explicite. Format : liste exemples + règle générale.' },
  ]),
  ...conseilsSenior([
    'Un logo qui ne survit pas en N/B est incomplet. Non négociable.',
    'Nommage rigoureux = -50% de tickets « où est le fichier X ? ».',
    'AI + SVG + PNG = trinité obligatoire. Rien d\'autre.',
  ]),
  ...validationFinale('3 versions livrées + exports nommés.', 'Dossier « Logo - Déclinaisons » dans Projet → Ressources'),
  ...escalade('Logo perd son identité en N/B', 'Directeur créa — retour case départ'),
]

/* ─── HORIZONTAL / CARRÉ ──────────────────────────────────────────────── */
const SOP_HORIZONTAL_CARRE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer version horizontale (bannières) + version carrée (avatar) du logo',
    resultat: '2 formats adaptés : horizontal 3:1 ou 4:1 + carré 1:1 (mêmes proportions internes)',
    delai: '1-2 h',
    canal: CANAL,
    regle: 'Ne pas déformer le logo pour qu\'il rentre. Créer variations propres.',
    prerequis: ['Logo final signé + versions couleur/N/B'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. VERSION HORIZONTALE (bannières, entête)', {
    objectif: 'Adapter le logo à des espaces horizontaux (site web, entête email)',
    temps: '45 min',
    ou: 'Illustrator',
    actions: [
      'Si logo pictogramme + wordmark → mettre pictogramme à gauche, wordmark à droite',
      'Si logo wordmark seul → augmenter le letter-spacing pour équilibrer',
      'Ratio cible : 3:1 ou 4:1',
      'Test dans un vrai contexte (site web mockup)',
    ],
    resultat: 'Version horizontale nette.',
    verification: ['Ratio 3:1 ou 4:1', 'Test mockup site'],
    conseil: 'Ne squeeze jamais. Réarrange les éléments.',
  }),
  ...etape('2. VERSION CARRÉE (avatar, favicon-ready)', {
    objectif: 'Version 1:1 pour avatars réseaux sociaux',
    temps: '30 min',
    ou: 'Illustrator',
    actions: [
      'Si logo horizontal → extraire pictogramme uniquement',
      'Si logo wordmark seul → prendre initiales OU logo empilé',
      'Marge intérieure 15-20% (safe zone circulaire pour crop)',
      'Test à 200 px et 40 px',
    ],
    resultat: 'Version carrée nette.',
    verification: ['Marge safe 15-20%', 'Test 40 px', 'Aucune coupe importante'],
    conseil: 'Beaucoup de plateformes croppent en cercle. Pense circulaire.',
  }),
  ...finalCheck(['Version horizontale 3:1 ou 4:1', 'Version carrée 1:1', 'Safe zone circulaire', 'Test tailles réelles']),
  ...qaCheck(['Test avatar réseaux sociaux ?', 'Aucun étirement ?']),
  ...promptCards([
    { agent: 'Gemini', title: 'Recommandations layout horizontal/carré',
      prompt: 'Mon logo est [DESCRIPTION - wordmark seul / pictogramme+wordmark]. Propose comment le décliner : (1) horizontal 3:1 pour entête site, (2) carré 1:1 pour avatar social. Détaille positionnement, letter-spacing, safe zone.' },
  ]),
  ...conseilsSenior([
    'Un vrai directeur artistique livre TOUJOURS 3 versions : logo principal + horizontal + carré.',
    'Safe zone 15-20% pour crop circulaire.',
    'Ne squeeze jamais. Réarrange.',
  ]),
  ...validationFinale('Versions horizontale + carrée livrées.', 'Dossier « Logo - Formats » dans Projet → Ressources'),
  ...escalade('Logo intrinsèquement inadapté au carré', 'Chef de projet — repenser structure logo'),
]

/* ─── FAVICON ─────────────────────────────────────────────────────────── */
const SOP_FAVICON: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer favicon multi-tailles (16, 32, 48, 64, 180) + Apple Touch Icon',
    resultat: 'Fichiers ICO + PNG pour toutes plateformes, lisibles à 16 px',
    delai: '1 h',
    canal: CANAL,
    regle: 'Le favicon doit être lisible à 16 px. Sinon = fail.',
    prerequis: ['Version carrée du logo prête'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. SIMPLIFICATION EXTRÊME', {
    objectif: 'Réduire le logo à son essence pour 16 px',
    temps: '30 min',
    ou: 'Illustrator',
    actions: [
      'Prendre la version carrée',
      'Simplifier les détails : supprimer traits < 2 px',
      'Renforcer les contrastes',
      'Essayer 16 px directement pendant la conception',
      'Ne pas dépasser 2 couleurs pour 16 px',
    ],
    resultat: 'Version favicon simplifiée.',
    verification: ['Test 16 px', '≤ 2 couleurs', 'Contrastes forts'],
    conseil: 'Si tu essaies de rétrécir un logo complexe, échec assuré. Repense pour la petite taille.',
  }),
  ...etape('2. EXPORT MULTI-TAILLES', {
    objectif: 'Générer toutes tailles standards',
    temps: '30 min',
    ou: 'Favicon Generator (favicon.io ou realfavicongenerator.net)',
    actions: [
      'PNG @16px + @32px + @48px + @64px',
      'Apple Touch Icon @180px',
      'ICO multi-tailles (16-32-48)',
      'Manifest.json pour PWA',
      'Convention nommage : favicon-[taille].png',
    ],
    resultat: 'Pack favicon complet.',
    verification: ['Toutes tailles présentes', 'ICO multi-tailles', 'Apple Touch 180px'],
    conseil: 'RealFaviconGenerator génère TOUT en 30 secondes. Utilise-le.',
  }),
  ...finalCheck(['Design simplifié 16 px', 'PNG multi-tailles', 'ICO', 'Apple Touch Icon 180', 'Manifest.json PWA']),
  ...qaCheck(['Lisible à 16 px ?', 'Toutes tailles présentes ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère HTML pour intégration favicon complète',
      prompt: 'Rédige la balise HTML complète à insérer dans <head> pour toutes les plateformes (favicon 16/32, apple-touch-icon 180, manifest.json PWA). Inclure meta theme-color. Chemin : /favicon-XX.png.' },
  ]),
  ...conseilsSenior([
    'RealFaviconGenerator = outil officiel. Utilise-le.',
    'Test 16 px pendant le design, pas après.',
    'Apple Touch Icon = obligatoire mobile iOS.',
  ]),
  ...validationFinale('Pack favicon complet livrable.', 'Dossier « Favicon » dans Projet → Ressources'),
  ...escalade('Logo non simplifiable à 16 px', 'Directeur créa — créer un pictogramme dédié pour favicon'),
]

/* ─── CHARTE GRAPHIQUE PDF ────────────────────────────────────────────── */
const SOP_CHARTE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger charte graphique PDF 8-12 pages : usage logo, couleurs, typos, exemples',
    resultat: 'PDF prêt à distribuer à tout collaborateur externe (imprimeur, community, dev)',
    delai: '1 jour',
    canal: CANAL,
    regle: 'Sans charte, l\'identité se dilue en 6 mois.',
    prerequis: ['Logo final + déclinaisons + palette + typos'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. STRUCTURE CHARTE (8-12 pages)', {
    objectif: 'Structure standard qui couvre tous usages',
    temps: '30 min',
    ou: 'InDesign / Figma / Canva Pro',
    actions: [
      'Page 1 : couverture + version horizontale du logo',
      'Page 2 : les 3 mots-clés + baseline (si existante)',
      'Page 3 : logo principal + zone protection',
      'Page 4 : déclinaisons (couleur/noir/blanc/horizontal/carré)',
      'Page 5 : usages INTERDITS (déformation, ombres, changement couleur)',
      'Page 6 : palette couleurs (HEX + RGB + CMYK + Pantone)',
      'Page 7 : typographies (titre + corps + citations)',
      'Page 8 : exemples applications (papeterie, digital, signalétique)',
    ],
    resultat: 'Structure planifiée.',
    verification: ['8+ pages', 'Toutes les sections présentes'],
    conseil: 'Page « usages interdits » = plus valuable que « usages autorisés ». Focus sur les erreurs.',
  }),
  ...etape('2. RÉDACTION + MISE EN PAGE', {
    objectif: 'Créer le PDF final',
    temps: '4-6 h',
    ou: 'InDesign ou Figma',
    actions: [
      'Format A4 portrait',
      'Utiliser le logo dans un contexte MockUp pour chaque page',
      'Codes couleurs en HEX/RGB/CMYK/Pantone (Pantone approximé si pas payé)',
      'Typos suggérées avec preview + licence (Adobe Fonts / Google Fonts)',
      'Zone protection = 25% de la hauteur du logo autour',
      'Section « interdits » avec 6 exemples croisés en rouge',
    ],
    resultat: 'PDF finalisé.',
    verification: ['8-12 pages', 'Codes couleurs complets', 'Section interdits présente'],
    conseil: 'Show don\'t tell — un mockup vaut 100 mots de description.',
  }),
  ...etape('3. VALIDATION + LIVRAISON', {
    objectif: 'Faire signer la charte + livrer PDF',
    temps: '1 h',
    ou: 'Projet → Documentation + Discussion',
    actions: [
      'Envoie PDF en HD',
      'Demande relecture 24-48h',
      'Applique retours mineurs si besoin',
      'Signature écrite « ok charte »',
    ],
    resultat: 'Charte signée + livrée.',
    verification: ['Signature écrite', 'PDF archivé Projet → Ressources'],
    conseil: 'La charte protège autant le client que toi. Investis-la sérieusement.',
  }),
  ...finalCheck(['Structure 8-12 pages', 'Logo + déclinaisons + interdits', 'Palette complète (HEX/RGB/CMYK/Pantone)', 'Typos avec licence', 'Signature écrite']),
  ...qaCheck(['Section « usages interdits » présente ?', 'Zone protection définie ?', 'Signée par écrit ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige rules book charte graphique',
      prompt: 'Rédige les règles clés d\'une charte graphique 8 pages pour un logo [DESCRIPTION]. Sections : (1) Usage principal, (2) Zone protection, (3) Interdits (6 exemples), (4) Palette 5 HEX, (5) Typos titre + corps. Ton : direct, actionnable, un décideur non-designer doit comprendre.' },
  ]),
  ...conseilsSenior([
    'Sans charte, l\'identité se dilue en 6 mois.',
    'Section « interdits » > section « autorisés ». Focus erreurs.',
    'Show don\'t tell — mockups partout.',
    'La signature écrite scelle le respect futur de la charte.',
  ]),
  ...validationFinale('Charte 8-12 pages signée et archivée.', 'Fichier « Charte_[Client].pdf » dans Projet → Ressources'),
  ...escalade('Client refuse de signer la charte', 'Chef de projet — signal fort de dilution future'),
]

/* ─── LIVRAISON VECTORIELS ────────────────────────────────────────────── */
const SOP_VECTORIELS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Livrer fichiers vectoriels finaux (AI + SVG) compatibles tous usages',
    resultat: 'Pack AI CS6+ et SVG optimisé, textes outlined, couleurs nommées',
    delai: '30 min',
    canal: CANAL,
    regle: 'Textes TOUJOURS outlined (Convertir en tracés) avant livraison. Sinon = police manquante = catastrophe.',
    prerequis: ['Logo final signé'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. PRÉPARATION FICHIERS AI', {
    objectif: 'Fichier AI propre, éditable, textes outlined',
    temps: '15 min',
    ou: 'Illustrator',
    actions: [
      'Ouvre fichier source',
      'Tout sélectionner → Menu Type → Convertir en tracés',
      'Nomme les couleurs (Pantone / HEX)',
      'Vérifie qu\'aucun élément lié n\'est cassé (fichiers embarqués OK)',
      'Enregistrer sous → AI CS6 (compat max)',
    ],
    resultat: 'AI propre livrable.',
    verification: ['Textes outlined', 'Couleurs nommées', 'CS6 compat'],
    erreurs: [['Textes non outlined', 'Ouverture sans police = catastrophe. Toujours outlined.']],
    conseil: 'CS6 = format le plus large de compatibilité. Prends-le comme défaut.',
  }),
  ...etape('2. SVG OPTIMISÉ', {
    objectif: 'SVG léger, sans classes CSS parasites',
    temps: '15 min',
    ou: 'Illustrator + SVGO (svgomg.net)',
    actions: [
      'Export SVG depuis Illustrator (Present : Style CSS interne)',
      'Passe le SVG dans SVGOMG (compression sans perte)',
      'Vérifie que couleurs sont dans les balises SVG (pas CSS externe)',
      'Test dans navigateur',
    ],
    resultat: 'SVG optimisé.',
    verification: ['Taille < 20 Ko', 'Ouverture navigateur OK', 'Aucune CSS externe'],
    conseil: 'SVGOMG divise le poids par 3-5 sans perte visible.',
  }),
  ...finalCheck(['AI CS6+ textes outlined', 'SVG optimisé < 20 Ko', 'Couleurs nommées', 'Ouverture testée']),
  ...qaCheck(['Textes outlined ?', 'CS6 compat ?', 'SVG optimisé ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Optimise SVG avec SVGO',
      prompt: 'Voici mon SVG brut Illustrator (colle contenu) : [SVG]. Optimise-le : (1) supprimer metadata, comments, editor tags, (2) remove empty attributes, (3) préserver viewBox, (4) préserver title/desc pour accessibilité. Sortie : SVG optimisé + gain en % versus original.' },
  ]),
  ...conseilsSenior([
    'Textes non outlined = catastrophe garantie. Non négociable.',
    'AI CS6 = compat max. Prends-le comme défaut.',
    'SVGOMG divise le poids par 3-5. Toujours passer par lui.',
  ]),
  ...validationFinale('AI + SVG propres livrables.', 'Dossier « Vectoriels » dans Projet → Ressources'),
  ...escalade('Fichier corrompu au dernier moment', 'Backup automatique du fichier source à conserver'),
]

/* ─── LIVRAISON PNG/JPG ───────────────────────────────────────────────── */
const SOP_RASTER: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Livrer PNG (fond transparent) + JPG (fond blanc) en tailles multi-usage',
    resultat: 'Pack PNG @2000/1000/500/200/64 + JPG @2000/500 pour web et print',
    delai: '30 min',
    canal: CANAL,
    regle: 'Toujours livrer PNG transparent ET JPG blanc — usages différents.',
    prerequis: ['Vectoriels finaux'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. EXPORT PNG (transparent)', {
    objectif: 'Export multi-tailles PNG avec fond transparent',
    temps: '15 min',
    ou: 'Illustrator Export for Screens',
    actions: [
      'File → Export → Export for Screens',
      'Formats : PNG 2000px, 1000px, 500px, 200px, 64px',
      'Fond : transparent',
      'Optimisation : max qualité, pas de compression destructive',
      'Convention nommage : [client]_logo_[version]_[taille].png',
    ],
    resultat: 'PNG multi-tailles.',
    verification: ['Fond transparent vérifié', '5 tailles', 'Nommage cohérent'],
    conseil: 'Illustrator « Export for Screens » exporte 20 tailles en 5 secondes. Utilise-le.',
  }),
  ...etape('2. EXPORT JPG (fond blanc)', {
    objectif: 'JPG pour print et docs officiels (fond obligatoirement blanc)',
    temps: '15 min',
    ou: 'Illustrator export',
    actions: [
      'Formats : JPG 2000px + 500px (rarement + petit)',
      'Fond blanc',
      'Qualité 90-95%',
      'Espace couleurs : RGB pour web, CMYK pour print (2 versions séparées)',
    ],
    resultat: 'JPG livrables.',
    verification: ['Fond blanc', 'Qualité 90%+', 'RGB + CMYK'],
    conseil: 'JPG CMYK pour print = obligatoire. Sinon l\'imprimeur devinera.',
  }),
  ...finalCheck(['PNG 5 tailles fond transparent', 'JPG 2 tailles fond blanc', 'RGB + CMYK', 'Nommage cohérent']),
  ...qaCheck(['PNG fond transparent ?', 'JPG CMYK pour print ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Convention nommage exports raster',
      prompt: 'Propose convention nommage claire pour exports raster logo : formats (PNG transparent / JPG blanc), tailles (2000/1000/500/200/64), espaces (RGB/CMYK). Format : liste exemples + règle.' },
  ]),
  ...conseilsSenior([
    'PNG transparent + JPG blanc = 2 formats obligatoires.',
    'CMYK pour print. Sinon l\'imprimeur devine (mal).',
    'Export for Screens (Illustrator) = 10x plus rapide qu\'export manuel.',
  ]),
  ...validationFinale('PNG + JPG multi-tailles livrables.', 'Dossier « Raster » dans Projet → Ressources'),
  ...escalade('Imprimeur refuse PNG (demande PDF vectoriel)', 'Ajouter export PDF vectoriel dans la livraison'),
]

/* ─── MOCKUPS PRÉSENTATION ────────────────────────────────────────────── */
const SOP_MOCKUPS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer 5-8 mockups de présentation pour livraison finale (WOW effect + usage réel)',
    resultat: 'Mockups HD imprimables + digitaux montrant logo en contexte réel',
    delai: '3-4 h',
    canal: CANAL,
    regle: 'Mockups = fin de projet, pas milieu. Sinon client bloque sur détails.',
    prerequis: ['Logo final signé', 'Version couleur + N/B'],
  }),
  ...projectContext(['client.company']),
  h2('Étapes'),
  ...etape('1. SÉLECTION 5-8 MOCKUPS PERTINENTS', {
    objectif: 'Choisir contextes réels du client (pas générique)',
    temps: '30 min',
    ou: 'Envato / Freepik / Cover Actions Pro',
    actions: [
      'Mockup 1 : carte de visite',
      'Mockup 2 : entête site web (fenêtre navigateur)',
      'Mockup 3 : t-shirt / uniforme',
      'Mockup 4 : signalétique / vitrine',
      'Mockup 5 : réseaux sociaux (avatar + couverture)',
      'Ajoute 2-3 mockups spécifiques métier (ex resto = menu, cabinet = tampon)',
    ],
    resultat: 'Liste 5-8 mockups sélectionnés.',
    verification: ['Contextes réels métier', 'Mix print + digital'],
    conseil: 'Mockup métier-spécifique impressionne toujours plus que le générique.',
  }),
  ...etape('2. APPLICATION LOGO + FINALISATION', {
    objectif: 'Intégrer le logo proprement dans chaque mockup',
    temps: '2-3 h',
    ou: 'Photoshop (mockups PSD avec smart objects)',
    actions: [
      'Ouvre mockup PSD → clic droit sur smart object logo → Edit Contents',
      'Colle logo vectoriel (SVG ou AI)',
      'Sauvegarde → mockup se met à jour auto',
      'Vérifie proportions + couleurs correctes',
      'Export JPG HD (max 2500px largeur)',
    ],
    resultat: '5-8 mockups finaux.',
    verification: ['Logo bien intégré', 'Proportions correctes', 'Export JPG HD'],
    conseil: 'Smart objects = magie. Modifie une fois, tout se met à jour.',
  }),
  ...etape('3. DECK PRÉSENTATION FINALE', {
    objectif: 'Compiler dans PDF présentation pour livraison',
    temps: '45 min',
    ou: 'Figma / Keynote / InDesign',
    actions: [
      'Format PDF A4 landscape',
      '1 mockup par page + phrase courte',
      'Couverture + slide fin « Merci » avec coordonnées client',
      'Nom : « Présentation_Logo_[Client].pdf »',
      'Archive dans Projet → Ressources / Presentation',
    ],
    resultat: 'PDF présentation prêt.',
    verification: ['A4 landscape', '5-8 mockups', 'Couverture + fin'],
    conseil: 'Le PDF de présentation est le souvenir que le client garde de toi. Investis-le.',
  }),
  ...finalCheck(['5-8 mockups pertinents', 'PDF présentation A4 landscape', 'Mockups métier-spécifiques', 'Archive livrable']),
  ...qaCheck(['Mockups adaptés au métier ?', 'Logo bien intégré (proportions) ?', 'PDF présentable ?']),
  ...promptCards([
    { agent: 'Gemini', title: 'Propose 8 mockups pertinents pour un secteur',
      prompt: 'Client est [SECTEUR] au Maroc. Propose 8 mockups pertinents pour présenter son nouveau logo : 4 génériques (business card, site web, t-shirt, réseaux), 4 spécifiques métier. Justifie chaque choix en 1 phrase.' },
  ]),
  ...conseilsSenior([
    'Mockups métier-spécifiques > génériques. Investis 30 min à les choisir.',
    'Smart objects PSD = productivité × 10.',
    'PDF présentation = ta signature. Investis-le.',
  ]),
  ...validationFinale('PDF présentation 5-8 mockups livrable.', 'Fichier « Presentation_Logo_[Client].pdf » dans Projet → Ressources'),
  ...escalade('Aucun mockup métier trouvé', 'Directeur créa — création mockup custom'),
]

/* ─── REMISE CLIENT + FORMATION USAGE ─────────────────────────────────── */
const SOP_REMISE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Remettre le pack complet + former le client à bien utiliser son logo',
    resultat: 'Client reçoit + signe accusé + comprend les règles d\'usage',
    delai: '1 h visio + envoi pack',
    canal: CANAL,
    regle: 'Sans formation usage, le logo est mal utilisé dans les 30 jours.',
    prerequis: ['Pack complet prêt (vectoriels + raster + charte + mockups + favicon)'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. PACK LIVRAISON STRUCTURÉ', {
    objectif: 'Organiser tous les fichiers dans une arborescence claire',
    temps: '30 min',
    ou: 'Projet → Ressources',
    actions: [
      'Dossier racine : « [Client] - Identité visuelle »',
      'Sous-dossiers : 1_Vectoriels / 2_Raster / 3_Favicon / 4_Charte / 5_Mockups / 6_Presentation',
      'ZIP compressé du dossier complet',
      'Poids ZIP < 50 Mo idéalement (sinon lien téléchargement)',
    ],
    resultat: 'Pack ZIP prêt.',
    verification: ['Arborescence claire', 'ZIP < 50 Mo ou lien'],
    conseil: 'Une arborescence claire = client autonome. Investis-la.',
  }),
  ...etape('2. VISIO REMISE + FORMATION 30 MIN', {
    objectif: 'Faire visite guidée du pack et former usage',
    temps: '30 min',
    ou: 'Visio (lien dans Projet → Documentation)',
    actions: [
      'Ouvre le pack en partage écran',
      'Explique chaque dossier',
      'Démontre : « pour print → utilise AI ou JPG CMYK », « pour web → utilise SVG ou PNG transparent »',
      'Rappelle les usages INTERDITS (charte page 5)',
      'Enregistre la visio (le client la reverra plus tard)',
    ],
    resultat: 'Formation faite + enregistrée.',
    verification: ['Client comprend arborescence', 'Sait quel fichier utiliser quand', 'Visio enregistrée'],
    conseil: 'La visio-formation vaut 100× l\'email « voici le pack ».',
  }),
  ...etape('3. ACCUSÉ RÉCEPTION + CLÔTURE PROJET', {
    objectif: 'Faire signer réception + fermer le projet officiellement',
    temps: '15 min',
    ou: 'Projet → Discussion',
    actions: [
      'Envoie ZIP + PDF présentation',
      'Message : « Voici le pack complet + PDF présentation. Merci d\'accuser réception et confirmer que tout est OK »',
      'Attend accusé « bien reçu, tout OK »',
      'Clôture projet dans l\'ERP',
      'Programme un follow-up à 3 mois (task ERP récurrente)',
    ],
    resultat: 'Projet clôturé.',
    verification: ['Accusé réception écrit', 'Projet marqué « Terminé » ERP', 'Follow-up 3 mois programmé'],
    conseil: 'Le follow-up à 3 mois = opportunité de vendre suite (papeterie, site web, autres déclinaisons).',
  }),
  ...finalCheck(['Pack ZIP structuré', 'Visio formation 30 min faite', 'Accusé réception écrit', 'Projet clôturé ERP', 'Follow-up 3 mois programmé']),
  ...qaCheck(['Le client sait-il quel fichier utiliser quand ?', 'Accusé de réception écrit ?', 'Projet marqué terminé ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Structure formation client 30 min',
      prompt: 'Rédige plan formation client 30 min pour usage logo. Sections : (1) Arborescence pack, (2) Print vs web (quel format quand), (3) Interdits critiques (charte page 5), (4) Q/A. Ton : direct, pédagogique, non-designer doit comprendre. Format : script minute par minute.' },
  ]),
  ...conseilsSenior([
    'La formation usage vaut 100× l\'email « voici le pack ».',
    'Enregistre la visio — le client la reverra dans 6 mois.',
    'Follow-up 3 mois = pipeline commercial gratuit.',
    'Accusé de réception écrit = clôture propre.',
  ]),
  ...validationFinale('Pack livré, formation faite, accusé écrit, projet clôturé.', 'Message accusé dans Projet → Discussion'),
  ...escalade('Client ne répond pas 7 jours après livraison', 'Chef de projet — relance formelle'),
]

/* ═══════════════════════════════════════════════════════════════════════ */

export const SOP_INDEX_LOGO: Record<string, SopBlock[]> = {
  [norm('Brief créatif client')]:              SOP_BRIEF,
  [norm('Recherche concurrence')]:             SOP_CONCURRENCE,
  [norm('Moodboard / inspirations')]:          SOP_MOODBOARD,
  [norm('Croquis 3 propositions')]:            SOP_CROQUIS,
  [norm('Présentation client')]:               SOP_PRESENTATION,
  [norm('Itérations / corrections')]:          SOP_ITERATIONS,
  [norm('Validation finale')]:                 SOP_VALIDATION,
  [norm('Logo couleur / noir / blanc')]:       SOP_DECLINAISONS_COULEUR,
  [norm('Logo horizontal + carré')]:           SOP_HORIZONTAL_CARRE,
  [norm('Favicon')]:                            SOP_FAVICON,
  [norm('Charte graphique PDF')]:              SOP_CHARTE,
  [norm('Fichiers vectoriels (AI / SVG)')]:    SOP_VECTORIELS,
  [norm('Fichiers PNG / JPG (HD + web)')]:     SOP_RASTER,
  [norm('Mockups de présentation')]:           SOP_MOCKUPS,
  [norm('Remise client + formation usage')]:   SOP_REMISE,
}
