/**
 * SOP — Site WordPress (44 tâches)
 * Rôle : Expert WordPress Senior — 30+ ans, WooCommerce Certified, Elementor Pro.
 */
import type { SopBlock } from '@/hooks/useSops'
import {
  introExpert, etape, finalCheck, qaCheck, promptCards,
  conseilsSenior, validationFinale, escalade, projectContext, h2,
} from './sopHelpers'

const norm = (s: string) => (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim()
const ROLE = 'Expert WordPress Senior — 30+ ans, WooCommerce Certified, migrations Hostinger/o2switch, 500+ sites'
const CANAL = 'Blocage → Projet → Discussion (canal Dev/WordPress)'

/* ─── COLLECTE INFOS (6 tâches → 2 SOPs partagés) ─────────────────────── */
const SOP_COLLECTE_IDENTITE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Récupérer les infos identité de l\'entreprise (nom, logo, couleurs, coords, réseaux)',
    resultat: 'Fiche projet complète dans Projet → Vue d\'ensemble + Ressources',
    delai: '45 min',
    canal: CANAL,
    regle: 'Auto-fill depuis fiche projet ERP. Si manquant → bouton « Compléter ».',
    prerequis: ['Client accessible', 'Accès Projet → Vue d\'ensemble'],
  }),
  ...projectContext(['client.name', 'client.company', 'client.email', 'client.phone']),
  h2('Étapes'),
  ...etape('1. FORMULAIRE INFOS + FICHIERS', {
    objectif: 'Rassembler nom, logo, couleurs, coords, services, réseaux sociaux',
    temps: '30 min',
    ou: 'Projet → Vue d\'ensemble + Projet → Ressources',
    actions: [
      'Vérifier auto-remplissage : nom, email, tel via fiche projet',
      'Uploader logo HD dans Projet → Ressources / Logo (SVG + PNG transparent)',
      'Noter couleurs HEX principales dans Projet → Documentation',
      'Adresse complète (rue + ville + code postal + pays)',
      'Réseaux sociaux : URLs complètes Facebook / Instagram / LinkedIn / TikTok',
      'Services : liste 5-10 principaux dans Projet → Documentation',
    ],
    resultat: 'Fiche complète.',
    verification: ['Logo uploadé HD', 'Couleurs HEX', 'Adresse complète', 'URLs réseaux'],
    conseil: 'SVG logo obligatoire — permet redimensionnement sans perte.',
  }),
  ...finalCheck(['Nom + logo + couleurs', 'Coords complètes', 'Réseaux + services', 'Archivé Projet → Ressources']),
  ...qaCheck(['Logo en SVG ?', 'HEX précis (pas approximatifs) ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Extract HEX depuis logo',
      prompt: 'Voici description couleurs logo : [DESCRIPTION]. Extrait 3-5 codes HEX précis (primaire, secondaire, accent, neutre). Sortie tableau avec proposition variations claires/foncées.' },
  ]),
  ...conseilsSenior([
    'SVG logo obligatoire.',
    'HEX précis, pas « bleu ».',
    'Auto-fill = zéro doublon manuel.',
  ]),
  ...validationFinale('Infos identité complètes archivées.', 'Projet → Vue d\'ensemble + Ressources'),
  ...escalade('Client n\'a pas de logo', 'Créer projet identité visuelle en amont'),
]

const SOP_COLLECTE_SERVICES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Structurer liste services + infos utiles pour intégration site',
    resultat: 'Liste services structurée + descriptions + prix + FAQ',
    delai: '30 min',
    canal: CANAL,
    regle: 'Sans descriptions structurées, le développement bloque.',
    prerequis: ['Client accessible'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. STRUCTURATION SERVICES', {
    objectif: 'Chaque service = fiche standardisée',
    temps: '30 min',
    ou: 'Projet → Documentation',
    actions: [
      'Pour chaque service : Nom | Description 100 mots | Prix | Durée | CTA',
      'Ajoute FAQ 3-5 questions par service',
      'Documente USPs (unique selling points)',
      'Ajoute témoignages clients si dispo',
    ],
    resultat: 'Liste services complète.',
    verification: ['5 champs par service', 'FAQ présente'],
    conseil: 'Un service sans FAQ = signal manque de maturité.',
  }),
  ...finalCheck(['5 champs par service', 'FAQ 3-5 questions', 'USPs identifiés']),
  ...qaCheck(['FAQ pertinente ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Structure liste services',
      prompt: 'Voici notes brutes sur services client [SECTEUR] : [COLLE]. Structure en tableau : Nom | Description 100 mots | Prix | Durée | CTA | FAQ (3 questions). Ton commercial.' },
  ]),
  ...conseilsSenior([
    'FAQ dès la conception, pas après.',
    'USPs différencient de concurrents.',
  ]),
  ...validationFinale('Services structurés prêts pour intégration.', 'Projet → Documentation'),
  ...escalade('Client hésite sur prix', 'Sortir de scope tarification'),
]

/* ─── MAQUETTE (3 tâches → 1 SOP maître) ──────────────────────────────── */
const SOP_MAQUETTE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Concevoir maquette UI dans Figma / XD couvrant home + 3 pages types',
    resultat: 'Fichier Figma partagé, maquettes desktop + mobile, validation client écrite',
    delai: '2-3 jours',
    canal: CANAL,
    regle: 'Aucune ligne de code avant validation écrite de la maquette.',
    prerequis: ['Infos identité + services collectés', 'Charte graphique OK'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. WIREFRAME + STRUCTURE', {
    objectif: 'Squelette pages avant design',
    temps: '4-6 h',
    ou: 'Figma',
    actions: [
      'Pages : Home + Services + Contact + À propos + Blog',
      'Wireframe basse-fidélité chaque page (blocs + hiérarchie)',
      'Structure : Header + Hero + Contenu principal + Footer',
      'Version mobile ⚠ mobile-first',
    ],
    resultat: 'Wireframes 5 pages.',
    verification: ['Desktop + mobile', 'Header/footer cohérents', 'Hiérarchie claire'],
    conseil: 'Wireframe > design. Force la clarté structurelle.',
  }),
  ...etape('2. DESIGN HAUTE FIDÉLITÉ', {
    objectif: 'Design final couleurs + typos + interactions',
    temps: '1-2 jours',
    ou: 'Figma',
    actions: [
      'Palette couleurs strict (charte graphique)',
      '2 typos max (titre + corps)',
      'Boutons cohérents (radius, states hover/focus)',
      'Composants réutilisables (buttons, cards, forms)',
      'Design system dans Figma (couleurs + typos + composants)',
    ],
    resultat: 'Design haute-fidélité.',
    verification: ['Design system Figma', '2 typos max', 'Composants cohérents'],
    conseil: 'Design system Figma = -50% temps développement.',
  }),
  ...etape('3. PRÉSENTATION + VALIDATION ÉCRITE', {
    objectif: 'Faire signer avant dev',
    temps: '1 h',
    ou: 'Visio + Projet → Discussion',
    actions: [
      'Visio 45 min : présentation maquette + Q/A',
      'Notez retours en direct',
      'Applique correctifs mineurs',
      'Signature écrite « ok pour dev »',
    ],
    resultat: 'Validation écrite.',
    verification: ['Visio tenue', 'Signature écrite'],
    conseil: 'Signature écrite = protection future.',
  }),
  ...finalCheck(['Wireframes desktop + mobile', 'Design haute fidélité', 'Design system Figma', 'Signature écrite']),
  ...qaCheck(['Mobile-first respecté ?', 'Signature écrite ?']),
  ...promptCards([
    { agent: 'Gemini', title: 'Suggère composants Figma manquants',
      prompt: 'Voici pages à designer : [LISTE]. Propose 15 composants Figma à créer pour design system : buttons, cards, forms, headers, etc. Chaque composant : nom + variants + états.' },
  ]),
  ...conseilsSenior([
    'Wireframe > design. Force la clarté.',
    'Design system Figma = économie temps massif.',
    'Signature écrite non négociable.',
  ]),
  ...validationFinale('Maquette validée par écrit prête pour dev.', 'Lien Figma dans Projet → Ressources'),
  ...escalade('Client refuse de valider', 'Chef de projet — recadrage brief'),
]

/* ─── DOMAINE & HÉBERGEMENT (3 tâches → 2 SOPs) ───────────────────────── */
const SOP_DOMAINE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Réserver ou transférer nom de domaine + configurer DNS',
    resultat: 'Domaine actif, DNS pointant vers hébergement, WHOIS masqué',
    delai: '30 min réservation + 24-48h propagation',
    canal: CANAL,
    regle: 'Domaine au nom du CLIENT, jamais de l\'agence.',
    prerequis: ['Registrar choisi (Hostinger / Namecheap / OVH)'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. RÉSERVATION OU TRANSFERT', {
    objectif: 'Domaine sécurisé au nom client',
    temps: '15 min',
    ou: 'Registrar (Hostinger recommandé Maroc)',
    actions: [
      'Vérifier disponibilité via WHOIS (whois.com)',
      'Réservation : compte client → paie avec sa carte',
      'Ajouter privacy WHOIS (masque coordonnées)',
      'Locker le domaine (empêche transfert non autorisé)',
      'Auto-renew ON',
    ],
    resultat: 'Domaine réservé.',
    verification: ['WHOIS masqué', 'Locker ON', 'Auto-renew ON'],
    conseil: 'Le client paie, tu conseilles. Jamais l\'inverse.',
  }),
  ...etape('2. CONFIGURATION DNS', {
    objectif: 'Pointer vers hébergement',
    temps: '15 min',
    ou: 'Registrar → DNS',
    actions: [
      'Récupérer nameservers hébergement (Hostinger : ns1.dns-parking.com, ns2...)',
      'Registrar → DNS → remplacer nameservers défaut',
      'Attendre propagation 24-48h (souvent < 2h)',
      'Vérifier via whatsmydns.net',
    ],
    resultat: 'DNS pointent vers hébergement.',
    verification: ['Nameservers modifiés', 'Propagation vérifiée'],
    conseil: 'Utilise Cloudflare intermédiaire = perf + sécurité gratuits.',
  }),
  ...finalCheck(['Domaine au nom client', 'WHOIS masqué + Lock + Auto-renew', 'DNS pointent vers hébergement', 'Propagation OK']),
  ...qaCheck(['Client est propriétaire ?', 'Propagation validée ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Explique DNS au client',
      prompt: 'Rédige explication client 5 lignes : rôle DNS, temps propagation 24-48h, pourquoi utiliser Cloudflare. Ton rassurant, sans jargon technique.' },
  ]),
  ...conseilsSenior([
    'Domaine au nom client, jamais agence.',
    'Cloudflare gratuit = perf + sécu.',
    'Auto-renew évite drames à N+1.',
  ]),
  ...validationFinale('Domaine actif + DNS propagés.', 'Section domaine dans Projet → Infos & Accès'),
  ...escalade('Propagation > 48h', 'Vérifier registrar + hébergeur — parfois cache DNS ISP'),
]

const SOP_HEBERGEMENT_SSL: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Configurer hébergement + installer SSL Let\'s Encrypt automatique',
    resultat: 'Hébergement actif, WordPress installable, HTTPS avec cadenas vert',
    delai: '1 h',
    canal: CANAL,
    regle: 'SSL avant installation WordPress. Sinon mixed content dès jour 1.',
    prerequis: ['Domaine avec DNS OK'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. CONFIGURATION HÉBERGEMENT', {
    objectif: 'Setup hébergement',
    temps: '30 min',
    ou: 'hPanel Hostinger / cPanel',
    actions: [
      'Choisir plan mutualisé (business ou premium selon trafic attendu)',
      'hPanel → Sites web → + Créer un site → domaine',
      'Configurer PHP 8.1+ (min 8.0)',
      'Base de données MySQL créée + user assigné',
      'Configurer email pro (voir SOP SMTP)',
    ],
    resultat: 'Hébergement prêt.',
    verification: ['PHP 8.1+', 'DB créée', 'Domaine associé'],
    conseil: 'PHP 8+ = perf x2 vs PHP 7.4. Non négociable.',
  }),
  ...etape('2. SSL LET\'S ENCRYPT', {
    objectif: 'HTTPS actif partout',
    temps: '30 min',
    ou: 'hPanel → SSL',
    actions: [
      'hPanel → SSL → activer Let\'s Encrypt (gratuit)',
      'Force HTTPS ON (redirect 301)',
      'Test https://[domaine] → cadenas vert',
      'SSL Labs (ssllabs.com) → viser A+',
      'HSTS activer si possible',
    ],
    resultat: 'HTTPS OK.',
    verification: ['Cadenas vert', 'SSL Labs A/A+', 'HSTS actif'],
    conseil: 'SSL Let\'s Encrypt renouvelé auto tous 90j. Vérifier Auto-renew.',
  }),
  ...finalCheck(['PHP 8.1+', 'DB MySQL créée', 'SSL Let\'s Encrypt actif', 'Force HTTPS', 'HSTS ON']),
  ...qaCheck(['Cadenas vert ?', 'SSL Labs A/A+ ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Debug SSL non-actif',
      prompt: 'SSL Let\'s Encrypt échoue avec erreur : [ERREUR]. Diagnostic : (1) DNS propagé ? (2) fichier .well-known accessible ? (3) rate limit LE ? (4) mixed content ? Sortie step-by-step résolution.' },
  ]),
  ...conseilsSenior([
    'PHP 8+ = perf x2.',
    'SSL avant install WP (mixed content).',
    'Cloudflare Universal SSL = backup si LE échoue.',
  ]),
  ...validationFinale('Hébergement + SSL actifs.', 'Section hébergement dans Projet → Infos & Accès'),
  ...escalade('SSL impossible à activer', 'Cloudflare Universal SSL alternative'),
]

/* ─── DÉVELOPPEMENT (5 tâches → 3 SOPs) ───────────────────────────────── */
const SOP_INSTALL_WP: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Installer WordPress + sécurité de base + configuration essentielle',
    resultat: 'WordPress fresh install, sécurisé, prêt pour thème + contenu',
    delai: '1 h',
    canal: CANAL,
    regle: 'JAMAIS user « admin ». Toujours user unique + mot de passe fort.',
    prerequis: ['Hébergement + SSL prêts', 'DB MySQL'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. INSTALL VIA HPANEL OU MANUEL', {
    objectif: 'WordPress installé',
    temps: '15 min',
    ou: 'hPanel → Installateur WordPress',
    actions: [
      'hPanel → Auto Installer → WordPress → installer',
      'Titre site + tagline + email admin (email pro client)',
      'User : jamais « admin » — utiliser prénom-role (ex « said-admin »)',
      'Mot de passe : générer 20+ chars via 1Password',
      'Attendre installation (2-3 min)',
    ],
    resultat: 'WordPress installé.',
    verification: ['User ≠ admin', 'Password 20+ chars', 'HTTPS auto'],
    conseil: '« admin » = première tentative des bots. Change-le.',
  }),
  ...etape('2. SÉCURITÉ + CONFIGURATION', {
    objectif: 'Hardening + settings de base',
    temps: '30 min',
    ou: 'WP Admin',
    actions: [
      'Réglages → Permaliens → « Nom de l\'article » (pour SEO)',
      'Utilisateurs → Ajouter admin secondaire (backup)',
      'Réglages → Discussion → désactiver pingbacks/trackbacks (spam)',
      'Installer plugin Wordfence + activer scan quotidien',
      'wp-config.php : ajouter DISALLOW_FILE_EDIT true',
    ],
    resultat: 'Site sécurisé.',
    verification: ['Permaliens SEO', 'Wordfence actif', 'DISALLOW_FILE_EDIT'],
    conseil: 'DISALLOW_FILE_EDIT bloque l\'édition thème/plugin via Admin = -50% risque hack.',
  }),
  ...etape('3. NETTOYAGE + BACKUP INITIAL', {
    objectif: 'Enlever ce qui traîne + premier backup',
    temps: '15 min',
    ou: 'WP Admin',
    actions: [
      'Supprimer thèmes défaut inutilisés',
      'Supprimer plugins Hello Dolly, Akismet (si non utilisé)',
      'Vider articles/pages defaut',
      'Installer UpdraftPlus → premier backup complet vers Dropbox/GDrive',
    ],
    resultat: 'Site propre + backup.',
    verification: ['Thèmes/plugins nettoyés', 'Backup réussi'],
    conseil: 'UpdraftPlus gratuit + backups auto = filet de sécurité vital.',
  }),
  ...finalCheck(['WordPress installé', 'User ≠ admin + password 20+', 'Wordfence + DISALLOW_FILE_EDIT', 'Backup initial UpdraftPlus']),
  ...qaCheck(['User admin renommé ?', 'Backup fonctionne ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Config wp-config.php sécurisée',
      prompt: 'Génère wp-config.php sécurisé avec : DB creds env vars, SALTS aléatoires, DISALLOW_FILE_EDIT, FORCE_SSL_ADMIN, WP_DEBUG_LOG only local, WP_MEMORY_LIMIT 512M. Sortie code prêt à coller.' },
  ]),
  ...conseilsSenior([
    'User « admin » = première cible bots.',
    'DISALLOW_FILE_EDIT = protection critique.',
    'UpdraftPlus dès jour 1.',
  ]),
  ...validationFinale('WordPress installé + sécurisé + backup.', 'Section WP dans Projet → Infos & Accès'),
  ...escalade('Erreur installation', 'Vérifier DB creds + PHP version'),
]

const SOP_THEME_HEADER: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Installer et personnaliser thème + Header/Footer/Menus selon maquette',
    resultat: 'Thème actif, Header/Footer aligné maquette, menus configurés',
    delai: '1-2 jours',
    canal: CANAL,
    regle: 'Utilise thème mainstream (Astra / Kadence / GeneratePress). Jamais nulled.',
    prerequis: ['Maquette Figma validée'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. THÈME + CHILD THEME', {
    objectif: 'Thème installé propre',
    temps: '1 h',
    ou: 'WP Admin → Apparence',
    actions: [
      'Choisir thème : Astra / Kadence / GeneratePress (light + flexible)',
      'Installer + activer',
      'Créer child theme (WPCode plugin ou manuel FTP)',
      'Activer child theme pour permettre customs sans casser update',
    ],
    resultat: 'Thème + child actifs.',
    verification: ['Child theme actif', 'Thème mainstream'],
    conseil: 'Child theme obligatoire. Sans, tes customs sautent au 1er update.',
  }),
  ...etape('2. HEADER / FOOTER / MENUS', {
    objectif: 'Structure identique maquette',
    temps: '1 jour',
    ou: 'Personnaliser (Customizer) + Elementor',
    actions: [
      'Header : logo + menu principal + CTA (voir maquette)',
      'Footer : coordonnées + réseaux + mentions légales',
      'Menus (WP Admin → Apparence → Menus) : structure hiérarchique',
      'Sticky header optionnel selon maquette',
      'Test mobile hamburger menu',
    ],
    resultat: 'Structure alignée maquette.',
    verification: ['Header/footer conformes', 'Menus fonctionnels', 'Mobile OK'],
    conseil: 'Sticky header desktop, hamburger mobile. Standard 2024.',
  }),
  ...finalCheck(['Thème mainstream + child', 'Header + Footer conformes maquette', 'Menus configurés', 'Mobile testé']),
  ...qaCheck(['Child theme actif ?', 'Mobile hamburger fonctionne ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Créer child theme automatique',
      prompt: 'Créer child theme WordPress pour parent thème [NOM]. Génère : style.css avec Template header + functions.php avec enqueue parent + child. Sortie code prêt à uploader dans /wp-content/themes/[parent]-child/.' },
  ]),
  ...conseilsSenior([
    'Child theme = protection updates.',
    'Astra / Kadence / GeneratePress = trinité 2024.',
    'Jamais de thème nulled — malware garanti.',
  ]),
  ...validationFinale('Thème installé + structure alignée maquette.', 'Screenshot avant/après dans Projet → Documentation'),
  ...escalade('Client fournit thème non-mainstream', 'Négocier alternative — nulled = danger'),
]

const SOP_PAGES_FONCTIONNALITES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer toutes les pages + intégrer fonctionnalités demandées',
    resultat: 'Pages home / services / contact / à propos / blog + fonctionnalités custom',
    delai: '3-5 jours',
    canal: CANAL,
    regle: 'Utilise page builder (Elementor / Bricks) pour vitesse + maintenance.',
    prerequis: ['Thème + Header/Footer OK', 'Contenus prêts'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. PAGES PRINCIPALES', {
    objectif: 'Home + Services + Contact + À propos + Blog',
    temps: '2-3 jours',
    ou: 'Elementor Pro / Bricks',
    actions: [
      'Home : Hero + Services + Témoignages + CTAs',
      'Services : listing + détail (custom post type si multiple)',
      'Contact : formulaire + Google Maps + coordonnées',
      'À propos : histoire + équipe + valeurs',
      'Blog : listing articles + template article single',
    ],
    resultat: '5 pages principales.',
    verification: ['5 pages créées', 'Design maquette respecté'],
    conseil: 'Elementor Pro = standard. Bricks pour perf max.',
  }),
  ...etape('2. FONCTIONNALITÉS CUSTOM', {
    objectif: 'Selon brief (booking, WooCommerce, LMS, membership)',
    temps: '1-2 jours selon complexité',
    ou: 'Plugins',
    actions: [
      'Booking : Amelia / Bookly',
      'E-commerce : WooCommerce + WooPayments',
      'LMS : LearnDash / LifterLMS',
      'Membership : MemberPress / Restrict Content Pro',
      'Custom : ACF (Advanced Custom Fields) pour métadonnées',
    ],
    resultat: 'Fonctionnalités actives.',
    verification: ['Selon brief', 'Test bout-en-bout'],
    conseil: 'Toujours plugin premium payé (support + updates). Nulled = danger.',
  }),
  ...finalCheck(['5 pages principales', 'Fonctionnalités selon brief', 'Test bout-en-bout', 'Design maquette respecté']),
  ...qaCheck(['Cohérence design ?', 'Aucun plugin nulled ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Génère template Elementor JSON',
      prompt: 'Rédige structure JSON export Elementor pour page [TYPE] : sections + colonnes + widgets. Base sur maquette Figma [DESCRIPTION]. Directement importable.' },
  ]),
  ...conseilsSenior([
    'Elementor Pro standard, Bricks pour perf.',
    'Plugins premium uniquement.',
    'ACF = pilier des sites complexes.',
  ]),
  ...validationFinale('Pages + fonctionnalités opérationnelles.', 'Preview dans Projet → Discussion'),
  ...escalade('Fonctionnalité impossible avec plugins standards', 'Dev custom avec devis séparé'),
]

/* ─── CONTENU (3 tâches → 2 SOPs) ─────────────────────────────────────── */
const SOP_CONTENU: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger + intégrer contenus SEO-friendly + optimiser CTAs',
    resultat: 'Chaque page a contenu 500+ mots optimisé + CTA visible above the fold',
    delai: '2-3 jours',
    canal: CANAL,
    regle: 'Zero lorem ipsum en production. Chaque mot doit être final.',
    prerequis: ['Pages créées', 'Mots-clés SEO définis'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. RÉDACTION SEO', {
    objectif: 'Contenus optimisés',
    temps: '2 jours',
    ou: 'Projet → Documentation + WP Admin',
    actions: [
      'Home : 800-1200 mots avec KW principal',
      'Services : 500-800 mots par service',
      'Contact + À propos : 300-500 mots',
      'Intègre H1/H2/H3 selon SOP SEO Balises',
      'Meta title + meta desc par page (voir SOP SEO)',
    ],
    resultat: 'Contenus intégrés.',
    verification: ['Word count minimum', 'Structure H', 'Meta title + desc'],
    conseil: 'IA aide beaucoup mais relis toujours pour ton + accuracy.',
  }),
  ...etape('2. CTAS + PARCOURS UTILISATEUR', {
    objectif: 'CTAs visibles et cohérents',
    temps: '1 jour',
    ou: 'Elementor',
    actions: [
      'CTA principal : bouton coloré, visible above the fold',
      'CTAs secondaires en cours de page',
      'Sticky WhatsApp / Call button mobile',
      'Chaque page = 1 objectif conversion clair',
      'Test heat map (Hotjar) après lancement',
    ],
    resultat: 'CTAs stratégiques.',
    verification: ['CTA above the fold', 'Sticky mobile', '1 objectif par page'],
    conseil: 'CTA above the fold = 3× plus de clics.',
  }),
  ...finalCheck(['Contenus 500+ mots par page', 'H1/H2/H3 structurés', 'CTAs above the fold', 'Sticky mobile']),
  ...qaCheck(['Aucun lorem ipsum ?', 'Meta title/desc partout ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige page service SEO',
      prompt: 'Rédige page service « [SERVICE] » pour [CLIENT SECTEUR]. Contraintes : 500-800 mots, KW principal « [KW] », structure H1/H2/H3, CTA « [CTA] ». Ton : [TON]. Sortie Markdown.' },
    { agent: 'Claude Code', title: 'Vérifie densité KW',
      prompt: 'Voici contenu page : [COLLE]. Calcule densité KW « [KW] » (idéal 1-2%). Alerte si stuffing (>3%). Suggère variations si sous-optimisée.' },
  ]),
  ...conseilsSenior([
    'IA aide, humain relit toujours.',
    'CTA above the fold non négociable.',
    'Sticky WhatsApp mobile au Maroc = +30% conv.',
  ]),
  ...validationFinale('Contenus + CTAs optimisés.', 'Preview dans Projet → Discussion'),
  ...escalade('Client refuse de fournir contenus', 'Facturer rédaction contenus séparément'),
]

const SOP_IMAGES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Optimiser toutes images du site : WebP + lazy loading + alt texts',
    resultat: 'Toutes images en WebP, lazy loading actif, alt texts renseignés, LCP < 2.5s',
    delai: '2-3 h',
    canal: CANAL,
    regle: 'Une image non optimisée = LCP cassé = SEO cassé.',
    prerequis: ['Images uploadées'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. CONVERSION WEBP + COMPRESSION', {
    objectif: 'Toutes images en WebP < 300 Ko',
    temps: '1 h',
    ou: 'Plugin ShortPixel / WebP Express / TinyPNG',
    actions: [
      'Installer plugin ShortPixel (recommandé)',
      'Bulk convert toutes images existantes → WebP',
      'Config compression : lossy 80% (invisible visuellement)',
      'Redimensionner : max largeur 1920 px',
      'Vérifier taille : < 300 Ko par image idéal',
    ],
    resultat: 'Images WebP compressées.',
    verification: ['WebP servi', 'Taille < 300 Ko', 'Redimensionné'],
    conseil: 'ShortPixel = référence 2024. Compare avec original avant validation.',
  }),
  ...etape('2. LAZY LOADING + ALT TEXTS', {
    objectif: 'Perf + SEO + accessibilité',
    temps: '1-2 h',
    ou: 'WP Admin + code',
    actions: [
      'Lazy loading natif WordPress 5.5+ (déjà actif)',
      'EXCLURE LCP image du lazy (au-dessus du fold)',
      'Alt texts : Media Library → chaque image → alt descriptif + KW naturel',
      'Voir SOP SEO Alt texts pour détails',
    ],
    resultat: 'Lazy + alt OK.',
    verification: ['LCP image sans lazy', 'Alts renseignés'],
    conseil: 'Lazy sur LCP image = pénalité SEO. Toujours exclure.',
  }),
  ...finalCheck(['Toutes images en WebP', 'Compression < 300 Ko', 'Lazy actif (sauf LCP)', 'Alts renseignés']),
  ...qaCheck(['LCP < 2.5s après ?', 'Alts descriptifs ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Config ShortPixel optimale',
      prompt: 'Config ShortPixel plugin WordPress pour site avec [X] images. Recommandations : (1) mode compression (glossy/lossy/lossless), (2) WebP + AVIF, (3) redimensionnement max, (4) exclude patterns pour LCP images. Sortie config JSON.' },
  ]),
  ...conseilsSenior([
    'ShortPixel = référence.',
    'LCP image jamais lazy.',
    'WebP + AVIF = combo 2024.',
  ]),
  ...validationFinale('Images optimisées, LCP OK.', 'Rapport PSI dans Projet → Documentation'),
  ...escalade('LCP > 4s après optimisation', 'Audit critical CSS + serveur'),
]

/* ─── OPTIMISATION (3 tâches → 3 SOPs distincts) ──────────────────────── */
const SOP_RESPONSIVE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Assurer responsive parfait mobile / tablette / desktop',
    resultat: 'Site fluide sur 320px → 1920px, aucun overflow horizontal, touch-friendly',
    delai: '1 jour',
    canal: CANAL,
    regle: 'Test réel sur téléphone. Chrome DevTools ne suffit pas.',
    prerequis: ['Pages créées'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. TESTS TOUS BREAKPOINTS', {
    objectif: 'Vérifier 5 breakpoints critiques',
    temps: '4 h',
    ou: 'Chrome DevTools + Real Device Testing',
    actions: [
      'Breakpoints : 320px (iPhone SE), 375px (iPhone), 768px (tablet), 1024px, 1920px',
      'Chrome DevTools → Toggle Device Toolbar → tester chaque',
      'Test réel iPhone + Android (au moins 2 devices)',
      'BrowserStack si multi-devices nécessaires',
      'Note problèmes : overflow, boutons trop petits, texte illisible',
    ],
    resultat: 'Liste bugs responsive.',
    verification: ['5 breakpoints testés', '2 devices réels', 'Bugs listés'],
    conseil: 'iPhone SE (320px) = worst case. Si ça passe, tout passe.',
  }),
  ...etape('2. CORRECTIONS + RE-TEST', {
    objectif: 'Fix bugs identifiés',
    temps: '4 h',
    ou: 'Elementor / CSS custom',
    actions: [
      'Corriger dans Elementor (Responsive controls par device)',
      'CSS custom si nécessaire : @media queries',
      'Touch targets ≥ 48×48 px (Google recommandé)',
      'Font-size mobile ≥ 16 px (évite zoom auto iOS)',
      'Re-test après chaque fix',
    ],
    resultat: 'Bugs corrigés.',
    verification: ['0 overflow horizontal', 'Touch targets OK', 'Font mobile 16+'],
    conseil: 'Touch target < 48px = frustration mobile. Standard Google.',
  }),
  ...finalCheck(['5 breakpoints testés', '2+ devices réels', '0 overflow', 'Touch targets 48+', 'Font mobile 16+']),
  ...qaCheck(['iPhone SE testé ?', 'Aucun overflow horizontal ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Détecte problèmes responsive CSS',
      prompt: 'CSS actuel : [COLLE]. HTML : [COLLE]. Identifie problèmes responsive : (1) overflow-x possible, (2) font-size < 16 px mobile, (3) touch targets < 48px, (4) media queries manquantes. Sortie fix par fix.' },
  ]),
  ...conseilsSenior([
    'iPhone SE (320px) = worst case.',
    'Test réel > DevTools.',
    'Touch 48+ non négociable.',
  ]),
  ...validationFinale('Responsive parfait tous breakpoints.', 'Screenshots par device dans Projet → Documentation'),
  ...escalade('Impossible à corriger dans Elementor', 'CSS custom via child theme'),
]

const SOP_SEO_ON_PAGE_WP: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Optimisation SEO on-page WordPress avec RankMath',
    resultat: 'Chaque page indexable a title/meta/schema optimisés, sitemap OK',
    delai: '1 jour',
    canal: CANAL,
    regle: 'Voir SOP SEO On-Page pour détails. Ici : intégration WP.',
    prerequis: ['Contenus intégrés'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. INSTALL RANKMATH + CONFIG', {
    objectif: 'RankMath (préféré vs YOAST)',
    temps: '30 min',
    ou: 'WP Admin → Plugins',
    actions: [
      'Installer RankMath (free suffit pour commencer)',
      'Setup wizard : titre site + logo + réseaux sociaux',
      'Connexion RankMath account (analytics)',
      'Modules à activer : Analytics + Schema + Sitemap + Redirects',
    ],
    resultat: 'RankMath configuré.',
    verification: ['Modules actifs', 'Setup wizard OK'],
    conseil: 'RankMath > YOAST en 2024 (features gratuites plus complètes).',
  }),
  ...etape('2. OPTIMISATION PAGES', {
    objectif: 'Titles, meta, schemas par page',
    temps: '4 h',
    ou: 'WP Admin édition pages',
    actions: [
      'Chaque page : onglet SEO RankMath en bas',
      'Meta title (≤ 60 chars) + Meta description (≤ 155)',
      'KW principal renseigné',
      'Schema (Article, Product, LocalBusiness, FAQ selon page)',
      'Score RankMath ≥ 80 (mais pas 100 obsessif)',
    ],
    resultat: 'Pages optimisées.',
    verification: ['Meta title/desc partout', 'Schema pertinent', 'Score 80+'],
    conseil: 'Score 100 = souvent forcé. Vise 80+ authentique.',
  }),
  ...etape('3. SITEMAP + SEARCH CONSOLE', {
    objectif: 'Soumission Google',
    temps: '30 min',
    ou: 'RankMath + Search Console',
    actions: [
      'RankMath → Sitemap → vérifier /sitemap_index.xml',
      'Search Console → Sitemap → soumettre',
      'Attendre 24-48h indexation',
      'Voir SOP SEO Search Console pour détails',
    ],
    resultat: 'Sitemap soumis.',
    verification: ['Sitemap valide', 'SC statut « Réussi »'],
    conseil: 'Voir SOP SEO Search Console pour setup complet.',
  }),
  ...finalCheck(['RankMath configuré', 'Meta title/desc/schema par page', 'Sitemap soumis SC']),
  ...qaCheck(['Score RankMath 80+ ?', 'Schema pertinent ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Config RankMath optimale',
      prompt: 'Config RankMath idéale pour site [SECTEUR]. Modules : quels activer / désactiver ? Schema par page type. Sitemap : quoi inclure/exclure. Sortie recommandations structurées.' },
  ]),
  ...conseilsSenior([
    'RankMath > YOAST (2024).',
    'Score 80+ authentique > 100 forcé.',
    'Sitemap soumis SC dès mise en prod.',
  ]),
  ...validationFinale('SEO on-page OK, sitemap soumis.', 'Section SEO dans Projet → Documentation'),
  ...escalade('Google refuse indexation', 'Voir SOP SEO Search Console debug'),
]

const SOP_PERFORMANCES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Atteindre Core Web Vitals verts : LCP < 2.5s, CLS < 0.1, INP < 200ms',
    resultat: 'PageSpeed Insights ≥ 90 mobile, LCP OK sur 3 pages critiques',
    delai: '1 jour',
    canal: CANAL,
    regle: 'Mesurer avant/après. Sans mesure = pas de progrès.',
    prerequis: ['Site en prod'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. WP ROCKET + CLOUDFLARE', {
    objectif: 'Setup cache + CDN',
    temps: '2 h',
    ou: 'WP Admin + Cloudflare',
    actions: [
      'Installer WP Rocket (payant, référence 2024)',
      'Activer : cache, GZIP, lazy load, minify CSS/JS, defer JS',
      'Cloudflare gratuit : Add site → DNS pointés → activer',
      'Cloudflare : Auto Minify + Brotli + Rocket Loader (attention jQuery)',
    ],
    resultat: 'Cache + CDN actifs.',
    verification: ['WP Rocket ON', 'Cloudflare Cloud actif'],
    conseil: 'WP Rocket + Cloudflare = combo -70% temps chargement.',
  }),
  ...etape('2. CRITICAL CSS + FONTS', {
    objectif: 'LCP < 2.5s',
    temps: '2 h',
    ou: 'WP Rocket + config manuel',
    actions: [
      'WP Rocket → Remove Unused CSS ON',
      'Font-display: swap dans tous les Google Fonts',
      'Preload fonts critiques (font-family utilisée dans H1 hero)',
      'Perfmatters : disable emojis, embeds, dashicons frontend',
    ],
    resultat: 'LCP < 2.5s.',
    verification: ['PSI mobile 90+', 'LCP < 2.5s'],
    conseil: 'Critical CSS + preload fonts = LCP -1s facilement.',
  }),
  ...etape('3. BENCHMARKS AVANT/APRÈS', {
    objectif: 'Prouver le gain',
    temps: '30 min',
    ou: 'PageSpeed Insights',
    actions: [
      'Test 3 pages critiques (Home + Service + Contact)',
      'Screenshot PSI avant / après',
      'Note dans Projet → Documentation delta chiffré',
      'Field data (28j) prioritaire sur Lab data',
    ],
    resultat: 'Rapport perf.',
    verification: ['3 pages testées', 'Delta chiffré'],
    conseil: 'Field data > Lab data. Regarde 28 derniers jours.',
  }),
  ...finalCheck(['WP Rocket + Cloudflare actifs', 'Critical CSS + preload fonts', 'PSI 90+ mobile', 'Delta chiffré']),
  ...qaCheck(['LCP < 2.5s ?', 'PSI 90+ ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Diagnostic perf PSI',
      prompt: 'PSI rapport : [COLLE]. Top 5 optimisations priorité impact/effort : (1) LCP element, (2) render-blocking, (3) unused CSS/JS, (4) images non-optim, (5) fonts. Sortie plan action.' },
  ]),
  ...conseilsSenior([
    'WP Rocket + Cloudflare = combo standard.',
    'Critical CSS + preload = -1s facilement.',
    'Field data > Lab data.',
  ]),
  ...validationFinale('Core Web Vitals verts sur 3 pages.', 'Rapport PSI avant/après dans Projet → Documentation'),
  ...escalade('LCP > 4s malgré optimisations', 'Migration VPS + audit critique'),
]

/* ─── INTÉGRATIONS (8 tâches → 5 SOPs) ────────────────────────────────── */
const SOP_WHATSAPP_LIENS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Ajouter bouton WhatsApp flottant + intégrations liens réseaux',
    resultat: 'WhatsApp sticky mobile + desktop + liens réseaux fonctionnels',
    delai: '30 min',
    canal: CANAL,
    regle: 'WhatsApp au Maroc = canal #1. Non négociable.',
    prerequis: ['Tel client + URLs réseaux'],
  }),
  ...projectContext(['client.name', 'client.phone']),
  h2('Étapes'),
  ...etape('1. WHATSAPP FLOATING BUTTON', {
    objectif: 'Bouton visible mobile + desktop',
    temps: '20 min',
    ou: 'Plugin (Chaty / WhatsApp Chat) OU code manuel',
    actions: [
      'Option A - Plugin Chaty : install + config numéro + message pré-rempli',
      'Option B - Manuel : CSS custom bouton position:fixed bottom-right',
      'Message pré-rempli : « Bonjour, je viens du site [NOM]... »',
      'Icône WhatsApp officiel verte',
      'Position mobile : bottom-right ne bloque pas contenu',
    ],
    resultat: 'WhatsApp actif.',
    verification: ['Visible mobile + desktop', 'Message pré-rempli', 'Clic ouvre app WA'],
    conseil: 'Chaty gratuit suffit. Le clic direct sans landing = +80% conv.',
  }),
  ...etape('2. LIENS RÉSEAUX SOCIAUX', {
    objectif: 'Footer + section dédiée',
    temps: '10 min',
    ou: 'Elementor',
    actions: [
      'Footer : icônes réseaux avec liens (target=_blank)',
      'Utiliser icônes officielles (Font Awesome ou Elementor icons)',
      'Vérifier tous les liens ouvrent bien',
      'Ajouter rel="noopener noreferrer" pour sécurité',
    ],
    resultat: 'Réseaux liés.',
    verification: ['Tous liens fonctionnent', 'target=_blank + noopener'],
    conseil: 'noopener = sécurité obligatoire pour target=_blank.',
  }),
  ...finalCheck(['WhatsApp flottant mobile + desktop', 'Message pré-rempli', 'Réseaux liés footer', 'noopener sécurité']),
  ...qaCheck(['WhatsApp ouvre app ?', 'Liens réseaux OK ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Bouton WhatsApp custom CSS',
      prompt: 'Génère CSS + HTML pour bouton WhatsApp floating : position:fixed bottom-right, taille 60px, icône SVG officielle verte, hover effet, mobile-responsive. Include message pré-rempli via wa.me/[tel]?text=...' },
  ]),
  ...conseilsSenior([
    'WhatsApp au Maroc = canal #1.',
    'Message pré-rempli = friction -80%.',
    'noopener obligatoire target=_blank.',
  ]),
  ...validationFinale('WhatsApp + réseaux intégrés.', 'Screenshot dans Projet → Documentation'),
  ...escalade('WhatsApp Business API demandé', 'Setup séparé — SOP dédié'),
]

const SOP_FORMULAIRE_MAPS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Formulaire contact + Google Maps embed sur page contact',
    resultat: 'Formulaire fonctionnel avec captcha + Maps interactive',
    delai: '1 h',
    canal: CANAL,
    regle: 'Formulaire sans captcha = spam bots garantis.',
    prerequis: ['SMTP configuré'],
  }),
  ...projectContext(['client.name', 'client.email', 'client.company']),
  h2('Étapes'),
  ...etape('1. FORMULAIRE + CAPTCHA', {
    objectif: 'Formulaire propre + anti-spam',
    temps: '30 min',
    ou: 'WPForms / Fluent Forms / Contact Form 7',
    actions: [
      'Recommandé : WPForms (UX) OU Fluent Forms (perf)',
      'Champs : Nom + Email + Tel + Message',
      'reCAPTCHA v3 (invisible) OU Cloudflare Turnstile',
      'Destinataire email : configurer email client',
      'Merci page : redirect ou message inline',
    ],
    resultat: 'Formulaire fonctionnel.',
    verification: ['Test soumission', 'Captcha actif', 'Email reçu'],
    conseil: 'Cloudflare Turnstile > reCAPTCHA (privacy + UX).',
  }),
  ...etape('2. GOOGLE MAPS EMBED', {
    objectif: 'Localisation visible',
    temps: '30 min',
    ou: 'Google Maps embed',
    actions: [
      'Google Maps → recherche adresse → Partager → Intégrer une carte',
      'Copier iframe HTML',
      'Coller dans widget HTML Elementor',
      'Alternative : plugin WP Google Maps si multiple pins',
      'Attention : Google Maps embed sans clé = quota limité',
    ],
    resultat: 'Maps intégrée.',
    verification: ['Adresse correcte', 'Interactive'],
    conseil: 'OpenStreetMap alternative gratuite si quota Maps insuffisant.',
  }),
  ...finalCheck(['Formulaire fonctionnel + captcha', 'Test email reçu', 'Google Maps embed', 'Merci page']),
  ...qaCheck(['Captcha actif ?', 'Email reçu par client ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Config WPForms webhook',
      prompt: 'Config WPForms pour envoyer submissions vers webhook [URL] en plus de l\'email. Format JSON payload. Ajoute retry si 5xx. Sortie code + settings WPForms.' },
  ]),
  ...conseilsSenior([
    'Sans captcha = spam bots.',
    'Cloudflare Turnstile > reCAPTCHA.',
    'Confirm email avec test réel.',
  ]),
  ...validationFinale('Formulaire + Maps fonctionnels.', 'Test soumission dans Projet → Discussion'),
  ...escalade('Formulaire n\'envoie pas d\'emails', 'Voir SOP SMTP debug'),
]

const SOP_SMTP_EMAILS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Configurer SMTP externe + créer emails pros + tester envoi/réception',
    resultat: 'SMTP actif (Brevo/Postmark), emails pros créés, tests OK',
    delai: '2 h',
    canal: CANAL,
    regle: 'JAMAIS SMTP hébergeur par défaut. Toujours SMTP externe (délivrabilité).',
    prerequis: ['Accès DNS domaine', 'Compte SMTP externe'],
  }),
  ...projectContext(['client.name', 'domain', 'client.email']),
  h2('Étapes'),
  ...etape('1. CHOISIR + CONFIGURER SMTP', {
    objectif: 'SMTP externe fiable',
    temps: '1 h',
    ou: 'Brevo (ex-Sendinblue) / Postmark / Mailgun',
    actions: [
      'Recommandé : Brevo (300 emails/jour gratuit) ou Postmark (transactionnel top qualité)',
      'Inscription + vérification domain (DNS TXT/DKIM/SPF)',
      'Récupérer SMTP creds (host + port + user + password)',
      'WP : installer plugin FluentSMTP → config Brevo API OU SMTP',
      'DKIM + SPF + DMARC : DNS records ajoutés',
    ],
    resultat: 'SMTP externe actif.',
    verification: ['DKIM + SPF + DMARC OK (mail-tester.com)', 'FluentSMTP status green'],
    conseil: 'DKIM/SPF/DMARC = anti-spam obligatoire 2024.',
  }),
  ...etape('2. CRÉER EMAILS PROS + TEST', {
    objectif: 'contact@domain.ma + info@domain.ma',
    temps: '30 min',
    ou: 'hPanel Mail',
    actions: [
      'hPanel → Emails → Créer contact@[domaine].ma + info@[domaine].ma',
      'Password fort 20+ chars',
      'Config client mail (Outlook/Gmail/Apple Mail) : IMAP + SMTP',
      'Test envoi vers Gmail : arrive ?',
      'Test envoi vers Outlook : arrive ?',
    ],
    resultat: 'Emails pros fonctionnels.',
    verification: ['Envoi + réception OK', 'Non spam Gmail/Outlook'],
    conseil: 'Envoi email de test vers Gmail = check anti-spam score.',
  }),
  ...finalCheck(['SMTP externe (Brevo/Postmark)', 'DKIM + SPF + DMARC OK', 'Emails pros créés', 'Tests envoi/réception OK']),
  ...qaCheck(['Mail-tester score 9+/10 ?', 'Non spam ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Config DNS DKIM/SPF/DMARC',
      prompt: 'Config DNS pour SMTP externe Brevo (ou Postmark) : records TXT nécessaires pour SPF + DKIM + DMARC. Domain : [DOMAIN]. Sortie records DNS exacts à ajouter chez registrar.' },
  ]),
  ...conseilsSenior([
    'SMTP hébergeur = délivrabilité faible.',
    'DKIM/SPF/DMARC obligatoires 2024.',
    'Test mail-tester.com avant validation.',
  ]),
  ...validationFinale('SMTP + emails pros opérationnels.', 'Section Emails dans Projet → Infos & Accès'),
  ...escalade('Emails vont en spam malgré config', 'Audit warmup domain + reputation IP'),
]

const SOP_GSC_GA4_WP: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Connecter Google Search Console + Google Analytics 4',
    resultat: 'GSC vérifié, GA4 connecté, tracking actif dès prod',
    delai: '1 h',
    canal: CANAL,
    regle: 'Voir SOPs SEO Search Console + GA4 pour détails.',
    prerequis: ['Site en prod HTTPS'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. GSC + GA4', {
    objectif: 'Setup rapide',
    temps: '1 h',
    ou: 'GSC + GA4',
    actions: [
      'GSC : voir SOP SEO Search Console',
      'GA4 : voir SOP SEO GA4',
      'RankMath Analytics module : connexion Google Analytics API',
      'Vérification propriété via TXT record OU HTML file',
      'Soumettre sitemap SC',
    ],
    resultat: 'GSC + GA4 actifs.',
    verification: ['Propriété vérifiée', 'GA4 real-time OK', 'Sitemap soumis'],
    conseil: 'Voir SOPs SEO dédiés pour détails complets.',
  }),
  ...finalCheck(['GSC vérifié', 'GA4 collecte data', 'Sitemap soumis', 'RankMath Analytics lié']),
  ...qaCheck(['Data GA4 arrive ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Debug GA4 no data',
      prompt: 'GA4 propriété créée mais 0 data 48h après install. Debug : (1) Measurement ID correct dans GTM ? (2) triggers All Pages ? (3) Consent Mode bloque ? (4) filter interne exclut ? Sortie diagnostic pas à pas.' },
  ]),
  ...conseilsSenior([
    'GSC + GA4 dès mise en prod.',
    'RankMath Analytics = data centralisée WP.',
  ]),
  ...validationFinale('GSC + GA4 opérationnels.', 'Screenshots dans Projet → Documentation'),
  ...escalade('Aucune data 48h après', 'Audit tracking détaillé'),
]

/* ─── VÉRIFICATIONS (7 tâches → 3 SOPs) ───────────────────────────────── */
const SOP_TESTS_TECHNIQUES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Tests avant mise en prod : liens, formulaires, emails, responsive, PageSpeed',
    resultat: 'Zéro bug bloquant, checklist QA signée',
    delai: '1 jour',
    canal: CANAL,
    regle: 'Aucun bug bloquant en prod. Zero.',
    prerequis: ['Site staging OK'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. LIENS + FORMULAIRES + EMAILS', {
    objectif: 'Fonctionnel complet',
    temps: '3 h',
    ou: 'Screaming Frog + tests manuels',
    actions: [
      'Screaming Frog : crawl → filtre response ≠ 200 → 0 tolérance',
      'Test formulaires (contact + newsletter) : soumission → email reçu',
      'Test SMTP : envoi/réception vers Gmail + Outlook',
      'Test WhatsApp bouton : ouvre app',
      'Test réseaux sociaux : liens OK',
    ],
    resultat: 'Liens + formulaires + emails OK.',
    verification: ['0 lien 4xx/5xx', 'Formulaires soumettent', 'Emails reçus'],
    conseil: 'Screaming Frog gratuit jusqu\'à 500 URLs — suffit pour la plupart des sites.',
  }),
  ...etape('2. RESPONSIVE + PERF + SEO', {
    objectif: 'UX + technique',
    temps: '3 h',
    ou: 'Chrome DevTools + PSI + Screaming Frog',
    actions: [
      'Voir SOP Responsive : 5 breakpoints + 2 devices',
      'PSI 3 pages : PSI 90+ mobile visé',
      'Audit SEO Screaming Frog : title/meta/H1 par page',
      'Rich Results Test schemas',
    ],
    resultat: 'Perf + SEO OK.',
    verification: ['PSI 90+', 'SEO on-page OK', 'Rich Results valides'],
    conseil: 'PSI 90+ mobile prioritaire (mobile-first indexing).',
  }),
  ...etape('3. VALIDATION INTERNE + SIGNATURE', {
    objectif: 'QA final + go/no-go',
    temps: '2 h',
    ou: 'Réunion équipe interne',
    actions: [
      'Réunion 30 min équipe : chef projet + dev + designer',
      'Parcours utilisateur : Home → Service → Contact',
      'Bugs mineurs listés',
      'Signature go/no-go pour mise en prod',
    ],
    resultat: 'GO signée.',
    verification: ['Réunion tenue', 'Bugs listés', 'Signature GO'],
    conseil: 'Pas de GO sans signature équipe. Protection future.',
  }),
  ...finalCheck(['0 lien 4xx', 'Formulaires OK', 'Emails OK', 'PSI 90+', 'Responsive OK', 'GO signée']),
  ...qaCheck(['Signature équipe interne ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Checklist QA pre-prod',
      prompt: 'Génère checklist QA 30 items avant mise en prod site WordPress : liens, formulaires, emails, responsive, perf, SEO, sécurité, backups. Format checkbox groupé par catégorie.' },
  ]),
  ...conseilsSenior([
    '0 bug bloquant en prod = règle absolue.',
    'PSI 90+ mobile prioritaire.',
    'Signature équipe = protection.',
  ]),
  ...validationFinale('Tests OK + GO signée.', 'Fichier « QA_Pre-Prod_[Client].md » dans Projet → Documentation'),
  ...escalade('Bug bloquant impossible à corriger', 'Chef de projet — décaler mise en prod'),
]

/* ─── MISE EN LIGNE (6 tâches → 3 SOPs) ───────────────────────────────── */
const SOP_MIGRATION: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Migrer staging vers prod avec zéro downtime',
    resultat: 'Site en prod, tests smoke OK, DNS pointent correctement',
    delai: '2-4 h',
    canal: CANAL,
    regle: 'Backup staging + prod avant migration. Toujours.',
    prerequis: ['Staging validé', 'Hébergement prod prêt'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. BACKUP + EXPORT STAGING', {
    objectif: 'Sécurité + export',
    temps: '30 min',
    ou: 'All-in-One WP Migration / Duplicator',
    actions: [
      'Backup staging complet (files + DB) UpdraftPlus',
      'Export via All-in-One WP Migration : fichier .wpress',
      'OU Duplicator : ZIP + installer.php',
      'Télécharger export en local (backup)',
    ],
    resultat: 'Export prêt.',
    verification: ['Fichier .wpress ou ZIP', 'Taille cohérente'],
    conseil: 'All-in-One > Duplicator (simplicité + fiabilité).',
  }),
  ...etape('2. IMPORT PROD + CONFIG', {
    objectif: 'Site en prod',
    temps: '1-2 h',
    ou: 'WP Admin prod',
    actions: [
      'Install WordPress fresh sur hébergement prod (si pas déjà)',
      'Installer plugin All-in-One WP Migration',
      'Import du fichier .wpress',
      'Attention : URL rewrite auto (staging → prod)',
      'Config wp-config.php prod (DB, salts, DISALLOW_FILE_EDIT)',
    ],
    resultat: 'Site en prod importé.',
    verification: ['URLs rewritten', 'DB connectée', 'Config prod'],
    conseil: 'Attention limite upload All-in-One (par défaut 512 MB). Souvent besoin extension paid.',
  }),
  ...finalCheck(['Backup staging', 'Export .wpress', 'Import prod OK', 'wp-config prod configuré']),
  ...qaCheck(['URLs correctes ?', 'DB prod connectée ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Debug URLs après migration',
      prompt: 'Après migration, URLs mixtes staging + prod dans base : [DESCRIPTION]. Génère query SQL wp-cli pour remplacer domaine [OLD] → [NEW] dans wp_options + wp_posts + wp_postmeta. Sécurisé (backup + LIKE match).' },
  ]),
  ...conseilsSenior([
    'Backup avant. Toujours.',
    'All-in-One > Duplicator.',
    'wp-cli search-replace = golden standard.',
  ]),
  ...validationFinale('Site prod importé + configuré.', 'Section migration dans Projet → Documentation'),
  ...escalade('Import échoue (fichier trop lourd)', 'Migration manuelle FTP + phpMyAdmin'),
]

const SOP_DNS_PROD: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Basculer DNS domaine vers hébergement prod',
    resultat: 'https://[domaine] pointe vers prod, HTTPS OK, propagation validée',
    delai: '30 min + 24-48h propagation',
    canal: CANAL,
    regle: 'Faire pendant heure creuse (2-6h du matin).',
    prerequis: ['Site prod prêt + testé'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. BASCULE DNS', {
    objectif: 'Update DNS vers prod',
    temps: '30 min',
    ou: 'Registrar',
    actions: [
      'Registrar → DNS → mettre à jour A record OU nameservers',
      'A record vers IP prod OU nameservers hébergeur prod',
      'TTL faible avant bascule (300s = 5 min propagation rapide)',
      'Cloudflare : DNS ON + proxy ON (nuage orange)',
      'Note timestamp bascule',
    ],
    resultat: 'DNS bascule.',
    verification: ['A record correct', 'Cloudflare proxy ON'],
    conseil: 'TTL 300s permet rollback rapide si problème.',
  }),
  ...etape('2. PROPAGATION + SSL', {
    objectif: 'Vérifier propagation + HTTPS',
    temps: '24-48h monitoring',
    ou: 'whatsmydns.net + navigateur',
    actions: [
      'whatsmydns.net : vérifier propagation mondiale',
      'Après propagation : SSL Let\'s Encrypt automatique (si hébergeur configuré)',
      'Tester https://[domaine] cadenas vert',
      'Rediriger HTTP → HTTPS force',
    ],
    resultat: 'DNS + SSL propagés.',
    verification: ['Propagation whatsmydns OK', 'Cadenas vert', 'HTTP → HTTPS'],
    conseil: 'SSL Let\'s Encrypt auto-renew 90j — vérifier.',
  }),
  ...finalCheck(['A record ou NS mis à jour', 'Cloudflare proxy ON', 'Propagation validée', 'SSL cadenas vert', 'Redirect HTTPS']),
  ...qaCheck(['Cadenas vert partout ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Explique bascule DNS au client',
      prompt: 'Explique client 5 lignes : bascule DNS, 24-48h propagation, SSL auto, aucune action requise de sa part. Ton rassurant sans jargon.' },
  ]),
  ...conseilsSenior([
    'TTL 300s = rollback rapide.',
    'Cloudflare proxy = perf + DDoS gratuit.',
    'SSL Let\'s Encrypt auto-renew 90j.',
  ]),
  ...validationFinale('DNS pointent vers prod + HTTPS OK.', 'Screenshot dans Projet → Documentation'),
  ...escalade('Propagation > 48h', 'Vérifier registrar + cache ISP'),
]

const SOP_MISE_PROD_LIVRAISON: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Finaliser mise en prod + tests smoke + livraison client',
    resultat: 'Site en prod stable, tests smoke OK, formation client faite',
    delai: '1 jour',
    canal: CANAL,
    regle: 'Livraison = formation. Pas d\'envoi email « voici votre site ».',
    prerequis: ['DNS OK', 'HTTPS OK'],
  }),
  ...projectContext(['client.name', 'client.email']),
  h2('Étapes'),
  ...etape('1. TESTS SMOKE PROD', {
    objectif: 'Tests bout-en-bout en prod',
    temps: '2-3 h',
    ou: 'Navigateur + outils',
    actions: [
      'Parcours user complet Home → Service → Contact (test réel)',
      'Formulaire contact : soumission + email reçu',
      'PSI 3 pages critiques',
      'Screaming Frog crawl : 0 lien 4xx',
      'Google Search Console : soumettre sitemap',
      'Ping bing.com/webmaster',
    ],
    resultat: 'Tests OK.',
    verification: ['0 bug bloquant', 'Sitemap soumis'],
    conseil: 'Tests smoke prod obligatoires même si staging validé (config diffère parfois).',
  }),
  ...etape('2. FORMATION CLIENT 45 MIN', {
    objectif: 'Autonomie client',
    temps: '45 min',
    ou: 'Visio',
    actions: [
      'Screen share : parcours WP Admin',
      'Comment publier un article',
      'Comment modifier une page (Elementor)',
      'Comment gérer utilisateurs',
      'Comment restaurer un backup (UpdraftPlus)',
      'Enregistrement disponible ensuite',
    ],
    resultat: 'Client formé.',
    verification: ['Enregistrement dispo', 'Client sait faire actions basiques'],
    conseil: 'Enregistrement = ressource future pour le client.',
  }),
  ...etape('3. LIVRAISON + FOLLOW-UP', {
    objectif: 'Clôturer projet',
    temps: '30 min',
    ou: 'Projet → Discussion',
    actions: [
      'Envoi email récapitulatif : URLs + accès + support',
      'Accès WP admin transféré (client owner)',
      'Documentation dans Projet → Documentation',
      'Program follow-up 30 jours (task récurrente ERP)',
      'Facturation finale',
    ],
    resultat: 'Projet clôturé.',
    verification: ['Docs livrées', 'Follow-up programmé', 'Facturation envoyée'],
    conseil: 'Follow-up 30 jours = opportunité maintenance récurrente.',
  }),
  ...finalCheck(['Tests smoke prod OK', 'Formation client + enregistrement', 'Documentation livrée', 'Follow-up 30j', 'Facturation']),
  ...qaCheck(['Client autonome ?', 'Facturation envoyée ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Email récap livraison',
      prompt: 'Rédige email récap livraison site WP au client [NOM] : URLs prod, accès WP, RankMath, GSC, GA4, support 30 jours, follow-up. Ton pro et rassurant. Max 250 mots.' },
  ]),
  ...conseilsSenior([
    'Livraison = formation, pas email.',
    'Follow-up 30j = pipeline maintenance.',
    'Enregistrement formation = ressource future.',
  ]),
  ...validationFinale('Site en prod, client formé, projet clôturé.', 'Fichier « Livraison_[Client]_[Date].md » dans Projet → Documentation'),
  ...escalade('Client refuse la formation', 'Documentation vidéo + insister sur enregistrement'),
]

/* ═══════════════════════════════════════════════════════════════════════ */

export const SOP_INDEX_WORDPRESS: Record<string, SopBlock[]> = {
  // Collecte (6 → 2)
  [norm('Récupérer le nom de l\'entreprise')]:            SOP_COLLECTE_IDENTITE,
  [norm('Récupérer le logo')]:                            SOP_COLLECTE_IDENTITE,
  [norm('Définir les couleurs de la marque')]:            SOP_COLLECTE_IDENTITE,
  [norm('Coordonnées (adresse, téléphone, e-mail)')]:     SOP_COLLECTE_IDENTITE,
  [norm('Liens des réseaux sociaux')]:                    SOP_COLLECTE_IDENTITE,
  [norm('Liste des services et informations utiles')]:    SOP_COLLECTE_SERVICES,
  // Maquette (3 → 1)
  [norm('Conception de la maquette')]:                    SOP_MAQUETTE,
  [norm('Présentation de la maquette au client')]:        SOP_MAQUETTE,
  [norm('Validation client avant développement')]:        SOP_MAQUETTE,
  // Domaine (3 → 2)
  [norm('Réservation ou transfert du nom de domaine')]:   SOP_DOMAINE,
  [norm('Configuration de l\'hébergement')]:              SOP_HEBERGEMENT_SSL,
  [norm('Installation du certificat SSL')]:               SOP_HEBERGEMENT_SSL,
  // Dev (5 → 3)
  [norm('Installation et configuration de WordPress')]:   SOP_INSTALL_WP,
  [norm('Génération / personnalisation du thème (Claude Code)')]: SOP_THEME_HEADER,
  [norm('Création du Header, Footer et menus')]:          SOP_THEME_HEADER,
  [norm('Création de toutes les pages')]:                 SOP_PAGES_FONCTIONNALITES,
  [norm('Intégration des fonctionnalités demandées')]:    SOP_PAGES_FONCTIONNALITES,
  // Contenu (3 → 2)
  [norm('Rédaction et intégration des contenus')]:        SOP_CONTENU,
  [norm('Optimisation des images')]:                      SOP_IMAGES,
  [norm('Optimisation des appels à l\'action (CTA)')]:    SOP_CONTENU,
  // Optim (3 → 3)
  [norm('Responsive (mobile, tablette, desktop)')]:       SOP_RESPONSIVE,
  [norm('Optimisation SEO on-page')]:                     SOP_SEO_ON_PAGE_WP,
  [norm('Optimisation des performances (vitesse)')]:      SOP_PERFORMANCES,
  // Intégrations (8 → 5)
  [norm('Bouton WhatsApp flottant')]:                     SOP_WHATSAPP_LIENS,
  [norm('Formulaire de contact')]:                        SOP_FORMULAIRE_MAPS,
  [norm('Google Maps sur la page contact')]:              SOP_FORMULAIRE_MAPS,
  [norm('Liens vers réseaux sociaux')]:                   SOP_WHATSAPP_LIENS,
  [norm('Configuration SMTP (envoi des e-mails)')]:       SOP_SMTP_EMAILS,
  [norm('Création et test des e-mails professionnels')]:  SOP_SMTP_EMAILS,
  [norm('Connexion Google Search Console')]:              SOP_GSC_GA4_WP,
  [norm('Installation Google Analytics')]:                SOP_GSC_GA4_WP,
  // Vérifications (7 → 1 SOP dense)
  [norm('Contrôle de tous les liens')]:                   SOP_TESTS_TECHNIQUES,
  [norm('Test des formulaires')]:                         SOP_TESTS_TECHNIQUES,
  [norm('Test d\'envoi et réception des e-mails')]:       SOP_TESTS_TECHNIQUES,
  [norm('Vérification responsive sur plusieurs appareils')]: SOP_TESTS_TECHNIQUES,
  [norm('Vérification des performances (PageSpeed)')]:    SOP_TESTS_TECHNIQUES,
  [norm('Vérification SEO (audit final)')]:               SOP_TESTS_TECHNIQUES,
  [norm('Validation finale interne')]:                    SOP_TESTS_TECHNIQUES,
  // Mise en ligne (6 → 3)
  [norm('Migration vers l\'hébergement de production')]:  SOP_MIGRATION,
  [norm('Configuration finale du nom de domaine')]:       SOP_DNS_PROD,
  [norm('Mise en production')]:                           SOP_MISE_PROD_LIVRAISON,
  [norm('Tests finaux en production')]:                   SOP_MISE_PROD_LIVRAISON,
  [norm('Indexation du site sur Google')]:                SOP_GSC_GA4_WP,
  [norm('Livraison au client + formation')]:              SOP_MISE_PROD_LIVRAISON,
}
