/**
 * SOP — SEO On-Page (20 tâches)
 * Rôle : Consultant SEO Senior — 30+ ans, on-page & technique, 500+ sites.
 */
import type { SopBlock } from '@/hooks/useSops'
import {
  introExpert, etape, finalCheck, qaCheck, promptCards,
  conseilsSenior, validationFinale, escalade, projectContext, h2,
} from './sopHelpers'

const norm = (s: string) => (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim()
const ROLE = 'Consultant SEO Senior — 30+ ans, on-page & technique, focus Maroc/francophone'
const CANAL = 'Blocage / question stratégie → Projet → Discussion (canal SEO)'

/* ─── AUDITS ──────────────────────────────────────────────────────────── */
const SOP_AUDIT_TECHNIQUE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Auditer la santé technique du site en 45 min : crawl, indexation, vitesse, structure',
    resultat: 'Rapport technique 1-pager listant top 5 problèmes chiffrés + priorité',
    delai: '45 min site petit, 2 h site gros',
    canal: CANAL,
    regle: 'JAMAIS toucher aux redirects/robots.txt sans avoir screenshot de l\'état initial.',
    prerequis: ['Accès Search Console + accès admin site OU staging'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. CRAWL + INDEXATION', {
    objectif: 'Repérer pages indexées, crawl errors, doublons',
    temps: '20 min',
    ou: 'Search Console → Couverture · Screaming Frog',
    actions: [
      'Search Console → Couverture → note pages « Valides », « Avec avertissements », « Exclues »',
      'Screaming Frog : crawl complet, filtre response code ≠ 200',
      'Note doublons title / meta description (>1 URL même title)',
      'Vérifie robots.txt et sitemap.xml accessibles',
    ],
    resultat: 'Liste erreurs indexation + doublons.',
    verification: ['Sitemap et robots.txt trouvés', 'Erreurs 4xx/5xx listées', 'Doublons titres identifiés'],
    conseil: 'Une page dupliquée en title = perte position instantanée. Identifie-les d\'abord.',
  }),
  ...etape('2. CORE WEB VITALS + STRUCTURE', {
    objectif: 'Mesurer LCP, CLS, INP + audit balises structurantes',
    temps: '15 min',
    ou: 'PageSpeed Insights + Screaming Frog',
    actions: [
      'PageSpeed Insights → run homepage + 3 pages critiques',
      'Note LCP (< 2.5s), CLS (< 0.1), INP (< 200ms)',
      'Screaming Frog : filtre H1 vide / multiple H1 / title > 60 chars / meta description > 160 chars',
      'Vérifie canonical présent sur toutes les pages',
    ],
    resultat: 'Core Web Vitals notés + balises audités.',
    verification: ['3 pages testées PSI', 'H1/title/meta audit fait', 'Canonical présent'],
    conseil: 'Depuis 2021, Core Web Vitals impactent le rank. LCP > 4s = pénalité mobile-first.',
  }),
  ...etape('3. SYNTHÈSE + PRIORISATION', {
    objectif: '1-pager top 5 problèmes chiffrés',
    temps: '10 min',
    ou: 'Projet → Documentation',
    actions: [
      'Format : Problème | Impact SEO | Effort correction | Priorité 🔴🟠🟢',
      'Priorité 🔴 : erreurs indexation, canonical manquants, LCP > 4s',
      'Priorité 🟠 : title/meta manquants, doublons, H1 vides',
      'Priorité 🟢 : optimisations mineures',
    ],
    resultat: 'Priorisation claire.',
    verification: ['5 problèmes max', 'Chiffres à l\'appui'],
    conseil: 'Un audit qui liste 30 problèmes ne sert à rien. Sélectionne les 5 à impact 80/20.',
  }),
  ...finalCheck(['Sitemap + robots.txt vérifiés', 'Core Web Vitals mesurés', 'Balises H1/title/meta auditées', 'Top 5 problèmes chiffrés + priorité']),
  ...qaCheck(['Chaque problème a-t-il un impact chiffré ?', 'Priorité 🔴🟠🟢 attribuée ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Analyse crawl Screaming Frog',
      prompt: 'Voici l\'export CSV de mon crawl Screaming Frog : [COLLE]. Identifie : (1) top 10 URLs avec status ≠ 200, (2) titles dupliqués (mêmes >1 URL), (3) meta descriptions manquantes, (4) H1 dupliqués ou vides. Sortie : rapport priorisé impact/effort.' },
  ]),
  ...conseilsSenior([
    'Un audit qui liste 30 problèmes ne sert à rien. 5 focus.',
    'Photo initiale des Core Web Vitals = indispensable pour prouver ROI ensuite.',
    'Canonical manquant = duplicate content garanti sur les paramètres URL.',
  ]),
  ...validationFinale('Rapport 1-pager audit technique livré, priorités claires.', 'Fichier « Audit_Tech_[Client]_[Date].md » dans Projet → Documentation'),
  ...escalade('Site avec > 100k pages ou architecture custom', 'Chef de projet — audit complexe > 4h'),
]

const SOP_AUDIT_CONTENU: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Auditer le contenu existant : mots-clés couverts, thin content, cannibalisation',
    resultat: 'Tableau content audit : URL | Title | KW principal | Score qualité | Action (garder/optim/supprimer)',
    delai: '2-3 h pour site 50-100 pages',
    canal: CANAL,
    regle: 'JAMAIS supprimer une page sans redirection 301 vers page pertinente.',
    prerequis: ['Screaming Frog + Search Console + Ahrefs/Semrush'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. INVENTAIRE URL', {
    objectif: 'Lister toutes les URLs indexées + métriques trafic',
    temps: '30 min',
    ou: 'Screaming Frog + Search Console',
    actions: [
      'Export Screaming Frog : URL, Title, H1, word count',
      'Export Search Console 12 mois : URL, clics, impressions, CTR moyen, position moyenne',
      'Merger dans un tableau maître',
      'Filtre URLs indexées uniquement',
    ],
    resultat: 'Tableau maître ~50-500 URLs.',
    verification: ['URLs listées avec trafic', 'Word count présent'],
    conseil: 'Ce tableau maître te suivra tout le projet. Investis 30 min à le structurer.',
  }),
  ...etape('2. CLASSIFICATION QUALITÉ + CANNIBALISATION', {
    objectif: 'Attribuer un score qualité à chaque URL',
    temps: '1-2 h',
    ou: 'Tableau maître',
    actions: [
      'Score : 🔴 thin content (< 300 mots) + 0 clics 6 mois → à supprimer',
      'Score : 🟠 contenu moyen (300-800 mots) + peu de clics → à réécrire',
      'Score : 🟢 contenu solide (800+ mots) + clics réguliers → à optimiser',
      'Cannibalisation : plusieurs URLs sur même KW → note action (fusion, redirect)',
    ],
    resultat: 'Chaque URL classifiée.',
    verification: ['Toutes URLs scorées', 'Cannibalisations identifiées'],
    erreurs: [['Supprimer sans 301', 'Perte de link juice. Toujours 301 vers page proche.']],
    conseil: 'Content pruning (suppression thin content) = +15-30% de trafic organique en 6 mois.',
  }),
  ...etape('3. PLAN D\'ACTION', {
    objectif: 'Prioriser 10-20 actions',
    temps: '30 min',
    ou: 'Projet → Documentation',
    actions: [
      'Top 5 URLs à supprimer + redirects 301',
      'Top 10 URLs à réécrire (word count + intent match)',
      'Top 5 URLs à optimiser (Quick Wins)',
      'Note dans Projet → Documentation avec timeline',
    ],
    resultat: 'Roadmap contenu prête.',
    verification: ['Actions chiffrées', 'Redirects 301 planifiés'],
    conseil: 'Quick Wins (positions 4-10) = gain rapide. Priorité 1.',
  }),
  ...finalCheck(['Tableau maître URLs + trafic', 'Scores 🔴🟠🟢 attribués', 'Cannibalisations identifiées', 'Roadmap 20 actions']),
  ...qaCheck(['Redirects 301 planifiés pour suppressions ?', 'Quick Wins identifiés ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Identifie cannibalisation depuis Search Console',
      prompt: 'Voici l\'export Search Console : [COLLE CSV avec URL/query/clicks/impressions]. Identifie les cas de cannibalisation : plusieurs URLs qui rankent sur la même query. Sortie : tableau | Query | URLs concernées | Action (fusion, canonical, redirect) |.' },
  ]),
  ...conseilsSenior([
    'Content pruning = levier SEO souvent oublié. +15-30% trafic possible.',
    'Toujours 301 avant suppression. Sinon perte link juice.',
    'Quick Wins positions 4-10 = ROI immédiat.',
  ]),
  ...validationFinale('Content audit terminé, roadmap 20 actions signée.', 'Fichier « Content_Audit_[Client].xlsx » dans Projet → Documentation'),
  ...escalade('Site > 500 pages avec architecture profonde', 'Chef de projet — audit approfondi'),
]

const SOP_AUDIT_CONCURRENTS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Cartographier 3-5 concurrents SEO : mots-clés, structure, backlinks, gaps',
    resultat: 'Rapport concurrentiel : top KW concurrents / KW gap / opportunités contenu',
    delai: '2-3 h',
    canal: CANAL,
    regle: 'Cible concurrents qui rankent, pas juste ceux que le client cite.',
    prerequis: ['Ahrefs ou Semrush (accès trial ok)'],
  }),
  ...projectContext(['client.name', 'client.company', 'domain']),
  h2('Étapes'),
  ...etape('1. SÉLECTION 3-5 CONCURRENTS RÉELS', {
    objectif: 'Identifier les concurrents SEO (pas commerciaux)',
    temps: '30 min',
    ou: 'Ahrefs / Semrush',
    actions: [
      'Ahrefs → Overview → Competing Domains',
      'Sélectionne 3-5 domaines avec « common keywords > 100 »',
      'Filtre : même pays cible (Maroc)',
      'Exclus les gros players hors-scope (ex Wikipedia, Amazon)',
    ],
    resultat: 'Liste 3-5 concurrents validés.',
    verification: ['3-5 concurrents cible', 'Common KW > 100 chacun'],
    conseil: 'Concurrent SEO ≠ concurrent commercial. Ahrefs Competing Domains est l\'outil référence.',
  }),
  ...etape('2. GAP ANALYSIS + BACKLINKS', {
    objectif: 'Identifier KW rankés par eux et pas par toi + top backlinks',
    temps: '1-2 h',
    ou: 'Ahrefs Content Gap + Backlinks',
    actions: [
      'Ahrefs → Content Gap → ton domaine vs 3 concurrents',
      'Export KW où eux rankent (top 20) et toi absent',
      'Filtre : volume > 100, difficulté < 40',
      'Ahrefs → Backlinks → top 20 backlinks concurrents',
      'Identifie backlinks reproductibles (annuaires, articles invités, listes)',
    ],
    resultat: 'Liste 50-200 KW gap + 20 backlinks cibles.',
    verification: ['KW gap filtrés (volume + difficulté)', 'Backlinks reproductibles identifiés'],
    conseil: 'Un KW gap avec volume > 500 et difficulté < 30 = opportunité en or.',
  }),
  ...etape('3. RAPPORT + PLAN CONTENU', {
    objectif: 'Rapport 3 pages : top opportunités + plan',
    temps: '30 min',
    ou: 'Projet → Documentation',
    actions: [
      'Résumé structure concurrents (nb pages, silos, catégories)',
      'Top 20 KW gap prioritaires (volume × difficulté)',
      'Top 10 backlinks à essayer de reproduire',
      'Plan contenu : 10 articles à créer / réécrire',
    ],
    resultat: 'Rapport concurrentiel + plan contenu.',
    verification: ['20 KW gap priorisés', '10 articles planifiés'],
    conseil: 'Rank pour ce que tes concurrents ratent = tactic sous-évaluée.',
  }),
  ...finalCheck(['3-5 concurrents identifiés', 'Gap 50-200 KW analysé', '20 backlinks cibles', '10 articles planifiés']),
  ...qaCheck(['Concurrents = concurrents SEO réels ?', 'KW gap filtrés par volume/difficulté ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Priorise KW gap',
      prompt: 'Voici mon KW gap (CSV Ahrefs) : [COLLE]. Filtre + priorise 20 KW selon score (volume × 100 / difficulté). Ajoute colonne « intention » (transactionnel / informatif / navigation). Sortie tableau Markdown.' },
  ]),
  ...conseilsSenior([
    'Concurrent SEO ≠ concurrent commercial. Ahrefs le sait mieux que toi.',
    'KW gap volume >500 + difficulté <30 = or pur.',
    'Backlinks reproductibles = plus valuable que backlinks uniques.',
  ]),
  ...validationFinale('Rapport concurrentiel + 10 articles priorisés.', 'Fichier « Concurrents_[Client].md » dans Projet → Documentation'),
  ...escalade('Aucun concurrent avec > 100 common KW', 'Chef de projet — repositionner stratégie (niche différente)'),
]

/* ─── MOTS-CLÉS ───────────────────────────────────────────────────────── */
const SOP_KW_PRINCIPAUX: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Sélectionner 20-30 mots-clés principaux à forte intention transactionnelle',
    resultat: 'Liste KW priorisés avec volume, difficulté, intention, URL cible',
    delai: '2 h',
    canal: CANAL,
    regle: 'Un KW principal = 500+ recherches/mois ET intention claire. Sinon = KW secondaire.',
    prerequis: ['Ahrefs/Semrush + Search Console'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. SEED LIST + KEYWORD PLANNER', {
    objectif: 'Générer 100-200 KW candidats',
    temps: '45 min',
    ou: 'Ahrefs Keywords Explorer + Keyword Planner',
    actions: [
      'Seed list : 20 mots métier + variantes',
      'Ahrefs → Keywords Explorer → colle seeds',
      'Filtres : volume ≥ 100 · difficulté ≤ 50 · pays Maroc',
      'Export CSV complet',
    ],
    resultat: '100-200 KW candidats.',
    verification: ['Volume + difficulté renseignés', 'Zone géo Maroc'],
    conseil: 'Ahrefs Keyword Difficulty > 50 = 6+ mois pour ranker (débutant). Reste sous 50.',
  }),
  ...etape('2. FILTRAGE INTENTION + SÉLECTION 20-30', {
    objectif: 'Garder uniquement les KW à intention pertinente',
    temps: '1 h',
    ou: 'Tableur',
    actions: [
      'Marque intention : 🔥 transactionnel · 💡 informatif · 🧭 navigation',
      'Priorité aux 🔥 pour URL commerciales, 💡 pour blog',
      'Retire les KW ambigus (« comment X » avec intention informative + commerciale mixte)',
      'Sélectionne 20-30 KW principaux (avec URL cible)',
    ],
    resultat: '20-30 KW finaux.',
    verification: ['Intention marquée', 'URL cible assignée'],
    conseil: 'Un KW ambigu ne rankera jamais. Choisis camp clair.',
  }),
  ...finalCheck(['100+ KW candidats', 'Intention classifiée', '20-30 KW principaux', 'URL cible assignée']),
  ...qaCheck(['Chaque KW principal a-t-il volume > 100 ?', 'Intention claire ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Classifier intention KW',
      prompt: 'Voici 100 KW : [COLLE]. Classifie chaque en 🔥 transactionnel / 💡 informatif / 🧭 navigation. Pour les ambigus, choisis camp majoritaire + explique en 1 mot. Sortie CSV.' },
  ]),
  ...conseilsSenior([
    'Difficulté < 50 pour débutant. Sinon patience 6 mois+.',
    'Intention claire > volume élevé.',
    'Ne mélange jamais intention commerciale + informative sur même URL.',
  ]),
  ...validationFinale('20-30 KW principaux prêts avec URL cible.', 'Fichier « KW_Principaux_[Client].xlsx » dans Projet → Documentation'),
  ...escalade('Aucun KW < 50 difficulté trouvé', 'Chef de projet — revoir stratégie longue traîne'),
]

const SOP_KW_LONGUE_TRAINE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Générer 100-300 KW longue traîne (3+ mots) à faible concurrence',
    resultat: 'Liste KW longue traîne pour articles blog + FAQ + landing pages secondaires',
    delai: '2 h',
    canal: CANAL,
    regle: 'Longue traîne convertit 5-10× mieux que tête de traîne. Volume divisé par 10.',
    prerequis: ['KW principaux définis'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. GÉNÉRATION LONGUE TRAÎNE', {
    objectif: 'Extraire 100-300 formulations 3+ mots',
    temps: '1 h',
    ou: 'Ahrefs / AnswerThePublic / Google Suggest',
    actions: [
      'Ahrefs → Keywords Explorer → filtre "word count ≥ 3"',
      'AnswerThePublic : questions autour KW principaux',
      'Google Suggest : lettre par lettre depuis KW principal',
      'People Also Ask sur SERP : questions supplémentaires',
    ],
    resultat: '100-300 KW longue traîne.',
    verification: ['≥ 3 mots', 'Volume ≥ 20'],
    conseil: 'People Also Ask + AnswerThePublic = mine d\'or contenu informatif.',
  }),
  ...etape('2. MAPPING VERS FORMATS CONTENU', {
    objectif: 'Chaque KW LT → 1 format contenu',
    temps: '1 h',
    ou: 'Tableur',
    actions: [
      'KW question (« comment X ? ») → Article blog',
      'KW comparatif (« X vs Y ») → Article comparatif',
      'KW local (« X à Casablanca ») → Landing page locale',
      'KW ultra-spécifique → FAQ section',
    ],
    resultat: 'Mapping KW → format contenu.',
    verification: ['Chaque KW a un format assigné'],
    conseil: 'PAA (People Also Ask) → FAQ block sur landing = feature snippet quasi garanti.',
  }),
  ...finalCheck(['100-300 KW LT collectés', 'Volume ≥ 20 filtré', 'Format contenu assigné']),
  ...qaCheck(['Sources multiples utilisées (Ahrefs + PAA + AtP) ?', 'Chaque KW a un format ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 50 KW LT à partir d\'un KW principal',
      prompt: 'KW principal : [KW]. Génère 50 KW longue traîne (3+ mots) organisés : 20 questions (comment/pourquoi/quand), 15 comparatifs (X vs Y), 15 locaux ([KW] + villes Maroc). Sortie liste plate.' },
  ]),
  ...conseilsSenior([
    'Longue traîne = ROI SEO le plus élevé (5-10x conversion).',
    'PAA → FAQ = feature snippet quasi-garanti.',
    'AnswerThePublic gratuit 3 recherches/jour — largement suffisant.',
  ]),
  ...validationFinale('100-300 KW LT mappés vers formats contenu.', 'Fichier « KW_Longue_Traine_[Client].xlsx » dans Projet → Documentation'),
  ...escalade('Longue traîne saturée par gros players', 'Chef de projet — spécialisation micro-niche'),
]

const SOP_KW_MAPPING: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Mapper 1 KW principal = 1 URL cible + KW secondaires + LT associés',
    resultat: 'Fichier mapping : URL | KW principal | KW secondaires | KW LT | Format contenu',
    delai: '2 h',
    canal: CANAL,
    regle: 'JAMAIS 2 URLs qui ciblent le même KW principal. Cannibalisation garantie.',
    prerequis: ['KW principaux + LT prêts'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. AFFECTATION KW ↔ URL', {
    objectif: 'Chaque KW principal = 1 URL unique',
    temps: '1 h',
    ou: 'Tableur',
    actions: [
      'Colonnes : URL | KW principal | KW secondaires (2-3) | KW LT (5-10) | Intent',
      'Une URL peut cibler 1 KW principal + 2-3 secondaires proches',
      'JAMAIS 2 URLs sur même KW principal (cannibalisation)',
      'Groupe LT par silo thématique',
    ],
    resultat: 'Fichier mapping complet.',
    verification: ['1 KW principal = 1 URL', 'KW secondaires cohérents'],
    conseil: 'Ce fichier est ton bible SEO 2 ans. Investis-le sérieusement.',
  }),
  ...etape('2. VÉRIFICATION CANNIBALISATION', {
    objectif: 'Contrôler qu\'aucun KW n\'est ciblé par 2 URLs',
    temps: '30 min',
    ou: 'Tableur + Search Console',
    actions: [
      'Filtre KW principaux : trier ordre alphabétique',
      'Repère doublons ou variations très proches',
      'Search Console → filtre le KW → vérifie que seule ta URL cible ranke',
      'Corrige mapping si conflit',
    ],
    resultat: 'Zéro cannibalisation.',
    verification: ['Doublons éliminés', 'Search Console cohérent'],
    conseil: 'Cannibalisation = 2 URLs qui se battent, aucune ne gagne.',
  }),
  ...finalCheck(['1 KW principal = 1 URL', 'KW secondaires 2-3 par URL', 'KW LT groupés par silo', 'Zéro cannibalisation']),
  ...qaCheck(['Chaque URL a-t-elle 1 seul KW principal ?', 'Cannibalisation vérifiée SC ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Détecte cannibalisation dans mapping',
      prompt: 'Voici mon mapping KW → URL : [COLLE CSV]. Détecte : (1) KW principal ciblé par > 1 URL, (2) KW secondaires en doublon entre URLs. Sortie : rapport conflits + suggestion résolution.' },
  ]),
  ...conseilsSenior([
    '1 KW principal = 1 URL. Règle absolue.',
    'KW secondaires sur même URL doivent être variations proches (accents, singulier/pluriel).',
    'Silos thématiques = pillar page + articles satellites.',
  ]),
  ...validationFinale('Mapping KW ↔ URL complet, zéro cannibalisation.', 'Fichier « Mapping_KW_[Client].xlsx » dans Projet → Documentation'),
  ...escalade('Cannibalisation existante impossible à résoudre', 'Chef de projet — suppression + 301 nécessaire'),
]

/* ─── ON-PAGE ────────────────────────────────────────────────────────── */
const SOP_META_TITLE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger meta titles optimisés : KW en début + < 60 chars + attractif',
    resultat: 'Chaque URL a un meta title unique, avec KW principal en position 1-3, < 60 chars',
    delai: '30 min par 10 URLs',
    canal: CANAL,
    regle: 'Meta title > 60 chars = coupure Google. KW dilué si en fin de title.',
    prerequis: ['Mapping KW ↔ URL prêt'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. RÈGLES DE RÉDACTION', {
    objectif: 'Connaître les contraintes',
    temps: '5 min',
    ou: 'Projet → Documentation',
    actions: [
      'Max 60 chars (parfois 55 sur mobile)',
      'KW principal en position 1-3 (début)',
      'Brand en fin : « Titre | Marque »',
      'Verbe d\'action ou USP si possible',
      'Aucun capital abusif (SEO ≠ shouting)',
    ],
    resultat: 'Règles claires.',
    verification: ['≤ 60 chars', 'KW début', 'Brand en fin'],
    conseil: 'Google coupe à 600 pixels (~55-60 chars). Trop long = ton titre invisible.',
  }),
  ...etape('2. RÉDACTION + INTÉGRATION', {
    objectif: 'Rédiger 1 title par URL cible',
    temps: '25 min par 10 URLs',
    ou: 'CMS (WordPress + RankMath / Yoast) OU code source',
    actions: [
      'Prend mapping KW → URL',
      'Rédige title selon formule : [KW principal] | [Bénéfice] | [Marque]',
      'Vérifie longueur (outil : mangools SERP simulator)',
      'Intègre via CMS (RankMath onglet SEO) OU code <title>',
      'Vérifie sur SERP après indexation',
    ],
    resultat: 'Meta titles intégrés.',
    verification: ['Longueur vérifiée', 'Intégré CMS/code', 'Prévisualisation SERP OK'],
    erreurs: [['Title identique à H1', 'Perte opportunité. Title = accroche SERP, H1 = début lecture.']],
    conseil: 'Utilise mangools SERP simulator pour vérifier rendu réel avant publish.',
  }),
  ...finalCheck(['Chaque URL a title unique', 'KW en début', '≤ 60 chars', 'Brand en fin', 'Intégré CMS']),
  ...qaCheck(['Titles < 60 chars ?', 'KW dans les 3 premiers mots ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige 10 meta titles optimisés',
      prompt: 'Voici 10 pages avec KW principal : [COLLE]. Rédige un meta title par page. Contraintes : ≤ 60 chars, KW en position 1-3, brand [BRAND] en fin, ton bénéfice-driven. Sortie tableau | URL | KW | Title | Nb chars |.' },
  ]),
  ...conseilsSenior([
    'Title = ta pub gratuite sur Google. Investis chaque mot.',
    'KW en début > KW en fin. Google pondère la position.',
    'Test A/B titles via Search Console 30j : compare CTR avant/après.',
  ]),
  ...validationFinale('Meta titles intégrés + testés SERP simulator.', 'Section Meta titles dans Projet → Documentation'),
  ...escalade('CMS bloque personnalisation title', 'Chef de projet — voir plugin dev ou passer en code direct'),
]

const SOP_META_DESC: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger meta descriptions attractives < 155 chars incitant au clic',
    resultat: 'Chaque URL a une meta desc unique, KW principal + CTA + USP, < 155 chars',
    delai: '30 min par 10 URLs',
    canal: CANAL,
    regle: 'Meta desc n\'est pas un facteur de ranking direct, mais impacte le CTR = ranking indirect.',
    prerequis: ['Mapping KW ↔ URL'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. RÈGLES RÉDACTION', {
    objectif: 'Contraintes claires',
    temps: '5 min',
    ou: '',
    actions: [
      'Max 155 chars (parfois 120 sur mobile)',
      'KW principal (Google le mettra en gras dans SERP)',
      'CTA implicite : « Découvrez », « Réservez », « Testez »',
      'USP unique : chiffre, garantie, spécificité',
      'Éviter guillemets (Google les affiche mal)',
    ],
    resultat: 'Règles.',
    verification: ['≤ 155 chars', 'CTA + USP + KW'],
    conseil: 'Google réécrit 60% des meta desc en 2024. Mais 40% garde ta rédaction — investis quand même.',
  }),
  ...etape('2. RÉDACTION + INTÉGRATION', {
    objectif: 'Rédiger + intégrer via CMS',
    temps: '25 min par 10 URLs',
    ou: 'CMS (WordPress RankMath / Yoast)',
    actions: [
      'Formule : [Accroche KW] · [USP chiffré] · [CTA implicite]',
      'Ex : « Photographe mariage Casablanca 15 ans d\'expérience. 500+ mariages. Devis gratuit sous 24h. »',
      'Vérifie via mangools SERP simulator',
      'Intègre CMS + attends indexation',
    ],
    resultat: 'Meta desc intégrés.',
    verification: ['Longueur OK', 'CTA + USP présents', 'Intégré CMS'],
    conseil: 'Chiffre concret (500 clients, 15 ans, 24h) > adjectifs vagues (meilleur, premium).',
  }),
  ...finalCheck(['Meta desc unique par URL', '≤ 155 chars', 'KW + CTA + USP', 'Intégré CMS']),
  ...qaCheck(['Chiffre concret présent ?', 'Sans guillemets ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige 10 meta descriptions optimisées',
      prompt: 'Voici 10 pages avec KW + USP : [COLLE]. Rédige 1 meta desc par page. Contraintes : ≤ 155 chars, KW naturel, USP chiffré, CTA implicite (Découvrez/Réservez). Ton [TON]. Sortie tableau | URL | Meta desc | Nb chars |.' },
  ]),
  ...conseilsSenior([
    'CTR sur SERP = ranking factor indirect.',
    'Google réécrit 60% des meta desc. Investis quand même.',
    'Chiffre concret > adjectif vague. Toujours.',
  ]),
  ...validationFinale('Meta desc intégrés partout.', 'Section Meta desc dans Projet → Documentation'),
  ...escalade('Google réécrit systématiquement (100%)', 'Chef de projet — revoir angle ou rédiger avec moins de KW'),
]

const SOP_HN_STRUCTURE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Structurer les balises H1/H2/H3 sur toutes pages selon hiérarchie sémantique',
    resultat: '1 H1 unique par page (KW principal), H2/H3 hiérarchisés, aucun saut de niveau',
    delai: '30 min par page principale',
    canal: CANAL,
    regle: '1 H1 par page. JAMAIS 2. Saut de niveau (H1→H3) = erreur sémantique.',
    prerequis: ['Contenu écrit ou template'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. AUDIT STRUCTURE ACTUELLE', {
    objectif: 'Repérer les H manquants ou multiples',
    temps: '15 min par page',
    ou: 'Screaming Frog + inspection navigateur',
    actions: [
      'Screaming Frog : filtre H1 vide ou multiple',
      'Inspection navigateur → Elements → cherche <h1>, <h2>, <h3>',
      'Note structure actuelle : arbre sémantique',
    ],
    resultat: 'Diagnostic structure.',
    verification: ['H1 unique vérifié', 'H2/H3 hiérarchie notée'],
    conseil: 'Beaucoup de thèmes WordPress mettent H1 sur le logo → conflit. Vérifie sur page.',
  }),
  ...etape('2. RESTRUCTURATION', {
    objectif: 'Un H1 unique = KW principal, H2 = sous-sections, H3 = détails',
    temps: '15 min par page',
    ou: 'CMS ou code',
    actions: [
      'H1 = KW principal + contexte (max 70 chars)',
      'H2 = 3-5 sections principales (chaque section = groupe de KW secondaires ou LT)',
      'H3 = détails sous chaque H2',
      'JAMAIS de saut de niveau (H1 → H3 direct = erreur)',
      'Test screen reader accessibility',
    ],
    resultat: 'Structure propre.',
    verification: ['1 seul H1', 'Pas de saut de niveau', 'H2 3-5 minimum'],
    conseil: 'Un blind reader navigue par H. Structure = accessibilité + SEO combinés.',
  }),
  ...finalCheck(['1 H1 unique KW principal', 'H2 3-5 sections', 'H3 sous-détails', 'Aucun saut de niveau']),
  ...qaCheck(['Screen reader test OK ?', 'H1 unique confirmé Screaming Frog ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Structure H1/H2/H3 pour article',
      prompt: 'Article sur [SUJET] ciblant KW « [KW] ». Propose structure H1 (1) + H2 (4-5) + H3 (2-3 par H2). Contraintes : H1 ≤ 70 chars, H2 clair et actionnable, H3 = détail. KW secondaires intégrés dans H2 naturellement.' },
  ]),
  ...conseilsSenior([
    '1 H1 par page = règle absolue.',
    'Saut de niveau = signal négatif Google + accessibilité cassée.',
    'H2 stratégiques = KW secondaires distribués.',
  ]),
  ...validationFinale('Structure H propre partout.', 'Audit final Screaming Frog dans Projet → Documentation'),
  ...escalade('Thème CMS injecte H1 sur logo (impossible à modifier)', 'Chef de projet — override CSS ou plugin custom'),
]

const SOP_ALT_TEXTS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger alt texts descriptifs + KW pour toutes images (SEO + accessibilité)',
    resultat: '100% des images ont un alt text non vide, descriptif, KW naturel si pertinent',
    delai: '5 min par 10 images',
    canal: CANAL,
    regle: 'Alt text vide = image invisible pour Google + malvoyants. Toujours renseigner.',
    prerequis: ['Images uploadées'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. AUDIT IMAGES ACTUELLES', {
    objectif: 'Repérer alt vides',
    temps: '15 min',
    ou: 'Screaming Frog → Images sans alt',
    actions: [
      'Screaming Frog → Images → filtre « Missing Alt Text »',
      'Note URL + count par page',
    ],
    resultat: 'Liste images sans alt.',
    verification: ['Count par page notée'],
    conseil: 'Depuis 2023, images optimisées SEO = Google Image Search + Bing → trafic bonus.',
  }),
  ...etape('2. RÉDACTION ALT', {
    objectif: 'Alt descriptif + KW naturel',
    temps: '5 min par 10 images',
    ou: 'CMS Media Library',
    actions: [
      'Description factuelle de l\'image (« photographe capture couple sur plage »)',
      'Intègre KW si naturel (« mariage Essaouira »)',
      'Max 125 chars',
      'JAMAIS de stuffing keyword (« mariage mariage plage mariage »)',
      'Pour image décorative : alt="" (vide voulu)',
    ],
    resultat: 'Alt texts renseignés.',
    verification: ['Descriptifs', 'KW naturel', 'Décoratives = alt vide'],
    conseil: 'Un blind reader entend l\'alt. Écoute-le à voix haute. Si étrange, réécris.',
  }),
  ...finalCheck(['100% images ont alt', 'Descriptif + KW naturel', 'Décoratives = alt vide']),
  ...qaCheck(['Aucun KW stuffing ?', 'Alt lisibles à voix haute ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 20 alt texts à partir de descriptions',
      prompt: 'Voici 20 images : [DESCRIPTIONS BRÈVES]. Rédige 1 alt text par image. Contraintes : ≤ 125 chars, descriptif factuel, intégrer KW « [KW] » si naturel (sinon skip). Aucun stuffing. Sortie tableau.' },
  ]),
  ...conseilsSenior([
    'Alt vide = image invisible pour Google.',
    'KW naturel > forcé.',
    'Décorative = alt="" (vide voulu).',
  ]),
  ...validationFinale('100% images ont alt renseigné.', 'Rapport Screaming Frog dans Projet → Documentation'),
  ...escalade('CMS empêche alt dynamique', 'Dev — trouver hook ou custom code'),
]

const SOP_LIENS_INTERNES: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Structurer maillage interne : chaque page importante reçoit 5+ liens depuis pages pertinentes',
    resultat: 'Silos thématiques clairs, 5+ liens internes par URL cible, anchor texts KW-riches',
    delai: '2 h pour site moyen',
    canal: CANAL,
    regle: 'JAMAIS anchor text « cliquez ici ». Toujours KW ou description.',
    prerequis: ['Mapping KW ↔ URL', 'Audit crawl fait'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. AUDIT MAILLAGE ACTUEL', {
    objectif: 'Compter liens entrants par URL',
    temps: '30 min',
    ou: 'Screaming Frog → Internal Links',
    actions: [
      'Screaming Frog → filtre pages profondes (level > 3 clicks depuis home)',
      'Rapport « Internal Inlinks » : compte par URL',
      'Note URLs avec < 5 inlinks (« orphelines »)',
    ],
    resultat: 'URLs orphelines identifiées.',
    verification: ['Compte inlinks par URL', 'Orphelines listées'],
    conseil: 'Page à 4+ clicks depuis home = enterrée. Google la considère peu importante.',
  }),
  ...etape('2. AJOUT LIENS + ANCHOR OPTIMISATION', {
    objectif: 'Ajouter 5+ liens vers chaque URL cible depuis pages pertinentes',
    temps: '1-2 h',
    ou: 'CMS édition manuelle OU plugin (Link Whisper)',
    actions: [
      'Pour chaque URL cible : cherche 5-10 pages thématiquement proches',
      'Insère lien contextuel avec anchor text = KW principal cible OU variant',
      'Varie les anchors (exact match, partial, branded)',
      'Priorité aux liens depuis pages à forte autorité interne (home, catégories)',
    ],
    resultat: 'Maillage renforcé.',
    verification: ['5+ inlinks par URL cible', 'Anchor variés', 'Pages thématiquement liées'],
    conseil: 'Un maillage bien fait = +30% trafic organique en 3 mois.',
  }),
  ...finalCheck(['0 URL orpheline (< 5 inlinks)', 'Anchor texts KW-riches', 'Variation anchor', 'Liens contextuels']),
  ...qaCheck(['Aucun « cliquez ici » ?', 'Silos cohérents ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Détecte URLs orphelines Screaming Frog',
      prompt: 'Export Screaming Frog Internal Links : [COLLE]. Identifie URLs avec < 5 inlinks. Pour chaque, propose 3-5 pages source (thématiquement proches) + anchor text KW-rich. Sortie tableau.' },
  ]),
  ...conseilsSenior([
    'Maillage interne = boost SEO le plus rapide et gratuit.',
    'Anchor texts variés > tous en exact match (over-optimization).',
    'Silos = pillar page + articles satellites reliés.',
  ]),
  ...validationFinale('Maillage renforcé, 0 orpheline.', 'Rapport maillage dans Projet → Documentation'),
  ...escalade('Site avec > 1000 pages : maillage manuel impossible', 'Dev — plugin (Link Whisper WordPress) ou algo custom'),
]

const SOP_SCHEMA: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Implémenter Schema.org JSON-LD pertinent pour rich snippets',
    resultat: 'Schema Organization + LocalBusiness (si local) + Article (blog) + FAQ + Product (e-com)',
    delai: '1-2 h',
    canal: CANAL,
    regle: 'JAMAIS de schema pour du contenu inexistant (Google pénalise).',
    prerequis: ['Site en production'],
  }),
  ...projectContext(['client.name', 'client.company', 'domain']),
  h2('Étapes'),
  ...etape('1. IDENTIFICATION SCHEMAS PERTINENTS', {
    objectif: 'Choisir 2-4 schemas prioritaires',
    temps: '15 min',
    ou: 'schema.org + Projet → Documentation',
    actions: [
      'Organization (obligatoire toutes home)',
      'LocalBusiness (si business local)',
      'Article (blog posts)',
      'FAQ (pages FAQ ou blocks)',
      'Product / Service (e-com ou service)',
      'BreadcrumbList (navigation)',
    ],
    resultat: 'Liste schemas à implémenter.',
    verification: ['2-4 schemas pertinents'],
    conseil: 'FAQ Schema = feature snippet quasi garanti si contenu réel.',
  }),
  ...etape('2. IMPLÉMENTATION + VALIDATION', {
    objectif: 'Insérer JSON-LD + valider Rich Results Test',
    temps: '1-2 h',
    ou: 'CMS (RankMath / Yoast intégrés) OU code manuel',
    actions: [
      'Option A - RankMath / Yoast Premium : configuration UI',
      'Option B - Code manuel : <script type="application/ld+json"> dans <head>',
      'Rich Results Test Google → colle URL → vérifie schemas détectés',
      'Vérifie warnings + erreurs',
    ],
    resultat: 'Schemas valides sans erreur.',
    verification: ['Rich Results Test OK', '0 erreur', 'Warnings résolus'],
    conseil: 'Rich Results Test > Structured Data Testing Tool (déprécié).',
  }),
  ...finalCheck(['2-4 schemas implémentés', 'Rich Results Test OK', '0 erreur', 'Warnings résolus']),
  ...qaCheck(['Schemas cohérents avec le contenu ?', 'RRT valide ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Génère JSON-LD Organization + LocalBusiness',
      prompt: 'Client [NOM], secteur [SECTEUR], adresse [ADRESSE], tél [TÉL], horaires [HORAIRES]. Génère JSON-LD Schema.org complet Organization + LocalBusiness (si applicable) + Website. Format prêt à coller dans <head>.' },
  ]),
  ...conseilsSenior([
    'FAQ Schema = feature snippet quasi garanti.',
    'Rich Results Test = source de vérité. Structured Data Testing Tool = déprécié.',
    'Ne mens jamais dans schema (Google pénalise).',
  ]),
  ...validationFinale('Schemas valides + Rich Results Test OK.', 'Section Schema dans Projet → Documentation'),
  ...escalade('Erreurs schemas persistantes après debug', 'Dev — audit HTML + JSON-LD manuel'),
]

/* ─── TECHNIQUE ──────────────────────────────────────────────────────── */
const SOP_VITESSE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Optimiser Core Web Vitals : LCP < 2.5s, CLS < 0.1, INP < 200ms',
    resultat: 'Score PageSpeed > 90 mobile, LCP OK sur 3 pages critiques',
    delai: '4-8 h selon état initial',
    canal: CANAL,
    regle: 'JAMAIS optimiser sans mesurer avant/après.',
    prerequis: ['Site accessible', 'PageSpeed Insights baseline notée'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. DIAGNOSTIC LCP', {
    objectif: 'Identifier ce qui bloque le LCP',
    temps: '30 min',
    ou: 'PageSpeed Insights + WebPageTest',
    actions: [
      'PSI mobile → note LCP element (image ? bloc texte ?)',
      'Si image LCP : vérifie taille (< 300 Ko idéal), format (WebP), lazy off pour LCP',
      'Waterfall WebPageTest : identifie ressources bloquantes',
      'Note top 3 optimisations',
    ],
    resultat: 'LCP diagnostiqué.',
    verification: ['LCP element identifié', 'Ressources bloquantes listées'],
    conseil: 'LCP image > 500 Ko = catastrophe mobile. WebP obligatoire.',
  }),
  ...etape('2. OPTIMISATIONS CLASSIQUES', {
    objectif: 'Appliquer les 5 wins standards',
    temps: '2-4 h',
    ou: 'WP Rocket / Perfmatters / Cloudflare',
    actions: [
      'Images : WebP + lazy loading (sauf LCP)',
      'JS : defer non critique + minify',
      'CSS : critical CSS inline + rest deferred',
      'Fonts : font-display swap + preload critiques',
      'Cloudflare : cache + minify + Rocket Loader (attention jQuery)',
    ],
    resultat: 'PSI 90+ visé.',
    verification: ['WebP actif', 'Lazy loading (sauf LCP)', 'Critical CSS'],
    erreurs: [['Rocket Loader casse jQuery', 'Désactive sur URL problématiques.']],
    conseil: 'Critical CSS = LCP -1s facilement. Invest.',
  }),
  ...etape('3. VALIDATION + BENCHMARKS', {
    objectif: 'Mesurer après optimisations',
    temps: '30 min',
    ou: 'PageSpeed Insights + Chrome Lighthouse',
    actions: [
      'PSI mobile 3 pages critiques',
      'Compare avant/après',
      'Note dans Projet → Documentation : avant | après | delta',
      'Objectif : LCP < 2.5s, CLS < 0.1, INP < 200ms',
    ],
    resultat: 'Benchmarks validés.',
    verification: ['Core Web Vitals dans zone verte', 'Delta chiffré'],
    conseil: 'Field data (CrUX) > Lab data. PSI utilise field 28 derniers jours si dispo.',
  }),
  ...finalCheck(['LCP < 2.5s', 'CLS < 0.1', 'INP < 200ms', 'WebP + lazy + critical CSS actifs', 'Avant/après documenté']),
  ...qaCheck(['3 pages testées ?', 'Field data OK ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Diagnostic waterfall WebPageTest',
      prompt: 'Waterfall WebPageTest CSV : [COLLE]. Identifie top 5 ressources bloquantes LCP : (1) type (image/CSS/JS), (2) taille, (3) timing, (4) optimisation possible. Sortie priorité impact/effort.' },
  ]),
  ...conseilsSenior([
    'Field data (CrUX) > Lab data. Regarde 28 derniers jours.',
    'Critical CSS + WebP + lazy = 80% du gain.',
    'Ne fais pas trust Rocket Loader aveuglément (jQuery casse).',
  ]),
  ...validationFinale('Core Web Vitals dans zone verte sur 3 pages.', 'Rapport PSI dans Projet → Documentation'),
  ...escalade('Site sur hébergement mutualisé faible', 'Chef de projet — migration VPS/CDN Cloudflare'),
]

const SOP_SITEMAP: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Générer + soumettre sitemap.xml propre à Search Console',
    resultat: 'sitemap.xml accessible /sitemap.xml, soumis SC, seulement URLs canoniques',
    delai: '30 min',
    canal: CANAL,
    regle: 'Sitemap contient uniquement URLs 200 canoniques. Aucun redirect, aucun 4xx.',
    prerequis: ['Site en prod'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. GÉNÉRATION', {
    objectif: 'Générer sitemap automatique',
    temps: '15 min',
    ou: 'RankMath / Yoast / plugin',
    actions: [
      'CMS : activer sitemap plugin (RankMath ou Yoast)',
      'Vérifier /sitemap.xml accessible et valide',
      'Exclure pages non pertinentes (login, tag pages vides, thank you)',
      'Split en sitemaps thématiques si > 50k URLs',
    ],
    resultat: 'Sitemap valide.',
    verification: ['Accessible /sitemap.xml', 'Uniquement canoniques', '< 50k URLs par sitemap'],
    conseil: 'Un sitemap avec des 301 dedans = confusion Google. Toujours 200 canoniques.',
  }),
  ...etape('2. SOUMISSION SEARCH CONSOLE', {
    objectif: 'Soumettre à Google + ping Bing',
    temps: '15 min',
    ou: 'Search Console',
    actions: [
      'Search Console → Sitemaps → soumettre URL sitemap',
      'Attendre 24-48h → vérifier statut « Réussi »',
      'Bing Webmaster Tools : ping sitemap (bonus)',
      'Ajouter dans robots.txt : Sitemap: https://[domaine]/sitemap.xml',
    ],
    resultat: 'Sitemap soumis SC.',
    verification: ['SC statut « Réussi »', 'robots.txt référence sitemap'],
    conseil: 'Bing = 5-10% du trafic search au Maroc. Non négligeable.',
  }),
  ...finalCheck(['/sitemap.xml accessible', 'URLs canoniques uniquement', 'Soumis SC', 'Dans robots.txt']),
  ...qaCheck(['Statut SC « Réussi » ?', 'Bing pingué ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Génère sitemap XML custom',
      prompt: 'Voici la liste des URLs canoniques du site : [COLLE]. Génère un sitemap.xml XML valide selon standard sitemaps.org : <urlset xmlns="..."><url><loc><lastmod><changefreq><priority>. Priorité 1.0 home, 0.8 catégories, 0.5 articles.' },
  ]),
  ...conseilsSenior([
    'Sitemap propre = 200 canoniques uniquement.',
    'Search Console statut « Réussi » avant de continuer.',
    'Bing = souvent oublié. Ping-le.',
  ]),
  ...validationFinale('Sitemap soumis SC + Bing.', 'Section Sitemap dans Projet → Documentation'),
  ...escalade('SC affiche « Sitemap could not be read »', 'Dev — vérifier accès + XML valid'),
]

const SOP_ROBOTS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Configurer robots.txt pour permettre crawl utile + bloquer parties privées',
    resultat: 'robots.txt propre : Allow /, bloque /admin /wp-admin /?param, référence sitemap',
    delai: '15 min',
    canal: CANAL,
    regle: 'JAMAIS Disallow: / (bloque tout Google). Erreur fatale.',
    prerequis: ['Accès serveur / FTP'],
  }),
  ...projectContext(['domain']),
  h2('Étapes'),
  ...etape('1. AUDIT ROBOTS ACTUEL', {
    objectif: 'Vérifier ce qui est bloqué actuellement',
    temps: '5 min',
    ou: '/robots.txt via navigateur',
    actions: [
      'Ouvre https://[domaine]/robots.txt',
      'Note règles actuelles',
      'Search Console → robots.txt Tester : vérifie que URLs importantes sont crawlables',
    ],
    resultat: 'Diagnostic actuel.',
    verification: ['Fichier accessible', 'Pas de Disallow: /'],
    conseil: 'robots.txt est le premier fichier Google lit. Vérifie-le tôt.',
  }),
  ...etape('2. RÈGLES OPTIMALES', {
    objectif: 'Configurer selon best practice',
    temps: '10 min',
    ou: 'FTP / plugin WordPress',
    actions: [
      'User-agent: *',
      'Disallow: /wp-admin/ + Allow: /wp-admin/admin-ajax.php (pour AJAX WooCommerce)',
      'Disallow: /?s= (recherche interne)',
      'Disallow: /author/ (WordPress si non utile)',
      'Sitemap: https://[domaine]/sitemap.xml',
    ],
    resultat: 'robots.txt propre.',
    verification: ['Test SC OK', 'Sitemap référencé', 'Zones sensibles bloquées'],
    conseil: 'Ne bloque JAMAIS /wp-content/uploads/ (images cassées SEO).',
  }),
  ...finalCheck(['Pas de Disallow: /', 'Sitemap référencé', 'Zones sensibles bloquées', 'Test SC OK']),
  ...qaCheck(['Aucune erreur SC ?', 'Uploads accessibles ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère robots.txt WordPress optimal',
      prompt: 'Site WordPress + WooCommerce sur [DOMAIN]. Génère robots.txt optimal : autorise crawl, bloque zones sensibles, référence sitemap. Explique chaque règle en commentaire.' },
  ]),
  ...conseilsSenior([
    'Disallow: / = suicide SEO. Ne fais jamais ça.',
    'Autorise /wp-content/uploads/ toujours.',
    'Référence sitemap dans robots.txt = practice standard.',
  ]),
  ...validationFinale('robots.txt propre + testé SC.', 'Contenu dans Projet → Documentation'),
  ...escalade('robots.txt inaccessible ou 404', 'Dev — créer fichier ou fixer permissions serveur'),
]

const SOP_HTTPS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Vérifier HTTPS partout + SSL valide + mixed content zero',
    resultat: 'Cadenas vert, redirect 301 HTTP → HTTPS, HSTS actif, zéro mixed content',
    delai: '1 h',
    canal: CANAL,
    regle: 'HTTP en 2024 = pénalité Google + Chrome affiche « Non sécurisé ».',
    prerequis: ['Accès serveur ou Cloudflare'],
  }),
  ...projectContext(['domain']),
  h2('Étapes'),
  ...etape('1. VÉRIFICATION SSL + REDIRECT', {
    objectif: 'Cadenas vert + HTTP → HTTPS 301',
    temps: '20 min',
    ou: 'Navigateur + SSL Labs',
    actions: [
      'Ouvre https://[domaine] → vérifie cadenas vert',
      'SSL Labs (ssllabs.com) : note score (A+ visé)',
      'Test HTTP : http://[domaine] doit rediriger 301 vers HTTPS',
      'Test www ↔ non-www : cohérence',
    ],
    resultat: 'HTTPS cadenas vert + SSL Labs A+ visé.',
    verification: ['Cadenas vert', 'SSL Labs A/A+', 'HTTP → HTTPS 301'],
    conseil: 'SSL Labs A+ vs A = petits détails (HSTS preload). Vise A+.',
  }),
  ...etape('2. MIXED CONTENT + HSTS', {
    objectif: 'Zéro ressource HTTP dans page HTTPS',
    temps: '30 min',
    ou: 'Console navigateur + JitBit SSL Check',
    actions: [
      'Console navigateur : cherche warnings « Mixed content »',
      'Fix : force HTTPS sur toutes les ressources (images, JS, CSS)',
      'Activer HSTS via header : Strict-Transport-Security',
      'Optionnel : preload HSTS (submit hstspreload.org)',
    ],
    resultat: 'Zéro mixed content.',
    verification: ['Console 0 warning', 'HSTS actif'],
    conseil: 'Un mixed content = cadenas dégradé. Fatal pour confiance user + SEO.',
  }),
  ...finalCheck(['SSL Labs A/A+', 'Redirect 301', 'Mixed content 0', 'HSTS actif']),
  ...qaCheck(['Cadenas vert partout ?', 'HSTS preload ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Corrige mixed content dans CMS',
      prompt: 'Ma page HTTPS a des warnings mixed content. Voici les ressources HTTP détectées : [COLLE]. Propose fix : (1) plugin WordPress SSL Insecure Content Fixer, (2) function.php snippet, (3) .htaccess rule pour forcer HTTPS. Choisis meilleur trade-off simplicité/robustesse.' },
  ]),
  ...conseilsSenior([
    'SSL Labs A+ = signal qualité pour Google.',
    'Mixed content casse le cadenas → perte confiance.',
    'HSTS = protection MITM. Toujours actif.',
  ]),
  ...validationFinale('HTTPS parfait + SSL Labs A+.', 'Rapport SSL dans Projet → Documentation'),
  ...escalade('Certificat SSL invalide ou impossible à installer', 'Chef de projet — Cloudflare Universal SSL OU Let\'s Encrypt via hébergeur'),
]

const SOP_SEARCH_CONSOLE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Configurer Search Console proprement : propriété, sitemap, alertes',
    resultat: 'Propriété vérifiée, sitemap soumis, alertes emails activées',
    delai: '30 min',
    canal: CANAL,
    regle: 'Search Console est le seul outil gratuit donnant la vérité Google. Configure-le rigoureusement.',
    prerequis: ['Compte Google client'],
  }),
  ...projectContext(['client.name', 'client.email', 'domain']),
  h2('Étapes'),
  ...etape('1. VÉRIFICATION PROPRIÉTÉ', {
    objectif: 'Ajouter + vérifier domain property',
    temps: '15 min',
    ou: 'search.google.com/search-console',
    actions: [
      'Ajouter propriété type « Domain » (couvre tous sous-domaines)',
      'Vérifier via DNS TXT (Cloudflare / registrar)',
      'Attendre 5-30 min propagation',
      'Alternative : URL Prefix property (par sous-domaine)',
    ],
    resultat: 'Propriété vérifiée.',
    verification: ['Vérification OK', 'Type Domain (recommandé)'],
    conseil: 'Domain property > URL Prefix. Couvre tout d\'un coup.',
  }),
  ...etape('2. SITEMAP + ALERTES + UTILISATEURS', {
    objectif: 'Config complète Search Console',
    temps: '15 min',
    ou: 'Search Console',
    actions: [
      'Sitemap : soumettre /sitemap.xml',
      'Paramètres → Utilisateurs : ajouter accès équipe (Owner / Full / Restricted)',
      'Alertes : Enable emails pour erreurs indexation, sécurité, action manuelle',
      'Bing Webmaster Tools : import automatique depuis Search Console',
    ],
    resultat: 'Config complète.',
    verification: ['Sitemap soumis', 'Alertes emails ON', 'Utilisateurs équipe'],
    conseil: 'Action manuelle Google = urgent. Configure alertes.',
  }),
  ...finalCheck(['Propriété vérifiée (Domain)', 'Sitemap soumis', 'Alertes emails', 'Utilisateurs équipe', 'Bing importé']),
  ...qaCheck(['Alertes emails activées ?', 'Bing importé ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Explique Search Console à un client',
      prompt: 'Rédige mini-guide 5 lignes pour client non-technique : que fait Search Console + comment lire les 3 métriques clés (clics, impressions, position moyenne) + comment lire un email d\'alerte. Ton : rassurant, simple.' },
  ]),
  ...conseilsSenior([
    'Search Console = vérité Google. Configure-le en 1er.',
    'Domain property > URL Prefix. Tout d\'un coup.',
    'Alertes emails vitales. Action manuelle = urgent.',
  ]),
  ...validationFinale('Search Console configuré complètement.', 'Screenshot vérification + sitemap dans Projet → Documentation'),
  ...escalade('Vérification DNS échoue', 'Dev — vérifier propagation DNS + record TXT exact'),
]

const SOP_GA4: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Installer GA4 + configurer événements clés + connexion Search Console',
    resultat: 'GA4 opérationnel, événements Purchase/Lead trackés, connecté SC',
    delai: '1-2 h',
    canal: CANAL,
    regle: 'GA4 n\'est PAS Universal Analytics. Migration events + property différente.',
    prerequis: ['GTM installé', 'Search Console vérifié'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. CRÉATION GA4 + TAG', {
    objectif: 'Créer propriété GA4 + installer tag via GTM',
    temps: '30 min',
    ou: 'analytics.google.com + GTM',
    actions: [
      'Créer propriété GA4 (compte du client)',
      'Copier Measurement ID (G-XXXXXXX)',
      'GTM → Balise Google Analytics: GA4 Configuration → Measurement ID',
      'Trigger : All Pages',
      'Publish GTM',
    ],
    resultat: 'GA4 collecte page views.',
    verification: ['Real-time GA4 affiche visite', 'Aucun doublon UA + GA4'],
    conseil: 'UA est mort juillet 2023. Purge tout GA UA existant.',
  }),
  ...etape('2. ÉVÉNEMENTS + CONVERSIONS', {
    objectif: 'Tag events clés + marquer comme conversions',
    temps: '45 min',
    ou: 'GTM + GA4 Admin',
    actions: [
      'Events : purchase, generate_lead, sign_up, view_item (e-com)',
      'GTM tags Custom Event pour chaque',
      'GA4 → Admin → Events → Mark as conversion',
      'Pass parameters : value, currency, items (e-com)',
    ],
    resultat: 'Events tagués + marqués conversions.',
    verification: ['Test Events GTM OK', 'Conversions marquées'],
    conseil: 'Enhanced Ecommerce ≠ GA4 e-commerce. Refonte events obligatoire.',
  }),
  ...etape('3. LIAISON SEARCH CONSOLE + BIGQUERY', {
    objectif: 'Lier SC + BigQuery pour analyse',
    temps: '15 min',
    ou: 'GA4 Admin → Product Links',
    actions: [
      'GA4 → Admin → Search Console Links → Link property',
      'BigQuery export : Admin → BigQuery Links (gratuit dans limites)',
      'Cross-domain tracking si applicable',
    ],
    resultat: 'Liaisons actives.',
    verification: ['SC lié', 'BigQuery export ON'],
    conseil: 'BigQuery = gratuit et illimité pour data brute. Active dès jour 1.',
  }),
  ...finalCheck(['GA4 collecte page views', 'Events + conversions', 'SC lié', 'BigQuery ON']),
  ...qaCheck(['Test Events OK ?', 'Aucun doublon UA ?']),
  ...promptCards([
    { agent: 'Claude Code', title: 'Migre events UA vers GA4',
      prompt: 'Voici mes events UA actuels : [COLLE]. Convertis-les au format GA4 (event_name + params snake_case). Pour ecommerce, utilise standard events GA4 (purchase, view_item, add_to_cart). Sortie mapping tableau + code GTM.' },
  ]),
  ...conseilsSenior([
    'UA mort juillet 2023. Purge complet.',
    'BigQuery gratuit dans limites — active dès jour 1.',
    'Enhanced Ecommerce ≠ GA4. Refonte events obligatoire.',
  ]),
  ...validationFinale('GA4 opérationnel + conversions + BigQuery.', 'Screenshots GA4 dans Projet → Documentation'),
  ...escalade('Data GA4 diverge de facturation e-commerce', 'Chef de projet — audit tracking'),
]

/* ─── SUIVI ──────────────────────────────────────────────────────────── */
const SOP_RAPPORT: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rapport positions mensuel : évolution KW + trafic + recommandations',
    resultat: 'Rapport 3 pages : positions | trafic | recommandations mois suivant',
    delai: '2 h par mois',
    canal: CANAL,
    regle: 'Rapport = chiffres + décisions. Pas de screenshots bruts.',
    prerequis: ['Suivi positions actif (Ahrefs / Semrush / SC)'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. EXTRACTION POSITIONS + TRAFIC', {
    objectif: 'Photo M vs M-1',
    temps: '30 min',
    ou: 'Search Console + Ahrefs',
    actions: [
      'SC 30j vs 30j précédents : clics, impressions, CTR moyen, position moyenne',
      'Ahrefs : positions KW principaux + top 10 gains / pertes',
      'Note KW passés en top 10 (Quick Wins)',
      'Note KW perdus (à investiguer)',
    ],
    resultat: 'Photo chiffrée.',
    verification: ['Métriques M vs M-1', 'Top gains/pertes'],
    conseil: 'Position moyenne SC est trompeuse. Regarde par KW critique.',
  }),
  ...etape('2. RÉDACTION 3 PAGES + PLAN', {
    objectif: 'Rapport client + plan mois suivant',
    temps: '1 h',
    ou: 'Projet → Documentation',
    actions: [
      'Page 1 : KPIs (clics, impressions, positions top 3/10/20)',
      'Page 2 : gains + pertes détaillés',
      'Page 3 : 3 priorités mois suivant + hypothèses',
      'Envoi Projet → Discussion + demande visio 30 min',
    ],
    resultat: 'Rapport prêt.',
    verification: ['3 pages max', '3 priorités mois suivant', 'Envoyé'],
    conseil: 'Un rapport sans plan mois suivant = signal d\'arrêt.',
  }),
  ...finalCheck(['SC + Ahrefs extraits', 'Top gains/pertes chiffrés', '3 pages max', '3 priorités mois suivant', 'Envoyé']),
  ...qaCheck(['Chiffres cohérents ?', 'Plan explicite ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige rapport SEO mensuel 1-pager',
      prompt: 'Données SEO client 30j : [COLLE]. Rédige rapport 1-pager : (1) 3 KPIs vs mois précédent, (2) 3 gains chiffrés + 2 pertes, (3) 3 priorités mois suivant. Zéro jargon. Max 400 mots.' },
  ]),
  ...conseilsSenior([
    'SEO ROI se voit sur 3-6 mois. Prépare le client.',
    'Position moyenne SC trompeuse. Regarde par KW.',
    'Plan mois suivant = obligation. Sinon client se demande pourquoi il paie.',
  ]),
  ...validationFinale('Rapport présenté + plan signé.', 'Fichier « Rapport_SEO_[Client]_[YYYYMM].pdf » dans Projet → Documentation'),
  ...escalade('Aucune progression 3 mois consécutifs', 'Chef de projet — audit stratégie complet'),
]

const SOP_RECOMMANDATIONS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Suggérer 5-10 nouveaux contenus mensuels basés sur KW gap + PAA + tendances',
    resultat: 'Liste 5-10 briefs contenus prêts à produire (title + KW + intent + structure)',
    delai: '2 h par mois',
    canal: CANAL,
    regle: 'Chaque contenu doit répondre à une intention identifiée (SC ou Ahrefs).',
    prerequis: ['Suivi Ahrefs / SC actif'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. IDENTIFICATION OPPORTUNITÉS', {
    objectif: 'Cherche KW à écrire',
    temps: '1 h',
    ou: 'Ahrefs + SC + AnswerThePublic',
    actions: [
      'Ahrefs Content Gap actualisé (nouveaux gaps vs concurrents)',
      'SC : requêtes où on ranke position 11-20 (Quick Wins)',
      'People Also Ask sur SERP KW principaux : nouvelles questions',
      'Google Trends : tendances saisonnières',
    ],
    resultat: 'Liste 20-30 opportunités.',
    verification: ['Sources multiples utilisées', 'Volume ≥ 100'],
    conseil: 'SC positions 11-20 = opportunité rapide (page existe, il faut booster).',
  }),
  ...etape('2. RÉDACTION BRIEFS + PRIORISATION', {
    objectif: '5-10 briefs prêts à produire',
    temps: '1 h',
    ou: 'Projet → Documentation',
    actions: [
      'Chaque brief : Title cible, KW principal + LT, intent, structure H2/H3, longueur cible',
      'Priorité : Quick Wins > KW gap facile > longue traîne',
      'Timeline : 2-3 contenus/mois selon capacité',
    ],
    resultat: '5-10 briefs.',
    verification: ['Structure H claire', 'KW LT associés'],
    conseil: 'Un brief clair économise 3h de rédaction chaotique.',
  }),
  ...finalCheck(['20-30 opportunités identifiées', '5-10 briefs priorisés', 'Structure H définie', 'Timeline claire']),
  ...qaCheck(['Chaque brief a intent claire ?', 'KW LT associés ?']),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère brief contenu à partir de KW',
      prompt: 'KW principal : [KW]. Intent : [transactionnel/informatif]. Volume : [X]. Génère brief complet : (1) title cible ≤60 chars, (2) meta desc ≤155, (3) structure H2/H3, (4) KW secondaires et LT, (5) longueur cible (mots), (6) FAQ questions.' },
  ]),
  ...conseilsSenior([
    'Quick Wins positions 11-20 = ROI le plus rapide.',
    'PAA → FAQ block = feature snippet quasi garanti.',
    'Un brief clair = 3h de rédaction économisées.',
  ]),
  ...validationFinale('5-10 briefs prêts à produire.', 'Section briefs dans Projet → Documentation'),
  ...escalade('Aucune opportunité de qualité (secteur saturé)', 'Chef de projet — repositionner niche'),
]

/* ═══════════════════════════════════════════════════════════════════════ */

export const SOP_INDEX_SEO: Record<string, SopBlock[]> = {
  [norm('Audit technique SEO')]:              SOP_AUDIT_TECHNIQUE,
  [norm('Audit contenu existant')]:           SOP_AUDIT_CONTENU,
  [norm('Audit concurrents')]:                SOP_AUDIT_CONCURRENTS,
  [norm('Recherche mots-clés principaux')]:   SOP_KW_PRINCIPAUX,
  [norm('Recherche mots-clés longue traîne')]: SOP_KW_LONGUE_TRAINE,
  [norm('Mapping mots-clés / pages')]:        SOP_KW_MAPPING,
  [norm('Meta Title optimisés')]:             SOP_META_TITLE,
  [norm('Meta Descriptions')]:                SOP_META_DESC,
  [norm('Balises H1/H2/H3')]:                 SOP_HN_STRUCTURE,
  [norm('Alt texts images')]:                 SOP_ALT_TEXTS,
  [norm('Liens internes')]:                   SOP_LIENS_INTERNES,
  [norm('Schema.org / Rich Snippets')]:       SOP_SCHEMA,
  [norm('Vitesse de chargement')]:            SOP_VITESSE,
  [norm('Sitemap.xml')]:                      SOP_SITEMAP,
  [norm('Robots.txt')]:                       SOP_ROBOTS,
  [norm('HTTPS / SSL vérifié')]:              SOP_HTTPS,
  [norm('Google Search Console')]:            SOP_SEARCH_CONSOLE,
  [norm('Google Analytics 4')]:               SOP_GA4,
  [norm('Rapport positions mensuel')]:        SOP_RAPPORT,
  [norm('Recommandations contenu')]:          SOP_RECOMMANDATIONS,
}
