/**
 * SOP — Facebook / Instagram Ads (15 tâches)
 * Rôle incarné : Senior Media Buyer — 30+ ans, 7-figure budgets, Meta Business Partner.
 */
import type { SopBlock } from '@/hooks/useSops'
import {
  introExpert, etape, finalCheck, qaCheck, promptCards,
  conseilsSenior, validationFinale, escalade, projectContext, h2,
} from './sopHelpers'

const norm = (s: string) => (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim()
const ROLE = 'Senior Media Buyer — 30+ ans, Meta Business Partner, 7-figure budgets DTC/local'
const CANAL = 'Blocage → Projet → Discussion (canal Ads)'

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_BRIEF: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Extraire l\'objectif business + KPI + audience + budget avant tout lancement',
    resultat: 'Brief 1-pager signé : objectif, KPI, cible, budget, échéance, offre.',
    delai: '45 min réunion client + 30 min rédaction',
    canal: CANAL,
    regle: 'JAMAIS lancer sans objectif business chiffré (leads/ventes) — pas juste « visibilité ».',
    prerequis: ['Fiche projet à jour', 'Historique conv 90j (ou benchmark secteur)'],
  }),
  ...projectContext(['client.name', 'client.company', 'project.budget']),
  h2('Étapes'),
  ...etape('1. RÉUNION OBJECTIF + KPI', {
    objectif: 'Convertir objectif marketing flou en KPI mesurable',
    temps: '45 min',
    ou: 'Visio (lien archivé dans Projet → Documentation)',
    actions: [
      'Question fondatrice : « Combien de leads/ventes ce mois-ci = campagne réussie ? »',
      'Convertit en KPI : CPA cible = budget / conversions attendues',
      'Vérifie faisabilité : CPA < AOV × marge × 0.5 (règle mi-marge)',
      'Note offre : produit + prix + différenciateur + garantie',
      'Signe objectifs par écrit dans Projet → Discussion',
    ],
    resultat: 'KPI CPA cible chiffré + validation client écrite.',
    verification: ['CPA cible en MAD', 'Objectif quantifié (X leads / Y MAD CA)', 'Validation écrite'],
    erreurs: [
      ['« Faire connaître la marque »', 'Non mesurable = échec assuré. Force à quantifier (recall, followers, portée).'],
      ['CPA cible = idéal client', 'Toujours 1.5× pour phase de learning. Explique-le.'],
    ],
    conseil: 'Un client qui ne sait pas chiffrer son objectif est un client qui te tiendra responsable de tout. Force la clarté.',
  }),
  ...etape('2. RÉDACTION BRIEF 1-PAGER', {
    objectif: 'Formaliser en 1 page pour signature',
    temps: '30 min',
    ou: 'Projet → Documentation → « Brief Meta Ads »',
    actions: [
      'Structure : Objectif business / KPI / Cible / Budget / Offre / Créas dispos / Contraintes',
      'Ajoute assumptions : taux conv landing, CTR cible, CAC cible',
      'Envoie via Projet → Discussion + demande signature',
    ],
    resultat: 'Brief signé, archivé.',
    verification: ['1 page A4 max', 'Signature client'],
    conseil: 'Un brief non signé n\'existe pas. Refuse de démarrer sans.',
  }),
  ...finalCheck([
    'Objectif business chiffré (leads ou CA)',
    'CPA cible calculé',
    'Cible + offre + budget définis',
    'Brief signé et archivé dans Projet → Documentation',
  ]),
  ...qaCheck([
    'Le CPA cible est-il × 1.5 pour absorber le learning ?',
    'L\'offre est-elle réellement différenciée ?',
    'Le budget respecte-t-il minimum 100 MAD/jour par ad set ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Convertit un objectif flou en KPI mesurable',
      prompt: 'Le client dit vouloir « [OBJECTIF FLOU] » pour Meta Ads. Aide-moi à le convertir en KPI mesurable : (1) objectif business quantifié (leads/ventes/MAD), (2) CPA cible calculé à partir de AOV [MAD] × marge [%] × 0.5, (3) budget minimum viable pour 30 conv/mois. Sortie : bloc structuré + 3 questions à poser au client pour valider.' },
  ]),
  ...conseilsSenior([
    'Sans brief signé, chaque désaccord finit à ta charge.',
    'Un client qui refuse de chiffrer son objectif = risque de non-paiement final.',
    'Toujours × 1.5 sur le CPA cible pour la phase de learning (30 conv/ad set en 7j).',
    'Le meilleur brief tient sur une carte postale. Simplicité = alignement.',
  ]),
  ...validationFinale('Brief signé écrit, CPA cible calculé, offre définie.', 'Fichier « Brief_Meta_[Client].md » dans Projet → Documentation'),
  ...escalade('Client refuse de chiffrer objectif', 'Chef de projet — souvent signal d\'attente irréaliste, à recadrer'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_AUDIENCE: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Définir 3 audiences distinctes : Prospection Broad, Retargeting chaud, Lookalike',
    resultat: 'Audiences configurées dans Business Manager, taille cohérente, exclusions mutuelles.',
    delai: '1 h',
    canal: CANAL,
    regle: 'JAMAIS d\'audience < 500k users en broad prospection Maroc. Sinon Google Meta ne peut pas optimiser.',
    prerequis: ['Business Manager configuré', 'Pixel installé 30+ jours', 'CRM export client (si dispo)'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. BROAD PROSPECTION AVANTAGE+', {
    objectif: 'Laisser Meta trouver la meilleure audience via signals + Advantage+',
    temps: '20 min',
    ou: 'Meta Ads Manager → Audience → Advantage+ Audience',
    actions: [
      'Créer audience Advantage+ : Meta trouve auto sur base des conversions passées',
      'Ajouter Audience Suggestions : centres d\'intérêt loose (2-3 max)',
      'Zone géo : Maroc (ou villes ciblées si local)',
      'Âge : 25-55 (large) — laisser Meta apprendre les vrais gagnants',
      'Placements : Advantage+ Placements ON',
    ],
    resultat: 'Audience broad prête, size affiché ≥ 500k.',
    verification: ['Advantage+ Audience ON', 'Zone géo correcte', 'Size ≥ 500k'],
    erreurs: [
      ['Cibler trop serré (5 centres d\'intérêt)', 'Meta 2024 déteste le targeting strict. Broad + signals.'],
      ['Age 20-30 seulement', 'Perd 60% des acheteurs réels. Laisse large.'],
    ],
    conseil: 'Depuis 2023, plus tu cibles serré, moins tu convertis. Broad + créa forte = gagnant.',
  }),
  ...etape('2. RETARGETING CHAUD (2 audiences)', {
    objectif: 'Créer les 2 audiences retargeting fondamentales',
    temps: '20 min',
    ou: 'Audiences → Custom Audience',
    actions: [
      'Custom Audience 1 : Site web visiteurs 30 jours (all URLs)',
      'Custom Audience 2 : Ajout au panier / Vue produit sans achat 30j',
      'Custom Audience 3 : Engagement IG/FB page 90j',
      'Créer exclusion : Purchasers 180j → à exclure de prospection',
    ],
    resultat: '3 audiences custom + 1 exclusion.',
    verification: ['Chaque audience ≥ 1000 users', 'Fenêtres cohérentes (30/90/180)'],
    conseil: 'Retargeting 30j panier abandonné a le ROAS le plus élevé — souvent 8-15× vs 3-4× broad.',
  }),
  ...etape('3. LOOKALIKE 1% ET CUSTOMER LIST', {
    objectif: 'Créer LAL sur top 25% acheteurs + upload CRM',
    temps: '20 min',
    ou: 'Audiences → Lookalike + Customer List',
    actions: [
      'Upload CRM client : email + tel hashés SHA-256 (Meta hasher auto en UI)',
      'Créer Custom Audience « Clients existants » depuis CRM',
      'Créer Lookalike 1% Maroc basé sur cette audience',
      'Créer LAL 1% basé sur « Purchase events 30j » (si volume)',
    ],
    resultat: '2 LAL 1% + Customer List uploadée.',
    verification: ['Match rate Customer List > 30%', 'LAL sizes = 250k (1% Maroc)'],
    erreurs: [
      ['LAL 5-10%', 'Trop broad, dilue le signal. Reste sur 1-2%.'],
      ['LAL sans hashing', 'Rejet RGPD. Meta impose SHA-256.'],
    ],
    conseil: 'LAL 1% des top 25% purchasers > LAL 1% de tous les visiteurs. Qualité > quantité.',
  }),
  ...finalCheck([
    'Advantage+ Audience broad configurée',
    '3 audiences retargeting (site 30j, panier abandonné, engagement 90j)',
    'Exclusions clients existants sur prospection',
    'LAL 1% × 2 (CRM + Purchases)',
    'Customer List uploadée match > 30%',
  ]),
  ...qaCheck([
    'Aucune audience < 1000 users ?',
    'Purchasers 180j exclus de prospection ?',
    'LAL basé sur 25% top purchasers (pas tous les buyers) ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Priorise structure audiences pour un secteur',
      prompt: 'Client vend [PRODUIT] au Maroc, budget [MAD/mois]. Propose la structure d\'audiences Meta Ads optimale : (1) Combien d\'Ad Sets Prospection Broad vs Advantage+ ? (2) Quels centres d\'intérêt légers (2-3 max) ? (3) Quelles audiences retargeting (fenêtres) ? (4) Faut-il LAL et sur quelle source ? Justifie chaque choix.' },
  ]),
  ...conseilsSenior([
    'Broad + Advantage+ > targeting serré. Meta 2024 récompense la simplicité.',
    'Retargeting panier abandonné = ROAS × 3-5 vs broad. Toujours créer.',
    'Exclusion mutuelle est aussi importante que l\'audience elle-même.',
    'LAL 1% (pas 3, 5, 10%). Reste focus sur la qualité.',
  ]),
  ...validationFinale('3 layers d\'audiences prêtes : broad, retargeting, LAL. Exclusions actives.', 'Screenshot Audience Manager dans Projet → Documentation'),
  ...escalade('Match Customer List < 20%', 'Chef de projet — CRM à nettoyer (emails invalides / doublons)'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_BUDGET: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Cadrer budget mensuel + split par phase (learning / scaling) + planning promo',
    resultat: 'Budget mensuel documenté, split par campagne, calendrier promo aligné',
    delai: '45 min',
    canal: CANAL,
    regle: 'JAMAIS < 100 MAD/jour par Ad Set. Sinon impossible d\'atteindre 50 conv/7j pour sortir du learning.',
    prerequis: ['Brief signé', 'CPA cible connu'],
  }),
  ...projectContext(['client.name', 'project.budget']),
  h2('Étapes'),
  ...etape('1. CALCUL BUDGET MINIMUM VIABLE', {
    objectif: 'S\'assurer que le budget permet 50 conv/7j par Ad Set',
    temps: '20 min',
    ou: 'Tableur dans Projet → Documentation',
    actions: [
      'Formule : Budget min/mois = CPA cible × 50 conv × 4 semaines × N Ad Sets',
      'Si budget client < min → réduire nombre Ad Sets OU accepter learning plus long',
      'Réserver 20% du budget pour scaling si perf > cible',
      'Note dans Projet → Documentation le calcul',
    ],
    resultat: 'Budget mensuel validé + marge scaling.',
    verification: ['≥ 50 conv/7j par Ad Set possible', 'Marge scaling 20%'],
    conseil: 'Un Ad Set sub-100 MAD/j apprend jamais. Mieux vaut 1 Ad Set à 200 MAD/j que 2 à 100.',
  }),
  ...etape('2. SPLIT PAR PHASE ET AD SET', {
    objectif: 'Ventiler entre prospection / retargeting / scaling',
    temps: '15 min',
    ou: 'Tableur',
    actions: [
      'Phase 1 - Testing (mois 1) : 100% prospection Broad + Advantage+',
      'Phase 2 - Scaling (mois 2+) : 70% prospection / 20% retargeting / 10% LAL',
      'CBO (Campaign Budget Optimization) : ON pour laisser Meta ventiler entre Ad Sets',
      'Sauf si scaling avancé → ABO (Ad Set Budget) pour contrôle fin',
    ],
    resultat: 'Split validé + choix CBO/ABO justifié.',
    verification: ['CBO en phase 1 (testing)', 'Splits % cohérents phase 2'],
    conseil: 'CBO = paresse contrôlée. ABO = maîtrise. Débute CBO, passe ABO quand tu comprends chaque Ad Set.',
  }),
  ...etape('3. CALENDRIER OFFRE / PROMO', {
    objectif: 'Aligner budget avec pics (weekend / promo)',
    temps: '10 min',
    ou: 'Projet → Documentation → « Calendrier promo »',
    actions: [
      'Note dates offres spéciales (soldes, ramadan, back to school)',
      'Prévois +30-50% budget pendant ces périodes',
      'Anticipe delivery restriction si offre forte trafic',
    ],
    resultat: 'Calendrier annuel prêt.',
    verification: ['3-5 dates majeures notées', 'Budget renforcé anticipé'],
    conseil: 'Ramadan au Maroc = comportement conso complètement différent. Prévois créas + budget spécifiques.',
  }),
  ...finalCheck([
    'Budget min/mois calculé avec formule 50 conv × 4 sem × Ad Sets',
    'Marge scaling 20% réservée',
    'CBO activé phase 1',
    'Calendrier promo annuel',
  ]),
  ...qaCheck([
    'Chaque Ad Set aura-t-il ≥ 50 conv/7j ?',
    'Le split % est-il cohérent avec l\'étape (testing vs scaling) ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Calcule budget minimum viable Meta Ads',
      prompt: 'Tu es Senior Media Buyer. Client vend [PRODUIT], AOV [MAD], marge [%], veut [NB] ventes/mois. Calcule : (1) CPA cible = AOV × marge × 0.5, (2) Budget min = CPA × 50 × 4 × N_ad_sets, (3) Nb max Ad Sets si budget donné [BUDGET], (4) recommandation CBO ou ABO. Sortie chiffrée + justif.' },
  ]),
  ...conseilsSenior([
    '100 MAD/jour minimum par Ad Set = règle absolue. Sinon Meta apprend jamais.',
    'CBO pour testing (moins de contrôle mais plus de vitesse). ABO pour scale.',
    'Réserve toujours 20% pour scaler ce qui marche + tester ce qui pourrait marcher.',
    'Ramadan modifie tout au Maroc. Prévois créas + budget spécifiques.',
  ]),
  ...validationFinale('Budget validé, split défini, calendrier promo prêt.', 'Section Budget dans Projet → Documentation'),
  ...escalade('Budget client < 3000 MAD/mois', 'Chef de projet — Meta Ads non viable, orienter vers Boost natifs + SEO local'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_VISUELS: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Produire 5+ visuels créas alignés avec l\'offre + testés par angle',
    resultat: '5-8 visuels finaux : 3 angles créa × 2-3 formats (1:1, 4:5, 9:16), rejet ratio < 5%',
    delai: '3-5 h',
    canal: CANAL,
    regle: 'JAMAIS de texte occupant > 20% de l\'image (règle Meta abolie mais impacte encore la delivery).',
    prerequis: ['Brief signé', 'Photos produits HD', 'Charte graphique'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. DÉFINITION 3 ANGLES CRÉATIFS', {
    objectif: 'Choisir 3 angles psycho distincts pour tester',
    temps: '30 min',
    ou: 'Projet → Documentation',
    actions: [
      'Angle 1 - Problème/Solution : « Fatigué de X ? Découvre Y »',
      'Angle 2 - Social Proof : « 500 clients Maroc ont choisi X »',
      'Angle 3 - Bénéfice concret : « X en 24h, garanti »',
      'Chaque angle = 1 headline + 1 visuel + 1 CTA distincts',
    ],
    resultat: '3 angles brief prêts.',
    verification: ['3 angles distincts', 'Chaque angle a headline + visuel + CTA'],
    conseil: 'Le meilleur angle est souvent le plus simple. Ne complexifie pas.',
  }),
  ...etape('2. PRODUCTION 5-8 VISUELS', {
    objectif: 'Créer variations format et angle',
    temps: '2-3 h',
    ou: 'Canva Pro / Photoshop / Figma',
    actions: [
      'Format 1:1 (Feed) : 1080x1080',
      'Format 4:5 (Feed portrait, gain espace mobile) : 1080x1350',
      'Format 9:16 (Reels/Stories) : 1080x1920',
      'Chaque angle en 2-3 formats',
      'Texte < 20% de l\'image (utilise Meta Image Text Check si dispo)',
      'Logo discret coin bas-droite (pas overlay agressif)',
    ],
    resultat: '5-8 visuels finaux exports.',
    verification: ['3 formats couverts', 'Texte < 20%', 'Logo présent mais discret'],
    erreurs: [
      ['Un seul format 1:1', 'Rate 60% des placements. Toujours 3 formats.'],
      ['Texte overlay bloque le produit', 'Réduit CTR de 30%. Texte en périphérie.'],
    ],
    conseil: 'Fais varier les couleurs de fond entre variantes (bleu vs vert vs jaune). Meta favorise la diversité visuelle.',
  }),
  ...etape('3. UPLOAD BIBLIOTHÈQUE + NAMING', {
    objectif: 'Uploader dans Meta Media Library avec convention naming',
    temps: '30 min',
    ou: 'Meta Business Suite → Media Library',
    actions: [
      'Convention naming : [Client]_[Angle]_[Format]_[Date] (ex : Brinova_SocialProof_9x16_20260710)',
      'Upload dans Media Library — accessible depuis Ads Manager',
      'Ajoute tags : angle, format, campaign',
      'Archive originaux dans Projet → Ressources / Créas',
    ],
    resultat: 'Bibliothèque prête, naming clair.',
    verification: ['Naming convention respectée', 'Tous les visuels uploadés'],
    conseil: 'Un naming rigoureux te sauvera des heures dans 6 mois quand tu voudras retrouver « le visuel qui marchait ».',
  }),
  ...finalCheck([
    '3 angles créatifs distincts définis',
    '5-8 visuels finaux produits',
    '3 formats couverts (1:1, 4:5, 9:16)',
    'Texte < 20% par image',
    'Naming convention respectée',
    'Archive dans Projet → Ressources',
  ]),
  ...qaCheck([
    'Les 3 angles sont-ils psychologiquement distincts ?',
    'Chaque visuel est-il testé mobile ?',
    'Aucun texte overlay > 20% de l\'image ?',
  ]),
  ...promptCards([
    { agent: 'Gemini', title: 'Génère 3 concepts créas pour un produit',
      prompt: 'Client vend [PRODUIT] au Maroc, cible [PROFIL]. Génère 3 concepts créas Meta Ads distincts : (1) Angle Problème/Solution, (2) Angle Social Proof, (3) Angle Bénéfice concret. Pour chaque : (a) Headline 40 char max, (b) Description visuelle 2 lignes, (c) CTA button (Learn More / Shop Now / Book), (d) Couleur dominante recommandée (HEX). Ton : direct, actionnable.' },
    { agent: 'ChatGPT', title: 'Copywriting primary text (accroche) par angle',
      prompt: 'Rédige 5 primary text (max 125 chars visibles) pour Meta Ads sur le produit [PRODUIT]. Angles : (1) urgence, (2) autorité, (3) social proof, (4) peur du manque, (5) gain rapide. Contraintes : 1 émoji max début, français Maroc, CTA implicite. Format tableau.' },
  ]),
  ...conseilsSenior([
    'La créa décide de 70% de la perf. La stratégie audience 30%. Investis en priorité dans la créa.',
    '3 angles × 2 formats > 6 visuels similaires. Meta a besoin de diversité pour tester.',
    'Le texte overlay < 20% est officiellement aboli mais impacte encore le CTR. Reste discipliné.',
    'Archive TOUT — même les créas ratées. Tu réutiliseras des éléments plus tard.',
  ]),
  ...validationFinale('5-8 visuels finaux uploadés, naming clair, archivés.', 'Section « Créas » dans Projet → Ressources'),
  ...escalade('Refus produit constant Meta (5+ rejets)', 'Chef de projet — vérifier policy (armes, alcool, promesses irréalistes)'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_VIDEO: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Produire 1-2 vidéos courtes (Reels/Stories 9:16) taillées pour la scroll speed',
    resultat: 'Vidéo 15-30s avec hook 3s, sous-titres burnt-in, CTA final, retention > 30%',
    delai: '4-8 h par vidéo (tournage + montage)',
    canal: CANAL,
    regle: 'Les 3 premières secondes = tout. Si la vidéo perd 70%+ à la 3e seconde, elle est morte.',
    prerequis: ['Concept validé', 'Personne à filmer OU stock footage + voice-over'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. SCRIPT + STORYBOARD', {
    objectif: 'Structurer la vidéo en 4 blocs : Hook / Problème / Solution / CTA',
    temps: '1 h',
    ou: 'Projet → Documentation → « Script vidéo »',
    actions: [
      'Hook (0-3s) : phrase choc, question ou visuel surprenant',
      'Problème (3-10s) : montre la douleur cible',
      'Solution (10-25s) : produit en action + bénéfice',
      'CTA (25-30s) : call-to-action clair + logo',
      'Total 15-30s max, 60s si Reels vraiment engageant',
    ],
    resultat: 'Script prêt + storyboard 4 scènes.',
    verification: ['Hook percutant', 'Bénéfice clair', 'CTA explicite'],
    erreurs: [
      ['Hook « Bonjour à tous »', 'Perd 80% en 2 secondes. Toujours phrase forte / question.'],
      ['Vidéo > 60s', 'Rate 90% de completion sur Reels. Reste 15-30s.'],
    ],
    conseil: 'Ta thumbnail est le 4e élément de créa. Choisis un frame avec un visage ou un contraste fort.',
  }),
  ...etape('2. TOURNAGE / MONTAGE', {
    objectif: 'Filmer 9:16 en éclairage propre + montage rapide (CapCut, Premiere Rush)',
    temps: '2-4 h',
    ou: 'CapCut (mobile) ou Premiere Rush',
    actions: [
      'Tournage vertical 9:16 (jamais paysage rotate — perd qualité)',
      'Éclairage frontal (fenêtre ou ring light)',
      'Coupe TOUT ce qui est mou — chaque seconde compte',
      'Ajoute sous-titres burnt-in (85% mobile users regardent sans son)',
      'Musique tendance (Sound library Meta) OU no music si dialogue',
      'Export : MP4 H.264, 1080x1920, 30fps, bitrate 8-10 Mbps',
    ],
    resultat: 'Vidéo finale 15-30s, sous-titrée, montée.',
    verification: ['Format 9:16', 'Sous-titres présents', 'Durée 15-30s', 'MP4 < 100 Mo'],
    conseil: 'Sous-titres BURNT-IN (dans la vidéo), pas fichier séparé. Meta ne les affiche pas sinon.',
  }),
  ...etape('3. UPLOAD + PLACEMENT REELS', {
    objectif: 'Uploader dans Ads Manager avec placement Reels + Stories',
    temps: '15 min',
    ou: 'Ads Manager → Créer annonce → Vidéo',
    actions: [
      'Upload MP4',
      'Choisir placements : Instagram Reels + Facebook Reels + Stories + Feed vertical',
      'Cover : sélectionner frame le plus impactant (0.5s ou 1s)',
      'Primary text court (60 char max sur mobile Reels)',
      'CTA button aligné avec la vidéo (Shop Now, Learn More)',
    ],
    resultat: 'Vidéo publiée dans Ads Manager, placement Reels prioritaire.',
    verification: ['Placements Reels ON', 'Cover attractive', 'CTA cohérent'],
    conseil: 'Meta 2024 pousse énormément Reels — investis-y en priorité.',
  }),
  ...finalCheck([
    'Script structuré Hook/Problème/Solution/CTA',
    'Vidéo 15-30s',
    'Format 9:16',
    'Sous-titres burnt-in',
    'Placements Reels + Stories',
    'Cover impactante sélectionnée',
  ]),
  ...qaCheck([
    'Le hook est-il vraiment percutant en 3s ?',
    'Les sous-titres fonctionnent-ils sans son ?',
    'Le CTA final est-il clair ?',
    'La vidéo tient-elle < 30s ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère script vidéo Meta Ads 30s',
      prompt: 'Rédige un script vidéo Meta Ads 30 secondes pour [PRODUIT], cible [PROFIL] au Maroc. Structure : Hook (3s) / Problème (7s) / Solution (15s) / CTA (5s). Format : | Timecode | Voix off / Action | Insert texte à l\'écran |. Hook = phrase choc ou question. Ton : direct, mobile-first. Français.' },
  ]),
  ...conseilsSenior([
    '3 premières secondes = tout. Investis 50% de ton temps sur le hook.',
    'Sous-titres burnt-in obligatoires. 85% des mobiles regardent sans son.',
    'Reels format 9:16 > Feed 1:1 en 2024. Meta priorise énormément.',
    'CapCut mobile suffit pour 90% des vidéos Ads. Pas besoin d\'Adobe.',
  ]),
  ...validationFinale('Vidéo finale prête, uploadée, placements corrects.', 'Section « Vidéos » dans Projet → Ressources'),
  ...escalade('Retention < 25% sur 3s après lancement', 'Chef de projet — hook à retravailler d\'urgence'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_COPY: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger 5 accroches primary text testables + variantes headline',
    resultat: 'Copywriting library : 5 primary text × 3 angles + 3 headlines par angle',
    delai: '2 h',
    canal: CANAL,
    regle: 'Aucun jargon marketing. Parle comme ton cousin te parlerait de l\'offre.',
    prerequis: ['Brief signé', 'Angles créas définis'],
  }),
  ...projectContext(['client.name', 'client.company']),
  h2('Étapes'),
  ...etape('1. RÈGLES DU COPY MOBILE-FIRST', {
    objectif: 'Comprendre les contraintes lecture mobile Meta',
    temps: '15 min',
    ou: 'Projet → Documentation',
    actions: [
      'Primary text : max 125 chars visibles avant « Voir plus »',
      'Headline : max 40 chars (bouton CTA à côté)',
      'Description : max 30 chars (rarement affichée)',
      '1 émoji max en début de ligne (pas fin)',
      'Aucun spam trigger : « Cliquez ici », « Cliquez maintenant » = boycott algo',
    ],
    resultat: 'Contraintes claires.',
    verification: ['Règles imprimées / notées'],
    conseil: 'Les 3 premiers mots du primary text sont tout ce que le user voit dans son feed. Fais-les compter.',
  }),
  ...etape('2. RÉDIGER 5 PRIMARY TEXT × 3 ANGLES', {
    objectif: 'Créer 15 accroches (5 primary × 3 angles)',
    temps: '1 h',
    ou: 'Projet → Documentation → « Copywriting »',
    actions: [
      'Angle 1 - Urgence : « [DERNIÈRES 48H] X à -30% seulement ce weekend »',
      'Angle 2 - Autorité : « Après 15 ans à [MÉTIER], on a créé [PRODUIT]... »',
      'Angle 3 - Social proof : « 3247 clients Maroc ont choisi X. Pourquoi ? »',
      'Chaque angle : 5 formulations différentes (variation ton, question, statement)',
      'Bannis « meilleur », « qualité premium », « leader » — vides de sens',
    ],
    resultat: '15 accroches prêtes.',
    verification: ['15 accroches', '3 angles distincts', 'Zéro adjectif générique'],
    erreurs: [
      ['« Meilleur produit du marché »', 'Le lecteur zappe. Sois spécifique.'],
      ['Émoji à la fin', 'Rate le scroll rapide. Émoji en début uniquement.'],
    ],
    conseil: 'Lis à voix haute. Si ça sonne comme une publicité, réécris.',
  }),
  ...etape('3. HEADLINES + CTA + TESTS', {
    objectif: 'Rédiger 3 headlines par angle + choisir CTA',
    temps: '45 min',
    ou: 'Ads Manager',
    actions: [
      'Headline (40 char max) : reprend le bénéfice principal',
      'CTA button : Shop Now (e-com) / Learn More (lead) / Sign Up (SaaS) / Book Now (services)',
      'Placeholder Description (30 char) — visible que placements spécifiques',
      'Notez dans Projet → Documentation : angle | primary | headline | CTA',
    ],
    resultat: 'Copy library complète.',
    verification: ['3 headlines × 3 angles = 9 headlines', 'CTA aligné offre'],
    conseil: '« Shop Now » convertit mieux que « Learn More » sur produit clair. Inverse pour service complexe.',
  }),
  ...finalCheck([
    '15 primary text (5 × 3 angles)',
    '9 headlines (3 × 3 angles)',
    'CTA button choisi cohérent',
    'Zéro adjectif générique',
    '1 émoji max en début',
    'Copy library archivée dans Projet → Documentation',
  ]),
  ...qaCheck([
    'Un ami à qui tu lis à voix haute comprend-il l\'offre en 5s ?',
    'Chaque angle est-il vraiment distinct ?',
    'Aucun spam trigger ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Génère 5 primary text par angle psycho',
      prompt: 'Tu es Senior Meta Ads Copywriter Morocco. Produit [PRODUIT], promesse [PROMESSE], cible [PROFIL, âge, revenu, douleurs]. Génère 5 primary text (max 125 chars) pour un carousel Meta Ads. Un angle par accroche parmi : peur du manque / autorité / social proof / nouveauté / gain rapide. 1 émoji max début. CTA implicite « Découvrir ». Format tableau : Accroche | Angle | Émotion visée.' },
  ]),
  ...conseilsSenior([
    'Un copy vide (« Meilleur X du Maroc ») coûte plus cher qu\'un copy honnête et spécifique.',
    'Lis à voix haute. Si tu rougis, c\'est trop vendeur. Si tu bâilles, c\'est mou.',
    'Les 3 premiers mots comptent 80%. Investis 80% du temps dessus.',
    'CTA button : tester Shop Now vs Learn More. Résultat souvent contre-intuitif.',
  ]),
  ...validationFinale('Copy library 15 primary + 9 headlines + CTAs prête.', 'Fichier « Copy_[Client].md » dans Projet → Documentation'),
  ...escalade('Copy rejetée policy Meta 3+ fois', 'Chef de projet — vérifier promesses / claims / language sensible'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_BM: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Configurer Meta Business Manager du client + accès agence + assets liés',
    resultat: 'BM configuré, agence en Admin, Pixel + Page + Compte Ads + Domaine liés',
    delai: '30-45 min',
    canal: CANAL,
    regle: 'JAMAIS créer un BM au nom de l\'agence pour un client. Le BM appartient au business.',
    prerequis: ['Compte Facebook business du client', 'Page FB du client', 'Compte IG business (idéalement)'],
  }),
  ...projectContext(['client.name', 'client.email', 'client.company']),
  h2('Étapes'),
  ...etape('1. CRÉER OU IDENTIFIER LE BM CLIENT', {
    objectif: 'S\'assurer que le BM est au nom du business, pas de l\'agence',
    temps: '15 min',
    ou: 'business.facebook.com',
    actions: [
      'Demande au client s\'il a déjà un BM (business.facebook.com/settings)',
      'Si oui → note l\'ID BM (Settings → Business info → ID)',
      'Si non → aide le client à créer son BM avec son propre profil FB personnel + email business',
      'Rôle client dans BM = Admin (jamais Employee)',
    ],
    resultat: 'BM client identifié + ID noté.',
    verification: ['Client est Admin de son BM', 'ID BM dans Projet → Infos & Accès'],
    erreurs: [
      ['BM créé au nom agence', 'Client dépendant. Créer au nom business.'],
      ['Client en Employee', 'Peut pas ajouter d\'accès. Force en Admin.'],
    ],
    conseil: 'Le client doit rester propriétaire de SON BM. Toi tu es partenaire.',
  }),
  ...etape('2. AGENCE PARTENAIRE + ACCÈS', {
    objectif: 'Lier le BM agence au BM client via Partner',
    temps: '15 min',
    ou: 'BM client → Business Settings → Partners',
    actions: [
      'Client : Business Settings → Business Info → Add Partner → coller BM ID agence',
      'Choisir assets à partager : Page, Compte Ads, Pixel, Catalogue, Domaine',
      'Rôles : Admin (Page + Ad Account), Standard (Pixel)',
      'Agence : Business Settings → Requests → Accept',
    ],
    resultat: 'Partenariat actif.',
    verification: ['Requests accepted côté agence', 'Assets visibles dans BM agence'],
    conseil: 'Partner Access > User Access individuel. Change d\'employé sans reconfigurer.',
  }),
  ...etape('3. LIAISON ASSETS + DOMAINE VERIFICATION', {
    objectif: 'Lier tous les assets + vérifier domaine',
    temps: '20 min',
    ou: 'BM → Business Settings → Data Sources / Brand Safety',
    actions: [
      'Data Sources → Pixels → nouveau ou existant → lier au compte Ads',
      'Accounts → Instagram accounts → lier compte IG business à la Page',
      'Brand Safety → Domains → ajouter [client].ma → vérifier via meta tag ou DNS',
      'Prioritize pixel events (Aggregated Event Measurement) : max 8 events par domaine',
    ],
    resultat: 'Tous les assets liés + domaine vérifié.',
    verification: ['Pixel actif « Health OK »', 'Domaine vérifié', 'AEM configuré (8 events)'],
    erreurs: [
      ['Domaine non vérifié', 'Depuis iOS 14, impossible de tracker sans. Vérifier d\'abord.'],
      ['+ de 8 events pixel', 'Meta ignore les excédents. Priorise les 8 les plus valuables.'],
    ],
    conseil: 'La vérification domaine est le prérequis à TOUT en 2024. Fais-la avant même de lancer une campagne.',
  }),
  ...finalCheck([
    'BM au nom du client',
    'Agence en Partner Admin',
    'Page FB liée',
    'Compte Ads lié',
    'Pixel actif Health OK',
    'IG Business lié à Page',
    'Domaine vérifié',
    'AEM configuré 8 events',
  ]),
  ...qaCheck([
    'Le client est-il Admin de son propre BM ?',
    'La vérification domaine est-elle validée ?',
    'AEM priorisé sur les 8 events valuables ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Explique vérification domaine à un client',
      prompt: 'Rédige un email court (max 10 lignes) au client [NOM] pour lui expliquer POURQUOI il doit vérifier son domaine [DOMAIN] dans Meta Business Manager. Vulgarise en 2 phrases (iOS 14 + tracking). Donne les 2 méthodes (meta tag vs DNS TXT). Ton : rassurant, direct, sans jargon.' },
  ]),
  ...conseilsSenior([
    'BM au nom du client = philosophie de partenariat sain.',
    'Partner Access > User Access — évite les reconfigurations à chaque changement d\'équipe.',
    'Domaine vérifié = prérequis absolu depuis iOS 14. Sans, tu perds 40% de tracking.',
    'AEM : priorise Purchase > AddToCart > Lead > ViewContent. Les 4 derniers events priorité basse.',
  ]),
  ...validationFinale('BM configuré, partenariat actif, assets liés, domaine vérifié, AEM OK.', 'Section « Meta BM » dans Projet → Infos & Accès'),
  ...escalade('Vérification domaine échoue après 48h', 'Chef de projet — souvent problème DNS TXT à re-vérifier'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_PIXEL: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Installer le pixel Meta + Conversions API (CAPI) pour tracking iOS 14+ résilient',
    resultat: 'Pixel + CAPI double envoi, deduplication OK, Events Manager Health « OK »',
    delai: '2-4 h selon plateforme',
    canal: CANAL,
    regle: 'JAMAIS pixel seul en 2024. CAPI obligatoire — pixel perd 30-40% en iOS 14+.',
    prerequis: ['BM configuré', 'Accès dev / GTM', 'Domaine vérifié'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. INSTALLER PIXEL DE BASE (via GTM)', {
    objectif: 'Poser le tag Meta Pixel sur toutes les pages',
    temps: '30 min',
    ou: 'GTM + Meta Events Manager',
    actions: [
      'Meta Events Manager → Data Sources → Add Pixel → nommer + créer',
      'Copier Pixel ID',
      'GTM → Balises → + Nouvelle → Custom HTML → coller script Meta base code',
      'Trigger : All Pages',
      'GTM → Preview → vérifier fire',
      'Events Manager → Test Events → vérifier PageView reçu',
    ],
    resultat: 'PageView reçu Events Manager.',
    verification: ['GTM Preview vert', 'Test Events reçoit PageView', 'Health « OK »'],
    erreurs: [
      ['Duplicate pixel (base + gtag direct)', 'PageView × 2 → confusion. Un seul point d\'entrée.'],
      ['Trigger sur DOM Ready au lieu Page View', 'Rate 5-10% des events. Utilise Page View.'],
    ],
    conseil: 'Toujours passer par GTM — évite refonte quand tu changes de plateforme.',
  }),
  ...etape('2. TAGGER LES ÉVÉNEMENTS CLÉS', {
    objectif: 'Tag les 8 événements valuables (AEM priorisé)',
    temps: '1-2 h',
    ou: 'GTM',
    actions: [
      'Événements à tagger (ordre AEM priorité) : Purchase > InitiateCheckout > AddToCart > Lead > ViewContent > Search > CompleteRegistration > Contact',
      'Chaque event = 1 tag GTM Custom HTML + trigger custom',
      'Purchase : pass value + currency + content_ids + content_type = product',
      'Lead : pass value estimated (voir SOP Google Ads tracking)',
      'GTM → Preview → simule chaque event → vérifie',
    ],
    resultat: 'Tous les events fire.',
    verification: ['8 events testés', 'Purchase envoie value + currency', 'AEM Order = perf priority order'],
    conseil: 'Purchase > ViewContent en AEM. Ne mets jamais ViewContent en position 1.',
  }),
  ...etape('3. CAPI (SERVER-SIDE) SETUP', {
    objectif: 'Envoyer les events aussi côté serveur pour résilience iOS 14+',
    temps: '1-2 h',
    ou: 'Options : Conversions API Gateway / Zapier / dev custom / Shopify natif',
    actions: [
      'Option A - Shopify/WooCommerce : activer intégration native Meta',
      'Option B - Custom : endpoint POST vers graph.facebook.com/vX/{PixelID}/events',
      'Payload : event_name + event_time + user_data (email/tel hashés SHA-256) + custom_data (value/currency)',
      'Inclure event_id (identifiant unique) — même que côté client → deduplication',
      'Events Manager → Deduplication check : ratio pixel/CAPI ~50/50',
    ],
    resultat: 'CAPI actif, dedup OK.',
    verification: ['Events reçus via Server (badge vert)', 'Dedup ratio proche 50/50', 'Match rate > 80%'],
    erreurs: [
      ['event_id différent pixel vs CAPI', 'Compte double. Toujours même event_id.'],
      ['User data non hashé', 'Match rate faible. SHA-256 obligatoire.'],
    ],
    conseil: 'CAPI récupère 30-40% des events perdus par iOS 14+. Non-négociable en 2024.',
  }),
  ...finalCheck([
    'Pixel base actif All Pages',
    '8 events tagués (AEM order)',
    'CAPI actif (Shopify natif OU custom)',
    'Deduplication OK (event_id identique)',
    'Health « OK » Events Manager',
    'Test Events valide chaque event',
    'AEM priorité configurée',
  ]),
  ...qaCheck([
    'Pixel + CAPI envoient le même event_id ?',
    'User data (email/tel) est-il SHA-256 hashé ?',
    'AEM priorise-t-il Purchase en 1 ?',
    'Match rate CAPI > 80% ?',
  ]),
  ...promptCards([
    { agent: 'Claude Code', title: 'Génère endpoint CAPI Node.js',
      prompt: 'Génère un endpoint Node.js Express POST /api/meta-capi qui reçoit du client { event_name, event_id, value, currency, email, phone } et forward vers Meta Conversions API. Hasher SHA-256 email + phone avant envoi. Utiliser access token env META_CAPI_TOKEN + pixel_id env META_PIXEL_ID. Inclure retry 3x si 5xx. Format : code TypeScript prêt à copier.' },
    { agent: 'ChatGPT', title: 'Debug pixel + CAPI dedup',
      prompt: 'Mon Events Manager Meta montre 1500 Purchase pixel + 800 Purchase CAPI mais deduplicated events = 1200. Analyse : (1) le dedup fonctionne-t-il ? (2) quel ratio est attendu ? (3) où peut être le problème (event_id / event_time différence) ? Sortie : diagnostic + 3 checks concrets.' },
  ]),
  ...conseilsSenior([
    'Pixel seul = 30-40% de perte iOS 14+. CAPI est vital.',
    'Deduplication via event_id identique. Sans, tu comptes double.',
    'AEM ordre : Purchase, InitiateCheckout, AddToCart, Lead — les 4 premiers priorisés.',
    'Match rate > 80% = qualité data. < 60% = revoir hashing ou format email/phone.',
  ]),
  ...validationFinale('Pixel + CAPI actifs, dedup OK, Health OK.', 'Section « Meta Tracking » dans Projet → Documentation'),
  ...escalade('Match rate < 50% CAPI', 'Chef de projet — problème hashing ou données CRM'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_AUDIENCES_CREATED: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Formaliser création dans BM des audiences déjà définies stratégiquement',
    resultat: 'Audiences visibles Ads Manager, prêtes à sélectionner dans Ad Sets',
    delai: '30 min',
    canal: CANAL,
    regle: 'JAMAIS créer une audience si tu ne sais pas dans quelle campagne tu vas l\'utiliser.',
    prerequis: ['Stratégie audiences définie (SOP précédent)', 'Pixel actif 30+ jours'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. CUSTOM AUDIENCES SITE WEB', {
    objectif: 'Créer les 3 CA site web fondamentales',
    temps: '15 min',
    ou: 'Ads Manager → Audiences → + Custom Audience → Website',
    actions: [
      'CA 1 : All visitors 30 days (source Pixel)',
      'CA 2 : People who added to cart 30 days (event = AddToCart)',
      'CA 3 : Purchasers 180 days (event = Purchase) — pour exclusion',
      'Nommer clairement : « [Client]_ST_[Description]_[Days] »',
    ],
    resultat: '3 CA site web créées.',
    verification: ['Sizes > 1000', 'Naming cohérent'],
    conseil: 'Naming rigoureux te sauve dans 6 mois quand tu auras 30 audiences.',
  }),
  ...etape('2. LOOKALIKE 1%', {
    objectif: 'Créer LAL 1% sur meilleure source',
    temps: '10 min',
    ou: 'Audiences → + Lookalike',
    actions: [
      'Source = Purchasers 30j (si volume) OU Customer List CRM',
      'Locations = Maroc',
      'Size = 1% (jamais 3, 5, 10)',
      'Naming : « [Client]_LAL_1%_[Source]_MA »',
    ],
    resultat: 'LAL 1% Maroc actif.',
    verification: ['Source qualifiée', 'Size 1%', 'Population estimée ~250k'],
    conseil: 'LAL 1% sur top 25% (Value-based) > LAL 1% sur tous les achats. Qualité > quantité.',
  }),
  ...etape('3. EXCLUSION LISTS', {
    objectif: 'Créer les listes d\'exclusion pour prospection propre',
    temps: '10 min',
    ou: 'Audiences',
    actions: [
      'Créer « Exclusion - Purchasers 180d »',
      'Créer « Exclusion - Site visitors 7d » (si retargeting séparé)',
      'Ces listes seront ajoutées en « Exclude » sur Ad Sets prospection',
    ],
    resultat: 'Exclusions prêtes.',
    verification: ['Listes créées', 'Utilisées dans Ad Sets prospection'],
    conseil: 'L\'exclusion est aussi importante que l\'audience. Sans, tu paies pour re-convertir tes clients.',
  }),
  ...finalCheck([
    '3 CA site web créées',
    'Custom Audience CRM uploadée (si dispo)',
    'LAL 1% créé',
    'Listes exclusion prêtes',
    'Naming cohérent partout',
  ]),
  ...qaCheck([
    'Aucune audience < 1000 users ?',
    'Purchasers 180d sont-ils exclus de prospection ?',
    'LAL 1% (pas 3-5-10) ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Analyse structure audiences existante',
      prompt: 'Voici la liste de mes audiences Meta Ads : [COLLE]. Analyse : (1) manque-t-il retargeting essentiels (site 30j, cart abandon, purchasers 180) ? (2) LAL 1% source qualité ? (3) exclusions actives ? Propose 3 audiences à créer / supprimer avec justification.' },
  ]),
  ...conseilsSenior([
    'Naming rigoureux + revue trimestrielle = bibliothèque saine dans 2 ans.',
    'LAL 1% Value-based (top 25%) bat LAL 1% classique. Toujours quand possible.',
    'Une exclusion active vaut 3 audiences ciblées.',
    'Nettoie les audiences dormantes (0 impression 90j) — bibliothèque = focus.',
  ]),
  ...validationFinale('Audiences créées, exclusions actives, naming cohérent.', 'Screenshot Audience Manager dans Projet → Documentation'),
  ...escalade('Aucune audience atteint 1000 users', 'Chef de projet — trafic site insuffisant, revoir stratégie'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_CATALOG: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Créer catalogue produits Meta + activer Advantage+ Shopping Campaigns (ASC)',
    resultat: 'Catalogue synchronisé, Dynamic Product Ads (DPA) fonctionnels, ASC prête',
    delai: '2-3 h selon plateforme e-com',
    canal: CANAL,
    regle: 'Sans catalogue, pas de retargeting produit-spécifique. Priorité 1 en e-commerce.',
    prerequis: ['Plateforme e-com (Shopify / WooCommerce)', 'Pixel + CAPI actifs'],
  }),
  ...projectContext(['client.name', 'domain']),
  h2('Étapes'),
  ...etape('1. CRÉER CATALOGUE + SOURCE', {
    objectif: 'Uploader source produits (feed Shopify / WooCommerce / manual)',
    temps: '45 min',
    ou: 'Meta Business Suite → Commerce Manager → Catalog',
    actions: [
      'Commerce Manager → Catalogs → Create → Type e-commerce',
      'Source :\n      • Shopify : intégration native (1 clic)\n      • WooCommerce : plugin Pixel for WooCommerce + feed URL\n      • Custom : upload CSV OU URL feed daily refresh',
      'Vérifie que tous les champs obligatoires sont mappés : id, title, description, price, availability, condition, image_link, link',
      'Attends premier import (5-30 min)',
    ],
    resultat: 'Catalogue actif avec produits.',
    verification: ['≥ 90% produits « Available »', 'Tous champs obligatoires OK'],
    erreurs: [
      ['Champs missing (brand, GTIN)', 'Advantage+ nécessite ces champs. Ajoute-les.'],
      ['Image link non HTTPS', 'Refus catalogue. Toujours HTTPS.'],
    ],
    conseil: 'Shopify natif = 2 min. WooCommerce nécessite un feed structuré + refresh régulier.',
  }),
  ...etape('2. ASSIGNER PIXEL + ÉVÉNEMENTS', {
    objectif: 'Lier pixel au catalogue pour matching automatique',
    temps: '20 min',
    ou: 'Catalog → Data Sources → Pixel',
    actions: [
      'Catalog → Data Sources → Assign Pixel',
      'Vérifie que les events ViewContent / AddToCart / Purchase envoient content_ids qui matchent les IDs catalogue',
      'Test dans Test Events : simule un ViewContent → vérifie que le content_id est reconnu par catalogue',
      'Sans matching, DPA ne peut pas retargeter les produits vus',
    ],
    resultat: 'Pixel matché avec catalogue.',
    verification: ['Match rate catalog > 80%', 'ViewContent envoie content_ids'],
    conseil: 'Le matching content_ids ↔ catalogue IDs est le point de rupture 90% des setups. Vérifie tôt.',
  }),
  ...etape('3. LANCER DPA / ASC', {
    objectif: 'Créer une campagne Advantage+ Shopping (ASC) ou DPA classique',
    temps: '30 min',
    ou: 'Ads Manager → Create Campaign → Sales → Advantage+ Shopping',
    actions: [
      'Choisir Advantage+ Shopping Campaign (ASC) — recommandé 2024',
      'Sélectionner catalogue',
      'Budget CBO (Advantage+ Budget)',
      'Audience Signals : localisation Maroc + intérêts loose (optionnel)',
      'Créas : dynamiques (utilisent le catalogue) + statiques (5-10 pour Meta test)',
      'Publish → laisser Meta apprendre 7 jours (learning phase)',
    ],
    resultat: 'ASC lancée.',
    verification: ['Catalogue lié', 'Budget CBO ON', 'Créas mix dynamiques + statiques'],
    conseil: 'ASC bat toutes les autres campagnes en 2024 sur e-commerce Maroc. Test avant tout.',
  }),
  ...finalCheck([
    'Catalogue créé + source configurée',
    '≥ 90% produits « Available »',
    'Champs obligatoires + brand/GTIN complets',
    'Pixel assigné, matching OK',
    'ASC / DPA active',
    'Créas dynamiques + statiques',
  ]),
  ...qaCheck([
    'Le matching content_ids ↔ catalog IDs fonctionne-t-il ?',
    'ASC vs DPA : justification claire du choix ?',
    'Feed catalogue refresh daily programmé ?',
  ]),
  ...promptCards([
    { agent: 'Claude Code', title: 'Génère feed catalogue XML pour WooCommerce',
      prompt: 'Génère un feed XML compatible Meta Catalog depuis un WooCommerce standard. Structure : <channel><item><g:id>, <g:title>, <g:description>, <g:price>, <g:availability>, <g:image_link>, <g:link>, <g:brand>, <g:condition>. Include : filter uniquement produits en stock, prix TTC, image HD. Format : code PHP endpoint qui expose le feed à /wp-content/plugins/meta-feed/feed.xml.' },
  ]),
  ...conseilsSenior([
    'ASC bat DPA en 2024 sur 80% des cas. Test toujours ASC first.',
    'Matching content_ids : LE point de rupture 90% des setups.',
    'Feed refresh > toutes les 24h — sinon stock desync = mauvaise expérience.',
    'Créa dynamique (via catalogue) + statique (Meta ML) = combo gagnant.',
  ]),
  ...validationFinale('Catalogue actif, ASC en learning, dépenses délivrées.', 'Section « Catalogue Meta » dans Projet → Documentation'),
  ...escalade('Matching < 60% après 48h', 'Chef de projet — souvent problème de format content_ids (string vs int)'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_LANCEMENT: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Lancer la première campagne : structure CBO, 2-3 Ad Sets, 3+ créas par Ad Set',
    resultat: 'Campagne active, learning en cours, monitoring 24-72h prêt',
    delai: '1-2 h setup + 7 jours observation learning',
    canal: CANAL,
    regle: 'Après lancement, NE TOUCHE À RIEN pendant 72h. Meta a besoin de collecter data.',
    prerequis: ['Brief signé', 'Audiences prêtes', 'Créas prêtes', 'Pixel + CAPI OK'],
  }),
  ...projectContext(['client.name', 'project.budget']),
  h2('Étapes'),
  ...etape('1. STRUCTURE CBO SIMPLE', {
    objectif: 'Créer 1 campagne CBO avec 2-3 Ad Sets max',
    temps: '30 min',
    ou: 'Ads Manager → Create Campaign',
    actions: [
      'Objectif : Sales (ou Leads selon business)',
      'Campaign Budget Optimization ON',
      'Advantage+ Placements ON',
      'Ad Set 1 : Advantage+ Audience (broad + signals)',
      'Ad Set 2 : Retargeting site 30j',
      'Ad Set 3 (optionnel) : LAL 1% Maroc',
      'Budget CBO : total mensuel / 30.4',
    ],
    resultat: 'Structure campagne prête.',
    verification: ['CBO ON', 'Advantage+ Placements', '2-3 Ad Sets max'],
    erreurs: [
      ['10 Ad Sets au lancement', 'Meta ne peut pas apprendre. 2-3 max.'],
      ['ABO au lancement', 'Bloque l\'optimisation cross-Ad Set. CBO obligatoire au démarrage.'],
    ],
    conseil: 'Simplicité au lancement, complexité au scaling. Pas l\'inverse.',
  }),
  ...etape('2. ANNONCES : 3+ CRÉAS PAR AD SET', {
    objectif: 'Chaque Ad Set = 3+ créas × 2 angles psychologiques minimum',
    temps: '45 min',
    ou: 'Ads Manager',
    actions: [
      'Par Ad Set : upload 3-5 créas (mix angles)',
      'Chaque annonce : primary text + headline + CTA button',
      'Format : mix 1:1 + 4:5 + 9:16 (Meta choisit selon placement)',
      'Publish tout d\'un coup',
      'Note dans Projet → Documentation : timestamps + hypothèses',
    ],
    resultat: 'Toutes créas publiées.',
    verification: ['3+ créas par Ad Set', 'Mix formats', 'Timestamps notés'],
    conseil: 'Meta ML a besoin de variance. 5 créas différentes > 5 identiques.',
  }),
  ...etape('3. MONITORING 24-72H NON-INVASIF', {
    objectif: 'Vérifier que ça délivre + tracking OK, sans toucher',
    temps: '10 min × 3 checks',
    ou: 'Ads Manager + Events Manager',
    actions: [
      '24h : vérifier delivery (impressions > 0), CTR > 0.5%, aucune erreur policy',
      '48h : vérifier conversions arrivent, Events Manager Health OK',
      '72h : première évaluation — CPA vs cible',
      'Aucune modification budget/enchère/créa pendant cette phase',
    ],
    resultat: 'Learning en cours proprement.',
    verification: ['Impressions > 0', 'CTR > 0.5%', 'Zéro modification'],
    erreurs: [
      ['Toucher au budget à 48h', 'Reset learning. Perte 7-14 jours.'],
      ['Créer un doublon car « ça délivre pas assez »', 'Divise le budget → chacun apprend moins.'],
    ],
    conseil: 'La patience est ta plus grande skill en Meta Ads. 72h non-intervention = règle d\'or.',
  }),
  ...finalCheck([
    'Campagne CBO active',
    '2-3 Ad Sets',
    '3+ créas par Ad Set',
    'Advantage+ Placements ON',
    'Tracking Events Manager Health OK',
    'Timestamp lancement noté',
    '3 checks planifiés 24/48/72h',
  ]),
  ...qaCheck([
    'Aucune modification prévue avant 72h ?',
    'Le budget CBO respecte-t-il 100 MAD/jour × Ad Set minimum ?',
    'Le monitoring est-il tracé (screenshots avant/72h) ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Check-list pre-lancement Meta campaign',
      prompt: 'Voici ma structure campagne Meta : [COLLE settings]. Fais une check-list pre-lancement en 15 points MAX : (1) budget vs learning phase, (2) audiences/exclusions, (3) créas variance, (4) pixel/CAPI, (5) landing pages test mobile, (6) tracking event Purchase actif. Sortie : checklist Markdown à cocher.' },
  ]),
  ...conseilsSenior([
    '72h non-intervention post-lancement = règle absolue. Discipline > envie de toucher.',
    'CBO simple > ABO fragmenté au démarrage. Meta ML a besoin d\'un container unique.',
    'Advantage+ Placements ON = laisse Meta placer aux meilleurs endroits.',
    'Note ton hypothèse initiale — dans 30 jours tu compareras avec la réalité (apprends toujours).',
  ]),
  ...validationFinale('Campagne en learning, tracking OK, monitoring programmé.', 'Section « Campagne active » dans Projet → Documentation'),
  ...escalade('Zéro impression après 24h', 'Chef de projet — problème policy ou budget trop bas'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_AB_MEDIA: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Tester systématiquement les créas via A/B tests structurés (1 variable)',
    resultat: 'Chaque test = 1 variable × 2 semaines × 30 conv/variante. Résultat capitalisé.',
    delai: '15 min setup + 2 semaines observation',
    canal: CANAL,
    regle: 'Un test avec < 30 conv/variante ne conclut RIEN. Aucune décision.',
    prerequis: ['Volume conv ≥ 60/mois', 'Ad Set actif'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. HYPOTHÈSE + VARIABLE UNIQUE', {
    objectif: '1 hypothèse, 1 variable, 1 KPI',
    temps: '15 min',
    ou: 'Projet → Documentation → « A/B Tests »',
    actions: [
      'Format : « Si je change [VARIABLE] alors [KPI] va [DELTA] parce que [POURQUOI] »',
      'Variables testables (par ordre d\'impact) : Créa image > Angle copy > Headline > CTA > Format vidéo/image > Placement',
      'Ne teste JAMAIS 2 variables en même temps',
      'KPI : CPA ou ROAS (pas CTR seul — vanity metric)',
    ],
    resultat: 'Hypothèse claire écrite.',
    verification: ['1 variable', 'KPI mesurable', '2 semaines minimum planifiées'],
    conseil: 'La créa image change la perf de 30-50%. Le CTA de 5-10%. Priorise par impact.',
  }),
  ...etape('2. LANCER TEST (Split Test Meta OU duplicate manuel)', {
    objectif: 'Configuration technique du test',
    temps: '20 min',
    ou: 'Ads Manager',
    actions: [
      'Option A - Meta Split Test (A/B Test officiel) : + Test → variable spécifique → durée 7-14j',
      'Option B - Duplicate manuel : dupliquer Ad Set, changer 1 variable, laisser tourner en parallèle',
      'Option A est plus rigoureux (split budget 50/50 forcé)',
      'Note timestamps dans Projet → Documentation',
    ],
    resultat: 'Test en cours.',
    verification: ['Split 50/50 confirmé', 'Timestamps notés', 'KPI clair'],
    conseil: 'Split Test Meta natif > duplicate manuel. Plus fiable statistiquement.',
  }),
  ...etape('3. ANALYSE + DÉCISION', {
    objectif: 'Décider après 14j OU 30 conv/variante',
    temps: '20 min',
    ou: 'Ads Manager + Projet → Documentation',
    actions: [
      'Vérifie ≥ 30 conv/variante ATTEINTES',
      'Compare KPI (CPA ou ROAS) : écart significatif > 15%',
      'Gagnant → archive control, garde variant',
      'Perdant → reverse ; capitalise la lesson',
      'Non conclusif → prolonge OU relance test différent',
    ],
    resultat: 'Décision tracée.',
    verification: ['≥ 30 conv/variante', 'Écart > 15% pour conclure', 'Lesson capitalisée'],
    conseil: 'Un test qui ne conclut pas est aussi précieux. Tu as appris que ce facteur ne bouge pas.',
  }),
  ...finalCheck([
    'Hypothèse « Si… alors… parce que… » écrite',
    '1 variable seulement',
    'Test lancé Split Test natif OU duplicate',
    '≥ 30 conv/variante ATTEINTES',
    'Écart > 15% pour déclarer gagnant',
    'Lesson tracée dans Projet → Documentation',
    'Prochain test planifié',
  ]),
  ...qaCheck([
    'Y a-t-il eu vraiment 1 seule variable ?',
    'Le KPI est-il un vrai KPI (CPA/ROAS, pas CTR seul) ?',
    'A-t-on attendu 30+ conv/variante ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Roadmap 10 A/B tests Meta 3 mois',
      prompt: 'Voici mes campagnes actuelles Meta : [COLLE]. Propose 10 A/B tests à faire dans 3 mois, priorisés par impact estimé × faisabilité (30 conv/variante en 2 sem). Variables testables : créa image, angle copy, headline, CTA, format vidéo, placement. Format : « Si je change [X] alors [KPI] +/-Y% parce que [Z] ».' },
  ]),
  ...conseilsSenior([
    'Créa image > tout le reste en impact. Teste d\'abord la créa.',
    'Meta Split Test natif > duplicate manuel. Utilise-le.',
    '15% d\'écart minimum pour appeler « gagnant ». Sinon reste sceptique.',
    'Documente TOUS les tests — ratés et gagnants. Ta science se construit sur 2 ans.',
  ]),
  ...validationFinale('Test conclu, décision prise, prochain test lancé.', 'Journal A/B dans Projet → Documentation'),
  ...escalade('Volume conv < 30/variante en 2 semaines', 'Chef de projet — accepter tests plus longs OU tester au niveau campagne'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_OPTIM: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Optimiser quotidiennement sans casser le learning : couper, scaler, tester',
    resultat: 'Actions quotidiennes tracées, perf stable, gains + 5-10% par mois',
    delai: '20-30 min/jour',
    canal: CANAL,
    regle: 'JAMAIS toucher un Ad Set en Learning. Attends la sortie (7-14j).',
    prerequis: ['Campagne 7+ jours', 'Tracking OK', 'KPIs cibles'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. AUDIT QUOTIDIEN 20 MIN', {
    objectif: 'Photographier la perf 24h, identifier signaux forts',
    temps: '20 min',
    ou: 'Ads Manager',
    actions: [
      'Filtre : hier ET 7 derniers jours',
      'Colonnes clés : Impressions, Reach, Frequency, CTR, CPA, ROAS, Delivery status',
      'Signaux rouges : Frequency > 3, CTR < 0.5%, CPA > cible × 1.5, Delivery « Limited »',
      'Signaux verts : ROAS > cible × 1.3, CTR > 1.5%, Delivery « Active »',
      'Note dans Projet → Documentation : 3 observations du jour',
    ],
    resultat: 'Photo perf + 3 signaux identifiés.',
    verification: ['Signaux rouges/verts identifiés', 'Observations tracées'],
    conseil: 'Fais l\'audit à heure fixe (matin) — la stabilité du process est aussi importante que l\'action.',
  }),
  ...etape('2. ACTIONS SÉLECTIVES (jamais > 20% changement)', {
    objectif: 'Agir seulement sur signaux forts, respecter learning',
    temps: '10 min',
    ou: 'Ads Manager',
    actions: [
      'CPA cible × 2 sur 7j ET Ad Set hors learning → couper Ad Set',
      'ROAS > cible × 1.5 sur 7j → scaler budget +15% max (jamais > 20%)',
      'Frequency > 3.5 → refresh créas ou pause Ad Set',
      'Créa Learning limited → augmenter budget campagne CBO',
      'AUCUN CHANGEMENT si Ad Set en Learning',
    ],
    resultat: 'Actions tracées.',
    verification: ['Chaque action < 20% changement', 'Learning respecté', 'Toutes actions tracées'],
    erreurs: [
      ['Scaler +50% d\'un coup', 'Reset learning. Perte 7-14j.'],
      ['Toucher Ad Set en learning', 'Reset learning. Attends fin.'],
    ],
    conseil: 'La discipline (< 20% par semaine) bat le génie (grosse action ponctuelle).',
  }),
  ...etape('3. REFRESH CRÉAS TOUS LES 14 JOURS', {
    objectif: 'Éviter fatigue Ad (frequency > 3-4, CTR décroissant)',
    temps: '10 min bi-mensuel',
    ou: 'Ads Manager',
    actions: [
      'Chaque 14 jours : ajoute 2-3 nouvelles créas dans chaque Ad Set',
      'Pause créas Frequency > 4 (fatigue)',
      'Garde les « evergreen winners » (créas qui perf 30+ jours)',
      'Utilise Dynamic Creative si possible',
    ],
    resultat: 'Bibliothèque créas refreshée.',
    verification: ['Frequency < 3 partout', 'Nouvelles créas ajoutées'],
    conseil: 'Un même créatif dépasse rarement 30 jours de perf. Prévois pipeline créa continue.',
  }),
  ...finalCheck([
    'Audit quotidien fait',
    'Actions < 20% changement',
    'Learning respecté (aucune modif sur Ad Set learning)',
    'Créas refreshées tous les 14j',
    'Actions tracées dans Projet → Documentation',
  ]),
  ...qaCheck([
    'Chaque action est-elle < 20% ?',
    'Aucun Ad Set en Learning n\'a été touché ?',
    'La fréquence est-elle sous contrôle (< 3.5) ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Diagnostic quotidien perf 3-liner',
      prompt: 'Voici mes stats Meta Ads hier vs 7j : [DATA]. Rédige un diagnostic 3-liner : (1) 1 signal fort du jour, (2) 1 action immédiate recommandée (< 20% changement), (3) 1 point à surveiller demain. Ton : direct, actionnable, moins de 100 mots.' },
  ]),
  ...conseilsSenior([
    'La discipline < 20% de changement / semaine bat toutes les stratégies avancées.',
    'Frequency > 3.5 = fatigue certaine. Refresh créas.',
    'Learning phase = tabou. Aucune modification.',
    'Un signal fort sur 7j > un signal fort sur 24h. Résiste à la panique.',
  ]),
  ...validationFinale('Actions du jour tracées, learning respecté, prochaine opti planifiée.', 'Log quotidien dans Projet → Documentation'),
  ...escalade('CPA × 3 vs cible 14j', 'Chef de projet — remise en cause structurelle (audit stratégie / créa)'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_RAPPORT_HEBDO: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rapport hebdo client 1-pager : perf + actions + priorités semaine suivante',
    resultat: 'Rapport tient sur 1 page, 3 chiffres clés + 2 actions + 2 priorités, signé',
    delai: '45 min par semaine',
    canal: CANAL,
    regle: 'JAMAIS un rapport rempli de screenshots. 1 phrase = 1 chiffre = 1 décision.',
    prerequis: ['Data 7 derniers jours', 'Actions tracées'],
  }),
  ...projectContext(['client.name']),
  h2('Étapes'),
  ...etape('1. EXTRACTION KPIS 7J', {
    objectif: 'Extraire 3 KPIs semaine + comparaison',
    temps: '15 min',
    ou: 'Ads Manager → rapport 7j',
    actions: [
      'KPIs : Dépenses / Conv / CPA / ROAS (si e-com)',
      'Compare vs semaine précédente + moyenne 4 semaines',
      'Ajoute delta % pour chaque',
      'Note top campagne + campagne à surveiller',
    ],
    resultat: 'Tableau KPIs 7j.',
    verification: ['3 KPIs minimum', 'Comparaison multiple'],
    conseil: 'Comparer semaine vs semaine ET vs moyenne 4 sem — évite les faux signaux.',
  }),
  ...etape('2. ACTIONS SEMAINE + IMPACT', {
    objectif: 'Lister 2-3 actions + impact chiffré',
    temps: '15 min',
    ou: 'Projet → Documentation',
    actions: [
      'Format : « [Action faite] → [Impact chiffré ou anticipé] »',
      'Ex : « Refresh 5 créas → CTR +18% », « Cut Ad Set X → 400 MAD/sem économisés »',
      'Screenshot preuve pour chaque',
    ],
    resultat: '2-3 actions × impact chiffré.',
    verification: ['Chaque action a impact', 'Preuves attachées'],
    conseil: 'Chiffrer chaque action = client voit ta valeur = renouvelle. Non-négociable.',
  }),
  ...etape('3. 2 PRIORITÉS SEMAINE SUIVANTE + ENVOI', {
    objectif: 'Formaliser 2 priorités + envoyer + signer',
    temps: '15 min',
    ou: 'Projet → Documentation + Discussion',
    actions: [
      'Structure rapport : KPIs → Actions → Priorités semaine suivante → 1 alerte / opportunité',
      'Priorités max 2 (au-delà = dilution)',
      'Envoie via Projet → Discussion + demande accusé lecture',
      'Optionnel : réunion 15 min visio si perf hors zone',
    ],
    resultat: 'Rapport envoyé, lu, éventuellement signé.',
    verification: ['1 page max', '3 KPIs + 2-3 actions + 2 priorités', 'Client acknowledge'],
    conseil: 'Le rapport est ta plus grande opportunité de storytelling. Ne le rate jamais.',
  }),
  ...finalCheck([
    '3 KPIs vs semaine précédente + 4 sem',
    '2-3 actions × impact chiffré',
    '2 priorités semaine suivante',
    '1 page max',
    'Envoyé Projet → Discussion',
  ]),
  ...qaCheck([
    'Un client non-technique comprend-il tout ?',
    'Chaque chiffre est-il vérifiable ?',
    'Le rapport tient-il vraiment en 1 page ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Rédige rapport hebdo Meta Ads 1-pager',
      prompt: 'Voici mes stats Meta Ads 7j : dépenses [MAD], conv [NB], CPA [MAD], ROAS [X] vs sem précédente [DELTAS]. Actions : [LISTE]. Rédige rapport client français 1-pager : (1) 3 KPIs en tableau, (2) 2-3 actions × impact chiffré MAD, (3) 2 priorités semaine suivante. Zéro jargon. Max 250 mots.' },
  ]),
  ...conseilsSenior([
    'Le rapport hebdo est ta plus grande arme de fidélisation. Ne le rate jamais.',
    'Chiffrer en MAD, pas en %. Le client pense en MAD.',
    '1 page A4 max. Personne ne lit 5 pages.',
    'Demande TOUJOURS un accusé lecture — trace de valeur.',
  ]),
  ...validationFinale('Rapport hebdo envoyé + lu (accusé + éventuellement signé).', 'Fichier « Rapport_[Client]_S[NUM].pdf » dans Projet → Documentation'),
  ...escalade('Client ne lit pas 3 semaines de suite', 'Chef de projet — signal fort de désengagement'),
]

/* ══════════════════════════════════════════════════════════════════════ */
const SOP_BILAN: SopBlock[] = [
  ...introExpert({
    role: ROLE,
    objectif: 'Rédiger bilan fin de campagne 3 pages : KPIs / apprentissages / roadmap',
    resultat: 'Bilan présenté + validé + roadmap suivante signée',
    delai: '3 h rédaction + 45 min présentation',
    canal: CANAL,
    regle: 'Un bilan sans roadmap est incomplet. Toujours proposer la suite.',
    prerequis: ['Campagne complète terminée', 'Toutes data extraites'],
  }),
  ...projectContext(['client.name', 'client.company', 'project.budget']),
  h2('Étapes'),
  ...etape('1. SYNTHÈSE KPIS GLOBAUX', {
    objectif: 'Photo globale de la campagne',
    temps: '1 h',
    ou: 'Ads Manager (full period) + Projet → Documentation',
    actions: [
      'KPIs : Dépenses totales / Impressions / Conv / CPA moyen / ROAS moyen',
      'Compare vs objectifs signés au brief initial',
      'Vs moyennes secteur (si dispo)',
      'Vs même période année précédente',
      'Extrait charts screenshot depuis Ads Manager',
    ],
    resultat: 'Tableau synthèse vs objectifs.',
    verification: ['Comparaison brief vs réalité', 'Delta % précisés'],
    conseil: 'Compare toujours vs le brief signé. Sinon impossible d\'évaluer honnêtement.',
  }),
  ...etape('2. APPRENTISSAGES 3-5 INSIGHTS', {
    objectif: 'Extraire les insights actionnables pour la suite',
    temps: '1 h',
    ou: 'Projet → Documentation',
    actions: [
      'Top créa (ROAS le plus élevé) + pourquoi',
      'Top audience (CPA le plus bas) + pourquoi',
      'Top angle psycho + pourquoi',
      'Signal à surveiller (fatigue, saison, etc.)',
      'Insights = base de la roadmap suivante',
    ],
    resultat: '3-5 insights structurés.',
    verification: ['Chaque insight actionnable', 'Justifié par data'],
    conseil: 'Les insights sont le vrai livrable. Le client renouvelle sur cette base.',
  }),
  ...etape('3. ROADMAP + PRÉSENTATION', {
    objectif: 'Proposer 3 pistes suivantes + faire signer',
    temps: '1 h',
    ou: 'Visio 45 min',
    actions: [
      'Rédige bilan final 3 pages : Synthèse → Insights → Roadmap',
      'Roadmap = 3 pistes (ex : scale ce qui marche, tester nouvelle audience, upsell)',
      'Chaque piste : objectif + effort + timeline + coût',
      'Visio 45 min : présentation 20 min + Q/A 25 min',
      'Signature roadmap dans Projet → Discussion',
    ],
    resultat: 'Roadmap signée pour phase suivante.',
    verification: ['Bilan 3 pages max', '3 pistes chiffrées', 'Signature écrite'],
    conseil: 'Un bilan sans roadmap = signal « on arrête ». Toujours proposer la suite.',
  }),
  ...finalCheck([
    'Synthèse KPIs vs brief initial',
    '3-5 insights structurés + justifiés',
    'Roadmap 3 pistes chiffrées',
    'Bilan 3 pages max',
    'Présentation visio faite',
    'Signature roadmap dans Projet → Discussion',
  ]),
  ...qaCheck([
    'Chaque KPI est-il comparé aux objectifs brief ?',
    'Chaque insight est-il actionnable ?',
    'La roadmap propose-t-elle 3 vraies pistes (pas 1 générique) ?',
  ]),
  ...promptCards([
    { agent: 'ChatGPT', title: 'Structure bilan fin de campagne',
      prompt: 'Voici data campagne complète : [COLLE]. Rédige bilan 3 pages : (1) synthèse KPIs vs objectifs brief [OBJECTIFS], (2) 3-5 insights structurés par data, (3) roadmap 3 pistes suivantes chiffrées. Ton : direct, orienté business. Max 800 mots.' },
  ]),
  ...conseilsSenior([
    'Le bilan est ta plus grande opportunité de storytelling — et de renewal.',
    'Compare TOUJOURS vs le brief signé. Sinon subjectivité.',
    'Roadmap = obligation. Sans, tu signals l\'arrêt.',
    'La visio 45 min bat le PDF envoyé — présence humaine renforce la relation.',
  ]),
  ...validationFinale('Bilan présenté, roadmap suivante signée par écrit.', 'Fichier « Bilan_[Client]_[Période].pdf » dans Projet → Documentation'),
  ...escalade('Client refuse la visio bilan', 'Chef de projet — signal de désengagement, à traiter en priorité'),
]

/* ══════════════════════════════════════════════════════════════════════ */

export const SOP_INDEX_META_ADS: Record<string, SopBlock[]> = {
  [norm('Brief client objectifs')]:         SOP_BRIEF,
  [norm('Définition audience cible')]:      SOP_AUDIENCE,
  [norm('Budget + planning')]:              SOP_BUDGET,
  [norm('Visuels publicitaires (5+)')]:     SOP_VISUELS,
  [norm('Vidéo courte (Reels/Stories)')]:   SOP_VIDEO,
  [norm('Copywriting accroches')]:          SOP_COPY,
  [norm('Business Manager configuré')]:     SOP_BM,
  [norm('Pixel Meta installé')]:            SOP_PIXEL,
  [norm('Audiences créées')]:               SOP_AUDIENCES_CREATED,
  [norm('Catalogue produits (si e-com)')]:  SOP_CATALOG,
  [norm('Lancement campagne')]:             SOP_LANCEMENT,
  [norm('A/B testing visuels')]:            SOP_AB_MEDIA,
  [norm('Optimisation quotidienne')]:       SOP_OPTIM,
  [norm('Rapport hebdomadaire')]:           SOP_RAPPORT_HEBDO,
  [norm('Bilan fin de campagne')]:          SOP_BILAN,
}
